### ISSUE TITLE
Dockerfile support

### ISSUE THREAD

**Issue by proppy** [drone/drone#1]
Is it possible to configure drone so that if your project already has a `Dockerfile`, you can omit the `script` part of `.drone.yml` and rely on the `Dockerfile` to build the image?

**Comment by bradrydzewski** [comment]
this can be considered closed based on work in the 0.4 branch (upcoming release). We have a Docker plugin that can run in privileged mode (Docker in Docker) to build and push images. We also have the ability to mount volumes on the host machines (such as the Docker unix socket).

the ability to build and publish images is much stronger in 0.4

**Comment by tingxin** [comment]
Hi bradrydzewski,
i used follow code to build image:
`  
      - build -f Dockerfile_local .
`
i got error like:
`
unable to evaluate symlinks in Dockerfile path: lstat /python3/src/xxxx-xxxxx.xxxxxxxxx.com/xxxx/Pubhub_Test_Drone/Dockerfile:
`
so it looks it still find the Dockerfile rather than Dockerfile_local

could you please tell me if i can use specify dockerfile?

thank you very much
