### ISSUE TITLE
Can "drone" run under a non-root user?

### ISSUE THREAD

**Issue by andrefernandes** [drone/drone#1006]
Can "drone" run under a non-root user?

**Comment by bradrydzewski** [comment]
sure, these are the steps you would need to take:

* modify the init script to run Drone as a different user. On Ubuntu it would be this file: https://github.com/drone/drone/blob/master/packaging/root/usr/share/drone/init/drone.conf
* make sure that the user running Drone is added to the Docker group. This will allow Drone to access the Docker daemon's unix socket
* update the Drone toml file to use a different port (ie not :80 since it requires root)
* optionally use somthing like iptables to route port :80 to :8000

feel free to ask any further questions in our chat room (gitter.im/drone/drone)
