### ISSUE TITLE
use travis-build to parse a YAML file

### ISSUE THREAD

**Issue by fommil** [drone/drone#1035]
We're considering moving to drone for our CI https://github.com/ensime/ensime-server/issues/974

But we have a few questions that I couldn't find answers to in your documentation:

1. can you take a `travis.yml` file defined in the project to define the various build stages for a simple sequential pipeline? (using the same rules for reporting and so on).
2. can remote workers be set up with a simple ssh login? What permissions does the user need to have?

I believe the travis file goes too far... it should not be used for setting up the system environment (that's the job of the docker image). In shippable, a new section called `docker_image` allows the definition of the docker image to use, which I think is ideal.

**Comment by bradrydzewski** [comment]
> can you take a travis.yml file defined in the project to define the various build stages for a simple sequential pipeline? (using the same rules for reporting and so on).

No. You would need to migrate to the `.drone.yml` format

> can remote workers be set up with a simple ssh login? What permissions does the user need to have?

A remote worker requires a Docker daemon that is exposed over TCP with TLS. Since Drone communicates with the Docker deamon over TCP (using the remote REST API) it does not require access to the machine or any special permissions. You can read more here:
http://readme.drone.io/setup/config/workers/

> I believe the travis file goes too far... it should not be used for setting up the system environment (that's the job of the docker image). In shippable, a new section called docker_image allows the definition of the docker image to use, which I think is ideal.

This is one of the primary reasons Drone deviates from the Travis format. When you configure a build in Drone you specify `image` instead of `language`. You can use any image in the Docker index as your build environment. See http://readme.drone.io/usage/build/images/

If you have additional questions feel free to ask in our chat room: [gitter.im/drone/drone](gitter.im/drone/drone)

**Comment by fommil** [comment]
this sounds awesome! :smile:
