### ISSUE TITLE
BitBucket integration not working

### ISSUE THREAD

**Issue by Dids** [drone/drone#1036]
I've pretty much followed everything here: http://readme.drone.io/setup/config/bitbucket/
The process itself is (as it should be) trivial, however it's not working.

After logging in to Drone through BitBucket, the returned URL is "/api/auth/bitbucket.org?oauth_verifier" (with a key and token), which results in a completely blank page. Additionally /var/log/upstart/drone.log also appends an empty line with a timestamp.

I'm using the latest .deb build on Ubuntu.

**Comment by djamelfel** [comment]
I think your issue come from the URL you set in Bitbucket (Manage account -> OAuth).
You should have something like: http://url.to.your.api/api/auth/bitbucket.org

**Comment by Dids** [comment]
My callback URL is set to http://drone.mydomain.com/api/auth/bitbucket.org.

**Comment by slawus** [comment]
I had same problem with github integration. In my case, I needed to use https:// instead of http, because there was an auto-redirect to https, which broke OAuth2.

**Comment by mopemope** [comment]
Try it.
```
$ sudo ntpd -q   
```
and
```
$ sudo hwclock --systohc --utc
```

**Comment by Dids** [comment]
@slawus I don't have HTTPS support by default (using Digital Ocean's pre-built image)
@mopemope Nope, sorry, didn't make a difference.

**Comment by dim** [comment]
We had the same problem until we realised that you must expose access to your repositories in the bitbucket permissions configuration to make it work. I think this is overly excessive, as some of our users (3rd parties, contractors, etc) are only 'watchers' and have no need to share all their code with our drone instance. I will try to look through the code and provide a PR but guidance is welcome.

**Comment by Dids** [comment]
@dim Care to elaborate on that? I'm the only user on my team on Bitbucket, and from what I can tell I have all the permissions necessary, still results in a white screen when trying to login using Bitbucket.

**Comment by dim** [comment]
Might not be related, but I did a little bit of debugging on our side and noticed that BitBucket's v1 API requires you to grant permissions to `Read your account information` and `Read your repositories and their pull requests`, because the [/v1/user](https://confluence.atlassian.com/bitbucket/user-endpoint-296092264.html#userEndpoint-GETauserprofile) endpoint which is used by Drone exposes both user and repository information. BitBucket have fixed this in their v2 API, where they have a strict separation between user and repo information.

To fix this, drone would have to migrate to use https://confluence.atlassian.com/bitbucket/version-2-423626329.html, I will create a separate ticket for it in https://github.com/drone/go-bitbucket

**Comment by bradrydzewski** [comment]
0.4 version of Drone has migrated to Bitbucket v2 API with Oauth2. I've been running it for the past few days and can confirm it is working well.

documentation for reference:
http://readme.drone.io/docs/setup/bitbucket.html
