### ISSUE TITLE
Question about build matrix

### ISSUE THREAD

**Issue by teodor-pripoae** [drone/drone#1070]
Hi,

I have a question about the build matrix new feature, but I don't think it's possible using the current format. What is the best solution for this use case:

I have an application which I want to be able to run on x86/x64 but also on arm architecture. I can add 2 build workers for this (1 for x64 and one for arm), but I have the following questions:

1. Can drone worker run on arm architecture ?
2. How can I make sure that one build will go on arm server and one on x64 server ?
3. I need different services images, for example `redis` for x64 and `arm-redis` for arm. Is this supported by build matrix ?

**Comment by bradrydzewski** [comment]
@teodor-pripoae I'm sure this could be achieved with the existing yaml / matrix approach, however it would probably require that you follow certain naming or tagging conventions with your images:

```
image: my-build-image:$$arch
matrix:
  arch:
    - arm
    - x64
```

> Can drone worker run on arm architecture ?

Drone speaks to Docker via the remote API and is only restricted to architectures that support Docker. So if Docker can run on arm, Drone will support it.

> How can I make sure that one build will go on arm server and one on x64 server ?

This is not possible today. There are a lot of different ways to customize our queue logic, including by priority and by resource. We should track this under #758

> I need different services images, for example redis for x64 and arm-redis for arm. Is this supported by build matrix ?

The example above demonstrates how this could be achieved using image naming conventions. This is really something, however, I look for Docker to solve. When Docker supports windows (coming this summer) what happens when I run `docker pull redis` on a windows server? How will Docker know to pull the windows version of Redis? I believe this is something the Docker team will solve as they support more architectures. We can then modify Drone, if necessary, to support Docker conventions

**Comment by bradrydzewski** [comment]
I'm going to close in favor of #758 which discusses queue / request routing customization. If there are additional, actionable enhancements we need to make to support arm we can log these as separate issues
