### ISSUE TITLE
Blank page after logging into gogs

### ISSUE THREAD

**Issue by lthibault** [drone/drone#1075]
Hello,

I've just installed drone and configured it to use a locally-installed gogs service via the following environment variables:

`DRONE_GOGS_URL=https://mygogsdomain.com`

`DRONE_GOGS_SECRET=[oath key]`

`DRONE_GOGS_OPEN=true`

When I visit the drone URL, I see a gogs button which prompts me for login credentials when clicked.  Upon entering my **gogs login** I'm redirected to a blank page at `https://mygogsdomain.com/api/auth/gogs`.

I'd appreciate any advice, as I'm at a complete loss.  Thanks!

**Comment by bradrydzewski** [comment]
Hi there, you can check the logs to see why authentication failed. We actually have really good logging in the authentication flow. The logs (on Ubuntu) are `/var/logs/upstart/drone.log`, however, this may vary on other systems. For example If Docker, you can run `docker logs <container id>`.

This happens all the time. It is probably a small misconfiguration (typo, etc) or could be caused if you are using a self-signed cert and don't have things correctly setup on your Drone machine, in which case you can use `skip_verify`. Either way, the logs will reveal the problem and solution

We have an open issue (#542) to improve error messages, which is fixed in upcoming 0.4

**Comment by bradrydzewski** [comment]
PS feel free to use our chat room (gitter.im/drone/drone) for help and questions

**Comment by lthibault** [comment]
@bradrydzewski Thanks for the hint (still very new to docker).  The problem does indeed stem from a self-signed certificate and `skip_verify` seems to have done the trick.

Many thanks!
