### ISSUE TITLE
[Drone, Gitlab] "Activate Now" returns 500 Internal Server Error

### ISSUE THREAD

**Issue by richarddowner** [drone/drone#1086]
Gitlab version:  7.12.2

Steps:
- Setup Drone in gitlab under applications
```
Name: Drone
Callback URL: http://drone.[myserver].com/api/auth/gitlab.com
```
- Setup drone.yml with client and secret keys to talk to gitlab
```
[gitlab]
url = "http://gitlab.[myserver].com"
client = "exampleclientkey"
secret = "examplesecretkey"
skip_verify=false
open=false
```
- Activate returns:
```
POST http://drone.[myserver].com/api/repos/gitlab.[myserver].com/user/test 500 (Internal Server Error)
```

Logs:
- Nothing in the apache log for gitlab
- Not sure where else to look

Cheers

**Comment by bradrydzewski** [comment]
a 500 error occurs when Drone cannot add the post-commit hook or register the deploy key with GitLab. This can happen if you don't have admin rights to the repository, which is required to complete these tasks.

There is also an issue when running GitLab behind a proxy. Looks like, based on your recent comment, this might be the issue?
https://github.com/drone/drone/issues/1043#issuecomment-118990277

We have an open issue for improving error messaging and logging (#542), both of which have been fixed in the next release. Therefore I'm going to close this, and we can re-open if we determine this is a new issue unrelated to existing open ones.

Also, feel free to jump on `gitter.im/drone/drone` to discuss
