### ISSUE TITLE
Inconsistent use of `*_url` in JSON

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#1173]
We currently have an inconsistent use of `_url` prefix in our JSON data. For example, we use `link_url` and `clone_url` in some cases, and use `avatar` instead of `avatar_url` in other cases. Avatar may be the only example, but we need to audit and fix so that we can finalize the REST api

**Comment by bradrydzewski** [comment]
occurrences of `_url` in the types:

```
./system.go:	Link    string   `json:"link_url"`
./repo.go:	Self     string `json:"self_url"`
./repo.go:	Link     string `json:"link_url"`
./repo.go:	Clone    string `json:"clone_url"`
./status.go:	Link     string `meddler:"status_link"     json:"target_url"`
```

**Comment by donny-dont** [comment]
I just see avatar as the sole case from the generated code from https://github.com/dogma-dart-apis/dogma-drone-api. Since its an image source I'm personally not too offended by it not having a _url attached to it. I'd probably prefer avatar_src since that fits with an img tag but I'm not too opinionated on that.

**Comment by donny-dont** [comment]
Only other thing I see that could maybe be nitpicked outside of the _url stuff is keypair. Not sure if that should be key_pair.
