### ISSUE TITLE
github auth defaulting to open

### ISSUE THREAD

**Issue by fommil** [drone/drone#1183]
Despite what the docs say, self registration is allowed unless I explicitly added `open=false`

REMOTE_CONFIG="https://github.com?client_id=$CLIENT&client_secret=$SECRET&open=false"

**Comment by bradrydzewski** [comment]
I had difficulty reproducing. I have the following configuration with `open=false` omitted:

```
REMOTE_DRIVER="github"
REMOTE_CONFIG="https://github.com?client_id=$CLIENT&client_secret=$SECRET"
```

I tried to login from a test account and got the following:

![image](https://cloud.githubusercontent.com/assets/817538/9667676/0bb4af02-5232-11e5-9f2f-b7088ed1c41c.png)

Let's see if we can get someone else from the gitter room to reproduce

**Comment by tboerger** [comment]
Where is the default value defined? I have not found it

**Comment by tboerger** [comment]
Just an unset value that should be nil, right?

**Comment by bradrydzewski** [comment]
@tboerger unset primitives in Go default to their zero value. In the case of a boolean, this is `false`. So by default the `open` parameter should be set to false if a) it isn't specified or b) it fails to parse the `open` value as a boolean

**Comment by bradrydzewski** [comment]
@fommil were you the first user to login? The `open=false` parameter is ignored if there are no users in the system, and the first user to authenticate becomes the system admin.

**Comment by donny-dont** [comment]
I checked this locally with the latest and greatest 0.4 deb on an internal GHE instance and I do not see the behavior reported. Had someone else login and although its a little weird that it started the OAuth flow and THEN failed she was not able to get in until I added the `&open=true` to the query string.

I think this can probably be closed.

**Comment by bradrydzewski** [comment]
@donny-dont thanks for your help looking into this.

I'm fairly certain this was due to the fact that @fommil was the first account to login to his instance -- when registration is closed the very first user to login is presumed to be the installer, and is therefore granted sysadmin privilege.

This is the intended behavior as it solves a chicken-and-egg issue. If registration is closed we need to find a way to grant the very first user access so that they can provision additional accounts.

**Comment by fommil** [comment]
ok, that's probably what it was.
