### ISSUE TITLE
Azure Deployment Plugin

### ISSUE THREAD

**Issue by jasonwilliams200OK** [drone/drone#1207]
Please provide ability to deploy on Azure.
Here are some links for your reference:

* http://blogs.msdn.com/b/holgerkenn/archive/2014/03/20/azure-from-the-linux-command-line-part-1.aspx
* http://blogs.msdn.com/b/holgerkenn/archive/2014/04/15/azure-from-the-linux-command-line-part-2.aspx
* https://github.com/Azure/azure-xplat-cli
* https://github.com/Azure/azure-cli-docker
* https://github.com/Azure/azure-docker-extension
* https://github.com/Azure/azure-linux-automation
* https://github.com/Azure/azure-linux-extensions
* https://github.com/Azure/WALinuxAgent

On a bright side, it will provide additional opportunities for service consumers IMO.

**Comment by bradrydzewski** [comment]
@jasonwilliams200OK all deployment functionality (as well as notifications, reporting, etc) is being moved to external plugins that sit outside this project. The expectation is, for the most part, that these plugins are community contributed since the core Drone team (which is just me) can focus on making the core Drone server excellent.

If you have an immediate need for an Azure plugin I encourage you to read about our plugin model and contribute. Otherwise perhaps someone else in the community will see this issue and will contribute.

Documentation for creating plugins:
http://readme.drone.io/docs/plugin/

**Comment by bradrydzewski** [comment]
thanks to @tboerger we now have a plugin for this. See http://readme.drone.io/plugins/azure_web_apps/
