### ISSUE TITLE
Rejected post commit hook but commit is built

### ISSUE THREAD

**Issue by wolfgang42** [drone/drone#1212]
I have Drone running as a docker container, connected to a local GitLab instance. Every time I push a commit, `droned` logs the following messages:
```
2015/09/23 22:24:35 Rejected post commit hook for [repository]. Token mismatch
2015/09/23 22:24:35 Rejected post commit hook for [repository]. Token mismatch
2015/09/23 22:24:35 Rejected post commit hook for [repository]. Token mismatch
starting build
2015/09/23 22:24:57 dial tcp :0: connection refused
2015/09/23 22:24:57 subscription's close channel received message
```

The build *runs* just fine, but I'd like to know what's causing these messages. Reading [hook.go](https://github.com/drone/drone/blob/bdd4742171f359098953751e792d28fe2c8947ac/server/handler/hook.go#L66) it looks like if the post-commit hook is rejected the build should never even start.

**Comment by bradrydzewski** [comment]
@wolfgang42 here is the line of code that is failing:
https://github.com/drone/drone/blob/master/server/handler/hook.go#L66:L69

This happens if a build is triggered but has an invalid token. A secret token is placed in the hook URL to verify it comes from GitLab / GitLab / etc, and isn't being spoofed. Off the top of my head, I would expect this to happen if you delete a repository and re-add to Drone and the old hooks aren't cleaned up and therefore have an old token.

Feel free to direct further questions in our gitter channel at https://gitter.im/drone/drone
