### ISSUE TITLE
Git clone hangs when using depth

### ISSUE THREAD

**Issue by brgaulin** [drone/drone#1243]
Not sure what is happening but I decided to give a go with the new 0.4.0 branch and I can't clone my repo =(

This is the console output
```
[info] Pulling image plugins/drone-git:latest
$ git init
Initialized empty Git repository in /drone/src/github.company.com/bgaulin/app/.git/
$ git remote add origin https://github.company.com/bgaulin/app.git
$ git fetch --no-tags --depth=50 origin +refs/heads/development:
```

When I do a docker exec with that fetch command and verbose it just hangs. But when I remove the --depth argument, it seems to go just fine.

So I guess the easier request would be to remove the --depth as being necessary. But I was wondering first if anyone else had this issue and worked through it.

This is using github enterprise. 

The verbose output just has this one line
```
POST git-upload-pack (143 bytes)
```

Kind of solved:

To get around this for now I specified tags: true. That cancels the shallow clone which apparently does it.. so maybe nevermind this issue.

Figured I would still submit this in case someone else hits this issue

**Comment by bradrydzewski** [comment]
are you using an older version of GitHub enterprise? I think someone else had this issue and it was solved when they upgraded to a newer version

**Comment by brgaulin** [comment]
It definitely isn't latest. But isn't too old. And drone 0.3 is ok with it. So probably a specific edge case where the drone git client is too new for me :) and the workaround of asking for tags seems to work ok until they update our GHE



--Brendan Gaulin

(508) 728-3582

**Comment by bradrydzewski** [comment]
In 0.4 we switched from `git+ssh` to `git+https`. The company that also experienced this issue was running a version of GitHub Entperprise from Dec 2014 (which they said was end of life last month). They are in the process of upgrading and found this was no longer an issue in the newer version of GitHub Enterprise (v2.1).

In the meantime, until they are fully migrated, we added a special parameter called `ssh=true` that will override and use `git+ssh` instead of `git+http`. You can set this parameter in your remote configuration string.

Let me know if you have any luck there

**Comment by brgaulin** [comment]
That also works! But our ssh stuff is a bit annoying and I'm going to just stick to requesting tags, doesn't add too much time.

Thanks a ton!
