### ISSUE TITLE
Inject secure parameters into Pull Requests

### ISSUE THREAD

**Issue by rymir** [drone/drone#1250]
https://github.com/drone/drone-exec/blob/b7e1c4c39b31d58aaeb74b6881e7c13ff913a9fd/main.go#L100-L117

there should be something wrong in the following lines cause we have a private repository running a PR build, but we cannot inject secret variables in the build environment section, also tried to add the checksum but didn't help.

I'm a bit confused about the code logic there..

**Comment by bradrydzewski** [comment]
private variables are not injected into the build section of the `.drone.yml` for security reasons. It is specifically this line of code preventing it from being injected:

```diff
case verified && payload.Build.Event == plugin.EventPull:
+  payload.Yaml, err = inject.InjectSafe(payload.Yaml, sec.Environment.Map())
```

the `InjectSafe` injects parameters into everything **but** the build section to prevent a secret variable from being leaked in a malicious pull request. I think we want this behavior by default, even for private repositories.

I think we could, however, add an optional parameter that gets encrypted with the `.drone.sec` file that instructs Drone to inject your secrets into the build section even if a pull request. Perhaps something like `unsafe: true` as seen below?

```
checksum: xxxx
unsafe: true
environment:
  - secret=foo
```

**Comment by rymir** [comment]
@bradrydzewski the way you are doing is correct, always good practice not to keep any secrets in the source code. On the other hand is also true that for some "trusted" private repositories, the freedom of being able to encrypt and store some secrets would be nice too and if you need some environment variables in the build phase that you want to use to build pull requests too.. makes sense to add this `unsafe: true` parameter. 
I think it really depends on the context and on the nature of the repository we are building:
1. private org and critical security: no secrets in source code at all
2. widespread open source project: maybe an encrypted secret that doesn't get injected on PRs 
3. my experimental private repo: `unsafe: true` and good luck :)

**Comment by bradrydzewski** [comment]
sounds good, this change was added to the 0.4 milestone so I'll get to it within the next day or two

**Comment by bradrydzewski** [comment]
@gtaylor gave me a link to kubernetes secrets and I think we can definitely learn from what they are doing. A kubernetes secret is a file that gets mounted as a volume into the container. http://kubernetes.io/v1.1/docs/user-guide/secrets.html

This approach is interesting because we could mount files directly into plugin containers and avoid the find / replace logic that we use today.

The kubernetes secret files also have extra metadata. We could use this sort of meta-data to limit which container (for example) mounts the secrets and when (pull requests, pushes, tags, etc). We could define additional rules that limit to specific authors ...

@gtaylor also suggested making the location of secrets pluggable. This would enable someone to store secrets on their own servers, instead of inside GitHub or inside the Drone database.

**Comment by jgreat** [comment]
It looks like you may be reworking this feature, but if there is interest here is a PR to allow secret injection into the build for Pull Requests if the Repo is Private and the .drone.yml checksum is good.

https://github.com/drone/drone-exec/pull/6

**Comment by jgreat** [comment]
I've thought about this a bit more, and please correct me if I'm wrong, but I believe there is no "safe" situation for injecting secrets into a PR.

Secrets are only secure from Read-Only users and then only if they are not allowed in PRs.

That's it, that's all the secrets are effective for. Any user with Write access could put malicious code into the build process to write out the secrets. So at best secrets are only obfuscated from Write users - Not Secure. If you allow secrets in a PR, a malicious Read-Only user could submit a PR to a repo with code to write out the secrets at build time. A checksum won't help since the malicious user doesn't need to modify the .drone.yml, just whatever the build process is running.

So if you really need secrets in your in your PRs, you might as well just put them in plain-text in your repo :(

**Comment by bradrydzewski** [comment]
> I've thought about this a bit more, and please correct me if I'm wrong, but I believe there is no "safe" situation for injecting secrets into a PR.

This is partially true. It is not safe to inject secrets into the _build_ section when the commit is a pull request. This is because the build section executes arbitrary code and a malicious pull request could expose secrets, as you mentioned.

It is safe, however, to inject secrets into plugins since plugins do not execute arbitrary code. This is why the checksum is important, because it prevents injecting secrets into plugins if the yaml has been tampered with.

> So if you really need secrets in your in your PRs, you might as well just put them in plain-text in your repo

This issue asks for the ability to inject secrets into the `build` section if the repository is private. I recommend only enabling this with `insecure: true` encrypted into the `.drone.sec` file. Some teams may still prefer to not keep secrets in their repository or commit history in plain text (in GitHub or Bitbucket) so I still see value in the requested enhancement.

**Comment by gtaylor** [comment]
> Some teams may still prefer to not keep secrets in their repository or commit history in plain text (in GitHub or Bitbucket) so I still see value in the requested enhancement.

Definitely agree. Un-encrypted secrets in git are something we really try to avoid, even if this only ends up being obfuscation.

**Comment by jgreat** [comment]
Yes, I should have been more specific. The only issue is secrets in the build that are imported into the container as environment variables. 

You may want secrets in the build that drone can access. An example might be docker private registry user and pass.

I was hoping to use secrets at build time for NPM tokens to access a private NPM repo. Realistically any user that has read access to the GitHub Repo is also going to have access to NPM repo. So they can be trusted with those credentials. Just something else to track and reset if a user leaves.

**Comment by ralfschimmel** [comment]
Would really like this.
