### ISSUE TITLE
Run as an unpriv user in docker image?

### ISSUE THREAD

**Issue by nullify005** [drone/drone#1283]
Hi There,

I'm having some issues trying to get builds to work with drone 0.4 with a container image which has `USER build` instead of being root as the default login

When my image defaults to non-priv then the build always fails just prior to executing the commands with:

`/bin/sh: 49: cannot create /etc/apt/apt.conf.d/90forceyes: Permission denied`

When it is root, then I don't get this issue however I then have flow on problems because things like bundler & bower etc. in ruby aren't all that happy running as root (nor do I really want them to)

I assume that the failure above is because of a script which is injected then run in my image & is assuming that it has root permissions prior to running the commands in the .drone.yml

How can I run the commands in the .drone.yml in the container as non root (without sudo -u <user> using a shell script?)

Is it assumed that the build process in the container has to be root?

I can't seem to find any clues in the doc or otherwise which help out

Regards, Lee

**Comment by nullify005** [comment]
Apologies, I found some references in gitter

**Comment by reesew** [comment]
I am trying to get drone to work, and getting the same error you mentioned. I'm not sure how you fixed it. What references did you find? What is the problem and solution?

**Comment by saidimu** [comment]
@reesew The issue is with images that set the `USER` [instruction](https://docs.docker.com/engine/reference/builder/#user) in `Dockerfile`. According to @bradrydzewski those images won't work anymore because drone expects the build container to run as root.

You can [override](https://docs.docker.com/engine/reference/run/#user) the `USER` instruction when running the container but I'm not sure how to do that in `.drone.yml`
