### ISSUE TITLE
Duplicate repos when searching

### ISSUE THREAD

**Issue by nodesocket** [drone/drone#1292]
Some repos show duplicates when searching. Is there a way to fix this, or flush the dups?

![screen shot 2015-10-30 at 2 52 16 pm](https://cloud.githubusercontent.com/assets/523312/10858922/d56ecf48-7f15-11e5-854e-8691d14674a4.png)

**Comment by foresmac** [comment]
Can confirm we're seeing this in 0.4.0.

**Comment by bradrydzewski** [comment]
GitHub changed the `GET /user/repos` endpoint to return all repositories. It previously omitted organization repositories, which is why you see Drone duplicating organization repositories in the list.

We need a fix that takes GitHub Enterprise into account which may not yet include this change, depending on which version is installed.

Note that this only impacts the view layer which fetches the list directly from GitHub. It does not impact the backend (ie we don't store two records of your repository in the database, trigger two builds, etc)

**Comment by bradrydzewski** [comment]
this was fixed in the drone:0.4.2 tag

**Comment by foresmac** [comment]
Thanks for the update. Before I open another issue, I wanted to ask if you know if 0.4.2 addresses another issue we have seen recently, where our org has a fork of another org's private repo, and it doesn't show up in our repo list in drone?

**Comment by bradrydzewski** [comment]
@foresmac drone uses the following api to return an unmodified list of repositories:
https://developer.github.com/v3/repos/#list-your-repositories

this endpoint is defined as the following:

> This includes repositories owned by the authenticated user, repositories where the authenticated user is a collaborator, and repositories that the authenticated user has access to through an organization membership.

Please verify the repository is returned by this endpoint (and subsequently not displayed in Drone) before opening an issue in Drone. If it is not returned by the endpoint an issue needs to be opened with GitHub support.
