### ISSUE TITLE
Show how long a build took in the web interface

### ISSUE THREAD

**Issue by nodesocket** [drone/drone#1298]
Once a build finishes, either success or failed, show how long it took in the web interface.

**Comment by gtaylor** [comment]
Related but not exactly the same thing. I figured I'd toss it in while we're touching the times. Currently you see two point of references:

* The relative time the commit was authoried (X minutes/hours ago)
* The relative time the build finished/failed/killed (X minutes/hours ago)

I can do the math in my head, but it'd be nice if when you hovered over this "X minutes ago" text you could see the absolute time for each ("started at 10:22").

**Comment by chuyskywalker** [comment]
(copying comment from #1469)

There's a great Jenkins plugin called [Timstamper](https://wiki.jenkins-ci.org/display/JENKINS/Timestamper) which provides per-line timestamps, but more novel is that the sidebar exists which lets you toggle between absolute and relative values. A very nice little feature.

**Comment by bitemyapp** [comment]
Timestamper looks really nice, that would be awesome so we could know how much each part of the build is contributing to our build times.

**Comment by bradrydzewski** [comment]
closing in preparation for 0.5 since we display the build duration in the user interface now, and I have a patch that also adds elapsed time for each line in the output.

<img width="1324" alt="screen shot 2016-06-08 at 3 14 11 pm" src="https://cloud.githubusercontent.com/assets/817538/16749996/3502850e-4783-11e6-8810-fe4e820d92d5.png">

<img width="925" alt="screen shot 2016-07-11 at 11 17 07 am" src="https://cloud.githubusercontent.com/assets/817538/16749999/3a20bc4a-4783-11e6-9b7c-6837bdfd589a.png">
