### ISSUE TITLE
Drone Docker logs

### ISSUE THREAD

**Issue by prashantchitta** [drone/drone#1301]
I am running drone on Docker on Ubuntu. Here is my docker file
```
# Pull from base Ubuntu image
FROM ubuntu

# Do system updates and install dependencies
RUN apt-get update
RUN apt-get -y upgrade
RUN sudo apt-get -y install git wget
RUN apt-get clean

# Download Drone.io
RUN wget http://downloads.drone.io/master/drone.deb
RUN dpkg -i drone.deb

# Expose the Drone.io port
EXPOSE 8080

ENV DRONE_SERVER_PORT 0.0.0.0:8080
ENV DRONE_DATABASE_DATASOURCE /var/lib/drone/drone.sqlite

# The command we'll be running when the container starts
CMD /usr/local/bin/droned
```

Could anyone tell where to find all the logs? I tried to locate in ubuntu, but could not find any.

**Comment by bradrydzewski** [comment]
@prashantchitta we provide an official Docker image: 
https://hub.docker.com/r/drone/drone/

Also the above Dockerfile is invalid because `droned` doesn't exist. Feel free to use our Gitter room for questions (at https://gitter.im/drone/drone) and reserve the issue tracker for issues. There are plenty of people in the chat that will be happy to help you. Thanks!
