### ISSUE TITLE
Drone fails if MySQL database isn't latin1, but doesn't set it

### ISSUE THREAD

**Issue by aaron42net** [drone/drone#1323]
My MySQL database is configured to create new databases as utf8, which means I ended up with:

CREATE DATABASE `drone` /*!40100 DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci */

Trying to run drone results in:

INFO[0000] using database driver mysql                  
INFO[0000] using database config drone:password@tcp(db.hostname:3306)/drone?parseTime=true
ERRO[0000] Error 1071: Specified key was too long; max key length is 767 bytes 
FATA[0000] migration failed

When in utf8 mode, each character takes three bytes, so drone's use of VARCHAR(500) would need a 1500 byte index, which beyond InnoDB's 767 byte limit.

After switching the database character set to latin1, this problem went away:

ALTER DATABASE drone CHARACTER SET = latin1 COLLATE = latin1_general_ci;

If you don't need VARCHAR(500), using VARCHAR(255) instead would avoid this problem, as would specifying a character set and collation on the CREATE TABLEs.

**Comment by bradrydzewski** [comment]
thanks for the detailed issue!

> If you don't need VARCHAR(500), using VARCHAR(255) instead would avoid this problem

the full GitHub repository slug can actually be 511 characters, so we probably can't reduce the value.

> as would specifying a character set and collation on the CREATE TABLEs

Setting the default character set is definitely something I'm open to ...

```
CREATE TABLE repos (

) DEFAULT CHARACTER SET latin1 COLLATE latin1_general_ci;
```

I'm a bit hesitant to force every table to latin1 since commit messages (stored in the `builds` table) may be in other languages (chinese, etc) and I'm guessing that might cause issues. Is there an issue with forcing just the repository table to latin1? This isn't an area I'm very familiar with, so I'm definitely open to community suggestions here.

**Comment by gtaylor** [comment]
I just recently got finished with hassling over a latin1 -> utf8 conversion on an old MariaDB. I'd hate to see us go latin1 just for key length when utf8 is such a safe default assumption for many.

Perhaps there's a solution where we could truncate with a hash at the end. I'm going to BS this, but here's the basic gist:

```
some-org/some-relaly-long-repo-name-that-is-far-beyond-the-limit
```

Lop this off at some pre-determined length:

```
some-org/some-relaly-long-
```

Now add a hash to the end that is also of a pre-determined length. The input should be the full, un-truncated version:

```
some-org/some-relaly-long-a92lkjfu09dlk
```

This does lead to a less browseable DB and potentially more work in debugging, but assuming latin1 would open us to a world of hurt in the future. Perhaps there are other, more graceful approaches than mine. Surely there is plenty of other software that has had to work around this limitation somehow.

**Comment by bradrydzewski** [comment]
@gtaylor agreed, UTF8 is a much better option. Here are my thoughts ...

For mysql we could alter the `repo.owner`, `repo.name` and `repo.full_name` fields so that `repo_full` name is 255 characters. There are very few repositories that are going to have a full_name greater than 255 characters. In fact, the longest full_name in the [drone.io](https://drone.io) hosted service's database is only 55 characters, from a sample of 30,000 repositories.

For teams that need more than 255 characters (if they exist) we can provide the necessary sql statements to alter the table to LATIN1 and alter the column size. Or we can encourage them to use sqlite or postgres instead. But as long as it is documentation I don't think it will be an issue.

**Comment by bradrydzewski** [comment]
merged https://github.com/drone/drone/pull/1375 to drop the `repos.repo_full_name` and `users.user_login` down to 255 characters which based on local testing has fixed the issue
