### ISSUE TITLE
Support windows/amd64

### ISSUE THREAD

**Issue by GabrielTK** [drone/drone#1330]
Hi!
Windows Server 2016 Technical Preview was released with a new feature: the ability to run Windows Containers inside Docker!! But I haven't seen any CI using it to provide .NET Support. So, I think it is a good idea to implement it. If you need help, please contact me (enricorocha1@hotmail.com)

Thank you,
Gabriel

**Comment by bradrydzewski** [comment]
@GeARCraft1 agree this is a must-have feature

**First** we need to alter the `drone-exec` project and isolate code that is specific to the operating system. We can then use build tags (ie `// +build linux` or `// +build windows`) to choose which code to include at compile time.

For the most part `drone-exec` should have very little code specific to the operating system, but this is an example of something that probably won't work with windows: 
https://github.com/drone/drone-exec/blob/5a4d65ba294707749861567fd7251680b041fa04/main.go#L186

**Second** since Drone uses plugins for everything (even `git clone`) we need to ensure those plugins are available for windows. Plugins are distributed as Docker containers so we'll need to build and distribute plugins for both architectures.

Plugins are more likely to have code specific to the operating system so we'll need to go through each plugin one-by-one and make sure they are built with portability in mind. This is probably a fairly large effort, so we can prioritize based on popularity in DockerHub:
http://index.docker.io/_/plugins

**Third** we need an improved Queue that is able to dispatch builds based on architecture. I don't have an open issue specifically for this, but it is discussed in https://github.com/drone/drone/issues/1254 

This step is not required, but it is important if we want a mixed environment for both Linux and Windows builds.

**Comment by GeARCraft1** [comment]
Hmm, that's interesting. Maybe Cygwin or powershell, .Net or something like this can help. I m going to google it now.

**Comment by bradrydzewski** [comment]
In terms of planning, I recommend we start by ensuring the following plugins can run on Windows:

* https://github.com/drone-plugins/drone-git
* https://github.com/drone-plugins/drone-cache

These two plugins are the only **required** plugins when running a build. All others are optional. We'll need to make sure these can compile and run on Windows, and we will need a Windows-specific Dockerfile.

Note that these plugins can be tested individually, without having to run Drone itself.  Once these plugins are working, we can try to run [drone-exec](https://github.com/drone/drone-exec) on windows and making any necessary adjustments.

**Comment by GeARCraft1** [comment]
Maybe something related to WinSocks

**Comment by bradrydzewski** [comment]
> Hmm, that's interesting. Maybe Cygwin or powershell, .Net or something like this can help. I m going to google it now.

for the `drone-git` and `drone-cache` plugins a container with Cygwin could absolutely work without requiring any code changes.

**Comment by GeARCraft1** [comment]
Wow, this is very good. Sorry, my app didn't refreshed automatically so some comments are out of order. Well, I'm having some crazy ideas, as using vagrant to run plugins, as maybe this could work. What do you think?

**Comment by GeARCraft1** [comment]
Also, if you need help, add me to your github team so I can help you to r

**Comment by GeARCraft1** [comment]
Sorry, my keyboard crashed. As I was saying, I can help you to rewrite the parts that aren't compatible.

**Comment by bradrydzewski** [comment]
@GeARCraft1 I don't have a windows environment readily available, and I'm working on some other issues at the moment, but if you're willing to help it would be very much appreciated, and would help accelerate this capability.

I think, with something like Cygwin, we could probably use the `git` plugin as-is with no changes. You can test this by compiling the git plugin and running it manually on a windows machine (no Docker required). See https://github.com/drone-plugins/drone-git#usage

If that works we just need the ability to create an image for the `git` plugin. This might be as simple as the following `Dockerfile.win64`:

```
FROM windowsservercore
RUN Install-Package cygwin
ENTRYPOINT ["/path/to/cygwin", "drone-git"]
```

* NOTE the above example file is just pseudo code, not sure exactly what it would look like

**Comment by bradrydzewski** [comment]
it is also worth mentioning that in the short term we'll need to need to use a different name or tag for windows images (ie `drone-git:windows`) but this will be temporary as the Docker team is planning to handle OS and Architecture automatically: https://github.com/docker/distribution/pull/1068

**Comment by GeARCraft1** [comment]
If you want I can create a basic windows testing environment.

**Comment by Dids** [comment]
Any news on this?

**Comment by bradrydzewski** [comment]
@Dids supporting windows containers would be awesome, however, none of the core Drone maintainers are working on this. I'm not aware of any maintainers planning to work on this in the near term. The issue has been labeled _help wanted_ according.

If and when there are updates to provide we will be sure to comment on this issue and update the status accordingly. Until then it should be assumed we are still looking for volunteers for this issue.

**Comment by Dids** [comment]
Yeah, I commented too early. Did some research and even tried to create my own image, but it turns out there are still a few issues with the latest version of Docker and Windows Server Core/Nano.
Once they fix those, it should be possible to make progress.

**Comment by mingwandroid** [comment]
Hi @Dids, would you have any more details about those issues?

**Comment by Dids** [comment]
@mingwandroid At the time of trying it out, there were issues downloading the Server Core/Nano images, as they would only download properly on older versions of Docker. Not sure if that's fixed yet.

On another note, this whole "bash on Windows" might actually help make Drone on Windows a real thing: https://msdn.microsoft.com/commandline/wsl/install_guide

From what I could gather, it's Windows 10 only, but even then, it sounds doable.

**Comment by mloskot** [comment]
AFAIK, there is no way to run Visual Studio toolchain (cl.exe, link.exe, etc.) from the "Ubuntu on Windows"

> note that Bash and Linux tools cannot interact with Windows applications and tools, and vice-versa

Read more at https://blogs.windows.com/buildingapps/2016/03/30/run-bash-on-ubuntu-on-windows/#CCdEB2mCGLJEpeZE.99

**Comment by mingwandroid** [comment]
I don't see why you wouldn't use MSYS2 anyway. I'm biased though.

**Comment by bradrydzewski** [comment]
this comment will discuss a strategy for an official windows image for drone.

---

I wanted to provide a quick not for what it will require to port drone 0.5 to windows and to other platforms. This assumes we are running the server on amd64 linux and the build agents on windows machines. Porting the server to windows is outside the scope of this post.

### windows binary

The first thing we will need is a version of the drone agent that can run on windows. The good news is that we already compile a binary that is compatible with windows. The generated binary can be used to start the agent, using `drone agent` command, to start the agent on a windows server:

* https://github.com/drone/drone/blob/master/Makefile#L53
* http://downloads.drone.io/release/windows/amd64/drone.tar.gz

### agent modifications, ambassador

the first problem we'll encounter is that drone attempts to spin up what is called an ambassador container (google it) for each build to provide a shared network and volumes. This ambassador container uses the `busybox` image which will not run on windows.

So the first change we'll need to make is the ability to use windows images depending on the architecture. This change will need to be made here:
https://github.com/drone/drone/blob/master/yaml/transform/pod.go#L26:L51

### agent modifications, build script

the next problem we'll encounter is that drone transforms the build stages in your `.drone.yml` to shell scripts that get passed to the build container and executed. This needs to be transformed to work with windows powershell scripts.

this change will need to be made to this file:
https://github.com/drone/drone/blob/master/yaml/transform/command.go

### porting plugins

the next problem that we'll encounter is that all the plugins are compiled for linux/amd64. Since drone uses plugins for everything (git clone, etc) this means all plugins need to be ported to windows

the good news is that we can specify and even override default plugins in the yaml. So we can instruct drone to use a custom git plugin compiled for windows:

```
pipeline:
  clone:
    image: bradrydzewski/git:windows
```

### official windows support

In order to officially support windows we'll need to make the (relatively simple) agent change described above and we'll need to start building and publishing windows versions of our drone agent and drone plugin images. Many of the drone repositories have a `Dockerfile.win` file in preparation. We do not currently have the infrastructure available to build windows versions of Drone and Drone plugins.

**Comment by gigi81** [comment]
I was investigating build drone on windows. the main problem is to have the proper pre-requisites installed.
I can create an appveyor build to generate the windows binaries, as a bootstrap.
after a first stable release of drone for windows, it can be replaced with a proper drone agent on windows build. would you be happy to merge such a PR?

**Comment by bradrydzewski** [comment]
@gigi81 thanks for the note, some thoughts below

> I can create an appveyor build to generate the windows binaries

we have a windows build of the drone binary available for download here:
http://downloads.drone.io/release/windows/amd64/drone.tar.gz

you can use this binary to run `drone agent` to start an agent on a windows machine. The agent can be configured with environment variables, same as the docker image.

> after a first stable release of drone for windows

the problem is that even though the agent runs on windows, it will not run windows builds. The following changes are required before we'll be able to run a windows build with drone:

1. agent ambassador modifications (see prior [comment](https://github.com/drone/drone/issues/1330#issuecomment-250843934))
2. agent build script modifications (see prior [comment](https://github.com/drone/drone/issues/1330#issuecomment-250843934))
3. update git plugin for windows

**Comment by Steiniche** [comment]
@bradrydzewski can you say if drone.io is going to support windows builds within a reasonable time?
I can see that it have been moved out of 0.6 and Unplanned.

**Comment by bradrydzewski** [comment]
Some updated notes on what is required to enable windows builds. There are 3 relatively minor tasks that need completed:

**1.** Set default git plugin for windows
https://github.com/cncd/pipeline/blob/b7427ae1fb86bb04e2997e5f3a1eec75c4b056ef/pipeline/frontend/yaml/compiler/compiler.go#L99:L103

**2.** Use the correct entrypoint and command for windows
https://github.com/cncd/pipeline/blob/b7427ae1fb86bb04e2997e5f3a1eec75c4b056ef/pipeline/frontend/yaml/compiler/convert.go#L79:L83

**3.** We use the commands section to generate a bash script, using the generateScriptPosix method. For windows we have a stub method called `generateScriptWindows` which should do the same thing, but in windows format
https://github.com/cncd/pipeline/blob/b7427ae1fb86bb04e2997e5f3a1eec75c4b056ef/pipeline/frontend/yaml/compiler/script_win.go

Once complete, we need a `Dockerfile.agent.windows.amd64` dockerfile added to the core repository that can build and publish windows agents.

We also need the git plugin ported to windows. I believe @tboerger is working on porting this and other plugins.

**Comment by Steiniche** [comment]
Hi @bradrydzewski can you give an update about the progress?
Furthermore, I have considered starting contributing to get this done however I believe the learning curve to be a little steep in the first couple of pull requests.
How is entry easiest in your opinion?

**Comment by tboerger** [comment]
The easiest part will be providing dockerfiles for all the plugins. I will try to take the time to provide some guide on Discourse what needs to be done for the plugins.

**Comment by jvican** [comment]
I manage the CIs for the Scala Platform, an official collection of Scala libraries that is meant to be shipped with the language. Cross-compilation in different platforms for these modules is important to ensure they are battle-tested.
  
I just want to say that if you get Drone to work on windows/amd docker images, this is going to be a game-changer. I've been about to use Jenkins just because I can cross-build my projects in every platform. I've finally stick to Drone because of the hope this future gets done some time soon.

**Comment by bradrydzewski** [comment]
__looking for volunteers__

I am going to lock this issue so that this is the last comment everyone sees. We are very close to having windows support. @tboerger has ported almost every every plugin to windows. We need volunteers with windows experience for the following:

* I think @tboerger has ported the windows plugin, but it just needs to be uploaded to dockerhub. Is this correct? If so, we then just need to add __2 loc__ to [this block](https://github.com/cncd/pipeline/blob/b7427ae1fb86bb04e2997e5f3a1eec75c4b056ef/pipeline/frontend/yaml/compiler/compiler.go#L99:L103) to specify the windows image.

* we need someone to update the __2 loc__ in [this block](https://github.com/cncd/pipeline/blob/b7427ae1fb86bb04e2997e5f3a1eec75c4b056ef/pipeline/frontend/yaml/compiler/convert.go#L79:L82) with the correct entrypoint and command to the build script which is passed to the pipeline image as a container 

* we need someone to create the windows-equivalent build script generator in this existing method stub that we have [here](https://github.com/cncd/pipeline/blob/b7427ae1fb86bb04e2997e5f3a1eec75c4b056ef/pipeline/frontend/yaml/compiler/script_win.go). It should resemble the posix script generator [here](https://github.com/cncd/pipeline/blob/b7427ae1fb86bb04e2997e5f3a1eec75c4b056ef/pipeline/frontend/yaml/compiler/script_posix.go). This is approximately __60 loc__

So we are approximately __64 loc__ away from supporting windows, but we just need people with windows container experience to submit the relevant patches. I have created a thread in discourse for volunteers to discuss building / testing windows support. So if you would like to volunteer please go here https://discourse.drone.io/t/windows-support-volunteers-wanted/2018

**Comment by bradrydzewski** [comment]
official windows support added in latest release https://readme.drone.io/install/agents/windows-1803/
