### ISSUE TITLE
Multiple remote drivers, i.e. Github and Gogs enabled

### ISSUE THREAD

**Issue by kageurufu** [drone/drone#1336]
I was able to configure multiple remotes in a prior version, and with the new configuration model. 

After looking in https://github.com/drone/drone/blob/d3767302266fe6ef73aa89bc9466f15daf13cbb1/remote/remote.go#L19, it seems this functionality has been removed.

Is this on the roadmap for the future?

**Comment by bradrydzewski** [comment]
The decision was made to remove multiple remotes and there are no plans to re-introduce. With each release Drone integrates more deeply with systems like GitHub (Gogs, etc). The more deeply we integrate with these systems the more difficult it became to support multiple remotes.

The multiple remote implementation in the prior version wasn't very good. You had to logout and login with a different account to switch between GitHub and Bitbucket (for example). The complexity caused by multiple remotes just didn't seem to justify our half-baked implementation.

Luckily Drone has a pretty lightweight runtime (< 20MB RAM) so the recommended approach is to run two drone instances on the same server with subdomains (ie `drone.myompany.com` and `drone.gogs.mycompany.com`)

**Comment by kageurufu** [comment]
Makes sense to me, albeit being slightly dissapointing :)

I'll just get another instance up then.

Thanks!

**Comment by axel22** [comment]
For what it's worth, +1 for allowing the same drone instance to connect to multiple hosting services.
Bitbucket has free private repos, but GitHub is nicer to use, so I can imagine many people splitting their repos across the two providers.

**Comment by davidak** [comment]
We also use Gitlab in the company.
This feature should get implemented some time in the future.

**Comment by tboerger** [comment]
I don't think that it's worth it to add all the overhead for multiple remotes. It's quite easy to start an instance per remote. The only thing that needs to be implemented is the behavior to get drone running in a subfolder instead of requireing a subdomain for each instance.

**Comment by bradrydzewski** [comment]
please see https://github.com/drone/drone/issues/1336#issuecomment-158459430 which describes why multiple remotes were removed in 0.4, and the suggested workaround. There are no plans to re-add multiple remotes in a future release.
