### ISSUE TITLE
Support Vagrant for non-Docker Builds

### ISSUE THREAD

**Issue by supermarin** [drone/drone#135]
Hi! Thanks for open sourcing this, it's a great thing.

I'm opening this issue to discuss a potential decoupling from Docker.
It's noticeable that Drone was built for cloud services, allowing clients to run under a specific container (e.g. just Ruby2.0).

What world needs is a good Jenkins replacement. It's something people would install with 1 click on any platform (I'm looking at you OSX), and **be able to run the job on a host machine**.
Something people would update with just `go get` or `git pull` and `go install`.

It's a big set of users, as currently there's no sane self-hosted CI for building iOS apps.

**Comment by supermarin** [comment]
@bradrydzewski is there a branch pushed with that work?

**Comment by bradrydzewski** [comment]
@supermarin the plan has slightly shifted since Windows announced they will officially support Docker. We now need a simple solution for OSX. My plan is to create a simple server daemon that implements the Docker protocol (simple REST API) that translates those commands into something that works on OSX. It will probably be a simple chroot, but can get more sophisticated over time.

This project doesn't exist yet, but I'm happy to help kick it off.

**Comment by supermarin** [comment]
@bradrydzewski would that still support vagrant and OSX virtualization?

The plans have slightly changed on our side too, and if it helps, one of the goals is to spawn a new VM for each build (and kill it afterwards).

**Comment by denji** [comment]
[Free] VirtualBox - build-in, [Parallels Desktop - Vagrant (only license product, better performance)](http://parallels.github.io/vagrant-parallels/)
[Paid] [VMware](http://www.vagrantup.com/vmware)

**Comment by supermarin** [comment]
@denji thank you for your response, but i'm not sure this answers the question

**Comment by bradrydzewski** [comment]
@supermarin yes and no.

If you need a Windows or Linux build environment you will be able to use Docker. This will let you spawn a new virtual environment for every build and kill it after.

If you need an OSX or IOS build environment we will need to provide a workaround. This workaround will need to **look** like Docker. Drone will think it is talking to Docker. Under the covers it will need to translate the instructions coming from Drone into something that OSX understands. I'm not sure what this will look like yet ...

**Comment by supermarin** [comment]
@bradrydzewski I'm pretty sure you need a full virtualization.
It's legal to virtualize OSX software on Apple's hardware.

**Comment by bradrydzewski** [comment]
@supermarin upcoming 0.4 supports build agents. The build agent polls Drone for builds, executes and then sends the results back to the Drone server.

This means someone can write an agent for non-Docker platforms, such as OSX, with or without using virtualization: https://github.com/drone/drone/tree/0.4.0/cmd/drone-agent

The only challenge here is that Drone heavily uses Docker for things like plugins (ie deploy to Heroku, publish to S3). This means that an IOS agent would function, but may have limited functionality compared to Docker-based agents.

But it is a start ...

**Comment by denji** [comment]
lightweight OS X virtualization https://github.com/mist64/xhyve

**Comment by marceldegraaf** [comment]
Hi @bradrydzewski, we're currently looking into using Drone behind our firewall. We're looking for a system that can run iOS builds on a dedicated Mac Mini that's sitting in our office.

The link to `drone-agent` you posted above is no longer working. Did build agents make it into the 0.4 release? We'd be happy to contribute a build agent that works on OS/X, but I'm not sure if that's still possible?

**Comment by bradrydzewski** [comment]
@marceldegraaf agents were pull from the 0.4 release since they need quite a bit more work. In the short term, have you considered running all your builds on linux machines, and for your IOS builds, you could ssh into the Mac Mini?

So your .drone.yml might look something like this:

```
build:
  image: unbuntu
  commands:
    - |
      ssh user@1.2.3.4 <<EOF
        cd /some/place/on/mini
        git fetch origin
        git merge origin master
        ./test.sh
      EOF
```

I know it isn't ideal, but it at least gives you a temporary solution until w have something permanent figured out.

**Comment by marceldegraaf** [comment]
Hm, that's not a bad idea actually. Thanks!

**Comment by joelchen** [comment]
Has anyone looked into https://github.com/jkingyens/docker4xcode?

**Comment by shaxbee** [comment]
It seems that native Mac OS and Windows Docker is in Beta: https://blog.docker.com/2016/03/docker-for-mac-windows-beta/

**Comment by supermarin** [comment]
Well this won't work either, as the builds won't get executed on OSX.

> The Docker engine is running in an Alpine Linux distribution on top of an xhyve Virtual Machine on Mac OS X or on a Hyper-V VM on Windows, and that VM is managed by the Docker application.

**Comment by nathany** [comment]
Support for other operating systems would be very helpful in certain circumstances. I'm currently looking at options to test the `fsnotify` Go library on multiple platforms and architectures: https://github.com/fsnotify/fsnotify/issues/136.

**Comment by bradrydzewski** [comment]
@nathany Drone is capable of running builds on different operating systems and architectures. There have been efforts, for example, to port Drone and all of the plugins to arm:
https://discuss.drone.io/t/drone-ported-to-arm/55

Docker is actively being ported to Windows and FreeBSD which means Drone should be able to run builds natively on Windows and FreeBSD as well. Below I'll provide some more context on what it would take to port Drone to these other architectures. This can serve as a roadmap for anyone that wants to accelerate these efforts.

### FreeBSD

Drone should run on FreeBSD with little or no modification. We would just need to build all of our plugins for FreeBSD and publish to the Docker registry (similar to what was done for arm)

### Windows

Drone converts build commands in the yaml file into a shell script. In order to support Windows we will need to convert these to powershell commands. We would also need to compile all of our plugins for windows and publish to the Docker registry.

Generating a powershell compliant script should not be too difficult. It should be a relatively simple change to our [shell script transform function](https://github.com/drone/drone/blob/master/engine/compiler/builtin/shell.go).

### Multi Architecture

As I mentioned drone is capable of running linux __or__ arm builds, but is not capable of running linux __and__ arm builds using the same installation. This is because right now all builds are placed on the same queue and pushed to the same pool of workers.

In order to support multiple architectures or platforms in a single installation we would need to have multiple queues (one per platform). This should be a relatively simple change to the [queue package](
https://github.com/drone/drone/blob/master/queue/queue.go)

```diff
-Publish(Work) error
-Pull() Work
+Publish(platform string, work Work) error
+Pull(platform string) Work
```

### Docker Registry Changes

Today when you run `docker pull redis` on linux it pulls the Docker image for linux. If you run `docker pull redis` on windows it pulls the Docker image for linux. This makes it difficult to use the same yaml across multiple platforms because Docker image names are currently unique to a single platform.

Luckily this is something the Docker team is working to improve:
https://github.com/docker/docker/issues/15866

**Comment by ysangkok** [comment]
FYI, compiling on FreeBSD currently, i have the following problem:

```
[janus@xn--kn-1ia ~/gopath/src/github.com/drone/drone] gmake build
cd drone && go build --ldflags '-extldflags "-static" -X github.com/drone/drone/version.VersionDev=' -o drone
# github.com/drone/drone/static
../static/static.go:15: undefined: Asset
../static/static.go:15: undefined: AssetDir
# github.com/drone/drone/template
../template/template.go:35: undefined: AssetDir
../template/template.go:45: undefined: MustAsset
# github.com/drone/drone/vendor/github.com/mattn/go-sqlite3
cc: warning: argument unused during compilation: '-pthread'
# github.com/drone/drone/store/datastore
../store/datastore/store.go:100: undefined: ddl.Asset
../store/datastore/store.go:101: undefined: ddl.AssetDir
Makefile:30: recipe for target 'build_static' failed
gmake: *** [build_static] Error 2
```

**Comment by bradrydzewski** [comment]
@ysangkok did you run `make deps` and `make gen` to generate the static assets? The compile errors seem to indicate these are missing and have not been generated. Second seems to be just a warning with sqlite3 but not sure that is an issue. Let's move the compiling discussion to our gitter room at https://gitter.im/drone/drone and I can help you in real time!

**Comment by bradrydzewski** [comment]
I also want to point mention that we are working on porting the git plugin to arm and have a docker image available. Would be great to have the same for freebsd and windows if there are any takers :)
https://github.com/drone-plugins/drone-git/blob/release/0.5-alt/Dockerfile.armhf

**Comment by XVilka** [comment]
Good day! Are there any plans for this yet? To be able to work without docker? This issue seems unupdated for a while.

**Comment by bradrydzewski** [comment]
Since this was opened (about 3 years ago) the project has deeply integrated with container runtimes. Unwinding this is not trivial. So at this time there are no plans to execute builds outside of container environments, so it is probably best to close the issue.

If the scope of the project changes we can always reconsider and re-open this issue.

**Comment by Adnn** [comment]
My 2 cents on a closed issue:
The original proposal of this discussion (integrating with Vagrant in addition to Docker) is much preferable than simply supporting host builds. Vagrant can be used to virtualize Windows and OSX (and others), and some people are building native apps targeting all of those.
[And to agree with one of the first points: the world is in need for a better Jenkins, i.e. an automation system that does not assume your target environment(s). Not saying you want to be this guy, but just in case :) ]

**Comment by v7lin** [comment]
关注drone一年多了，依然未解决osx编译问题，真是让人失望啊。

--- translate ---

It is disappointing to notice that drone is still more than a year old and still fails to solve the OSX compiler problem.

**Comment by tboerger** [comment]
The upcoming release will be prepared for other build environments, but the usage of plugins is still not resolved that way.

**Comment by bradrydzewski** [comment]
Drone supports different runtime execution environments, including support for native execution directly on the host. This includes support for Linux, Windows, macOS, BSD and more. See https://twitter.com/droneio/status/1168931431546052608
