### ISSUE TITLE
Store GitHub pull request base branch

### ISSUE THREAD

**Issue by divercraig** [drone/drone#1367]
Add a new setting to the Repo Config page which allows users to provide a list of branches which should trigger a build on push.

By default an empty list should mean build on a push to any branch, but if the user providers a list of branches e.g. "master, dev" then builds should only be triggered when a push occurs to those branches.

This would allow developers to make multiple commits to development branches without triggering a build. Then a build would be triggered when the developer creates a pull request (if the repo was configured to run builds for pull requests). When the merge request was accepted it would be a push to master, which would trigger a build.

**Comment by bradrydzewski** [comment]
@divercraig in the `.drone.yml` file you can configure a white-list list of branches that should be built. Any branch not in this list will be ignored. Hope that helps!

```
branches:
  - master
  - develop
```

**Comment by divercraig** [comment]
@bradrydzewski this suggestion has the problem that it also prevents pull requests from being built.

Can we please re-open the issue?

**Comment by bradrydzewski** [comment]
In this case, I think the fix is to use the `base` branch name instead of the `head` branch name for pull requests when evaluating the `branches` block in the yaml [1]

[1] https://developer.github.com/v3/activity/events/types/#webhook-payload-example-13

**Comment by divercraig** [comment]
@bradrydzewski one issue with using the base branch instead of HEAD for merge requests is that this will mean evaluations like
```
when:
    branch: master
```
will be true for merge requests. How do you prevent steps like publish or deploy occurring for merge requests?

**Comment by bradrydzewski** [comment]
@divercraig publish and deploy steps are always skipped for pull requests. We also support filtering based on build event type (hook, pull request, tag, deploy) that can be used to filter out pull requests:

```
when:
  event: pull_request
```

**Comment by tvooo** [comment]
+1 that would be very useful

**Comment by ChiperSoft** [comment]
We're also running into this problem. Every push to a feature branch triggers a build both for the branch and again for the PR. Like @divercraig I tried using the `branches` whitelist and it prevented PRs from building entirely.

**Comment by bradrydzewski** [comment]
adding a quick note here since this came up recently in Gitter. Right now we are storing the source branch in the database for pull requests, which as far as I can tell, is only for UI / display purposes.

we should therefore be able to switch from the source branch to the target branch in the database. We will still need to visually display the source branch in the UI. We have an existing, unused field, called `refspec` which is generally formatted like `refs/heads/master:refs/remotes/origin/master`, which we should be able to use to store the source branch, which can be parsed out in the UI and rendered on the screen.

Hopefully that all makes sense. Let's plan this for 0.5.1+ or 0.6

**Comment by bradrydzewski** [comment]
#1866 fixes this issue by storing the target branch for pull request, instead of the source.

**Comment by therynamo** [comment]
I noticed in the documentation:

>Deployments are triggered at the end of a successful build. Note that deployment steps are not executed for pull requests or failed builds.

I'm wondering if this has to be the case. I'd like to publish pull request builds to our private registry under their own repo. This is because I want to be able to run the code in a production like environment prior to merging.

I could see being able to filter by `pull_request` and then creating a separate publish step for that trigger. However, it seems that isn't possible.

Can I accomplish a publish on PR? Or is that not supported by Drone?
