### ISSUE TITLE
Bitbucket Status API changed, updates required

### ISSUE THREAD

**Issue by mcoms** [drone/drone#1380]
Hey, ~~after switching from HTTP to HTTPS,~~ I can no longer activate any Bitbucket repositories.

The UI gives the error
> Unable to activate this repository. You must have administrative access to this repository. Also, please check the third-party application access policy to ensure Drone is approved. Bad request

And in debug mode:
```
[GIN] 2015/12/18 - 16:41:23 | 404 |  363.193332ms | 194.247.xxx.xxx |   GET     /repos/mcoms/xxx
time="2015-12-18T16:41:32Z" level=error msg="unable to create hook https://drone.xxx.com/hook?access_token=eyJhbGciOxJIUzIxNiIsInR5xCI6IkpXxCJ9.exJ0ZXh0IxoibWNvbXMxZmF0LWJhx3RhcmQxLCJ0eXBlxjoiaG9vaxJ9.4NGK3YXxP3k7B18bwxwnWqeiLeB9xdPgXDKODxQN_Kk. Bad request" 
[GIN] 2015/12/18 - 16:41:32 | 500 |  2.316416239s | 194.247.xxx.xxx |   POST    /api/repos/mcoms/xxx
```

If I manually add the Webhook via the Bitbucket site, it accepts the URL as valid, but activating the repository in Drone clears out the manually entered webhooks and errors as above.

Existing repositories and logging in all seem to work fine.

**Comment by bradrydzewski** [comment]
@gtaylor recently merged https://github.com/drone/drone/pull/1351 to fix this issue. You'll need to upgrade to the latest version of Drone.

If you want to read more about the issue and the underlying root cause please see https://github.com/drone/drone/issues/1280 and https://github.com/drone/drone/issues/761

**Comment by mcoms** [comment]
Hi @bradrydzewski — I think this may be a different issue; I used `mitmproxy` to see requests from `drone:latest` to bitbucket and discovered the response from Bitbucket was as follows:

```
2015-12-18 19:33:58 POST https://api.bitbucket.org/2.0/repositories/mcoms/xxx/hooks                                                                                                                                 
{
    "active": true, 
    "description": "drone.xxx.com", 
    "events": [
        "repo:push"
    ], 
    "url": "https://drone.xxx.com/hook?access_token=eyJhbGcixiJIUzI1NixsInR5cCI6IxpXVCJ9.eyJ0ZXx0IjoibWNvbXMxZmF0LWJhcxRhcmQiLCJ0exBlIjoxaG9vayJ9.xFuPgAUPKdVmftxB-wenpW0lcxBAfB5c59c0QpxQuIk"
}
```


```
2015-12-18 19:33:58 POST https://api.bitbucket.org/2.0/repositories/mcoms/xxx/hooks
{
    "error": {
        "fields": {
            "skip_cert_verification": [
                "This field may not be null."
            ]
        }, 
        "message": "Bad request"
    }
}
```

Perhaps it's bad timing on my part, but it looks like the Bitbucket API now requires `skip_cert_verification` to be sent as a boolean, and it's not being provided in the request to create the hook?

**Comment by bradrydzewski** [comment]
@mcoms thanks for providing more details, very helpful. I'm not sure what the expected payload should look like since the field is not included in their documentation:
https://confluence.atlassian.com/bitbucket/webhooks-resource-735642279.html#webhooksResource-POSTawebhook

This may be a simple matter of adding the field to the following:
https://github.com/drone/drone/blob/master/remote/bitbucket/types.go#L46

This isn't something I'm going to be able to look at until after the new year due to holiday travel, but if you are willing to test it out and submit a PR I'm happy to merge.

cc @gtaylor who has may also be interested in this issue

**Comment by mcoms** [comment]
Thanks, definitely looks like a regression in their API, there's a similar ticket on another project: https://github.com/Shippable/support/issues/2144.

Going by [what this does on the web interface](https://confluence.atlassian.com/bitbucket/manage-webhooks-735643732.html), it looks like a boolean, with `false` being the sane default.

I'm not sure my zero-Go experience is quite up to making the fix, but appreciate the pointer and I'll certainly have a try. Enjoy your travels!

**Comment by bradrydzewski** [comment]
Might be as simple as the following, since Go boolean primitives default to `false`. I'm just not setup to push code from this laptop otherwise I'd submit a patch

```diff
type Hook struct {
	Uuid   string   `json:"uuid,omitempty"`
	Desc   string   `json:"description"`
	Url    string   `json:"url"`
	Events []string `json:"events"`
	Active bool     `json:"active"`
+	SkipVerify bool `json:"skip_cert_verification"`
}
```

**Comment by mcoms** [comment]
:+1: I reported this as a regression to Bitbucket who appear to have fixed it; everything is working again with no code changes.

They don't list the new parameter on their site, so I guess we just got an early look at API v2.1 :wink:

Thanks for your help!

**Comment by gtaylor** [comment]
wow, I wish it was always this easy.
