### ISSUE TITLE
Override deploy default behaviour of 'when'

### ISSUE THREAD

**Issue by ralfschimmel** [drone/drone#1406]
> Deployments are triggered at the end of a successful build. Note that deployment steps are not executed for pull requests or failed builds.

I really want to deploy my PR's, meaning I have to do this as the last build step, in 0.4.
Why not implement the `when` here and allow something like;

```
 when:
  events: pull_request
```

Obv. we would need to defaulting to the current behaviour.

**Comment by tboerger** [comment]
@ralfschimmel this won't work currently as most deployments rely on secure variables and those are still not injected into pull requests.

**Comment by bradrydzewski** [comment]
@tboerger I'm thinking of lifting that restriction as long as a checksum is present.

@ralfschimmel I think this is definitely possible. We need to ensure, however, that all publish and deploy plugins are defaulted to only execute when the event is of type `push`. The biggest blocker here is actually quite simple -- we need to improve the test coverage for the build runner ([drone/drone-exec](https://github.com/drone/drone-exec)) so that we can feel more comfortable rolling out this sort of change

**Comment by ralfschimmel** [comment]
Sounds good @bradrydzewski , any ETA on lifting the restriction?

**Comment by bradrydzewski** [comment]
let's merge this with https://github.com/drone/drone/issues/1476 which has an in-depth, ongoing technical discussion about executing plugins during pull requests
