### ISSUE TITLE
no warning when .drone.sec checksum is invalid

### ISSUE THREAD

**Issue by ryane** [drone/drone#1408]
It would be nice if there was some kind of warning to advise you when you pushed a new .drone.yml without re-running `drone secure` [1] to update the checksum.

The scenario: I had an existing `publish` section in my .drone.yml that used the docker plugin to push an image to docker hub. It used secrets encrypted in .drone.sec and it was working correctly. I added another `publish` section to trigger a push with a different tag when the repo was tagged. After pushing the change, drone ran and reported a successful build. However, I noticed no new docker images were published. When I looked at the build logs, I saw that the build step completed but none of the publish tasks ran. 

After much troubleshooting, I remembered I had forgotten to run `drone secure` after updating .drone.yml. I did that and subsequent builds successfully ran my publish steps.

I don't know if the build should fail in this scenario but I feel like there should at least be a warning somewhere indicating that the checksum didn't match. Right now, drone reports a successful build and just silently skips the publish steps.

[1] `drone secure --repo user/repo --in ./secrets.yml --yaml .drone.yml --checksum`, for example

**Comment by bradrydzewski** [comment]
I ran into the same issue today. You can add `debug: true` which does output useful debugging day and would have surfaced this error. I just pushed a quick change that will display the error by default, without having to enable debug mode.

> I don't know if the build should fail in this scenario but I feel like there should at least be a warning somewhere indicating that the checksum didn't match

Since you asked, and because others may have the same question ...

The reason we don't fail the build is because we want the ability to test pull requests even if the yaml changes. In some cases, especially with public repositories, the pull request author may not have the ability to generate a new `.drone.sec` file. This avoids a chicken-and-egg issue where the maintainer cannot merge the pull requests until tests are run, but the tests cannot be run until the `.drone.sec` has a valid checksum.

**Comment by ryane** [comment]
thanks! makes sense and the `debug: true` option is helpful
