### ISSUE TITLE
Patch release?

### ISSUE THREAD

**Issue by cweagans** [drone/drone#1438]
It would be awesome to have another release that has the `nsswitch.conf` fix included, even if it's just a patch release. Any plans for another tag/release soon and/or getting on a semi-regular release schedule?

**Comment by davidak** [comment]
maybe related to https://github.com/drone/drone/issues/1428

**Comment by bradrydzewski** [comment]
@cweagans we release a new version of drone on every successful commit, even if we don't increment a version number. This means the drone/drone:latest and drone/drone:0.4 image have the latest nsswitch.conf changes

**Comment by cweagans** [comment]
@bradrydzewski Is there any particular reason you do that? Seems weird to have a tag that changes all the time, especially if you're shooting for reproducible deployments (i.e. if I test with 0.4 on my local environment and then deploy to prod, I should be able to deploy the *exact* same version -- it shouldn't change).

**Comment by gtaylor** [comment]
We probably should use "latest" for what we are currently using 0.4 for, with versioned tags never changing after they are built+pushed. Some people may want to ride trunk (latest) or any special branches, but may/most are going to want a pinned version that doesn't change because unexpected breakages stink.

**Comment by cweagans** [comment]
^ that.

**Comment by bradrydzewski** [comment]
The current practice is not uncommon. If you look at the node image (https://hub.docker.com/_/node/) every modification to 5.X updates the `node:5` image tag, every change to `5.5.X` update the `node:5:5` tag, and so on. Docker tags are not considered immutable.

Tags are primarily used by this project to highlight breaking changes between versions. The reason we don't use tags more heavily is that we release constantly and auto-upgrade major portions of the system. Every time we merge a change to one of the 50+ plugins (docker, git, etc) or the build runner, your system auto-upgrades. This level of continuous delivery is unique and is the reason we may not follow conventions used by other projects.

**Comment by bradrydzewski** [comment]
also, I want to add that our current approach works well with tools like [watchtower](https://github.com/CenturyLinkLabs/watchtower). I can instruct watchtower to auto-upgrade `drone/drone:0.4` every time a newer image version is available. I would not want to use `drone/drone:latest` because there may be breaking changes between `drone/drone:0.4` and `drone/drone:0.5`

**Comment by gtaylor** [comment]
The problem is that for each actual point release (0.4.1), there is no static tag. There's just 0.4.

https://hub.docker.com/r/drone/drone/tags/

I think there's a lot of value in auto-upgrading plugins, but auto-upgrading the base Drone is not actually going to be desirable for all users. Especially those with a huge amount of integrations with APIs (in the enterprise especially). As the project grows, it's going to be harder to keep minor breaking changes (or new show-stoppers) from appearing.

Also, while watchtower is convenient, I'd be super hesitant to use such a thing in a high-traffic Drone setup. I'd really want to know what I'm getting into with each point release, whereas smaller companies and teams are more likely to care less.

**Comment by cweagans** [comment]
> I can instruct watchtower to auto-upgrade drone/drone:0.4 every time a newer image version is available.

Yeah, but people that care about things not going down in the middle of the night avoid auto-update like the plague. It kind of seems like you could get what you're going for by having a `0.4` tag that changes a lot, and then `0.4.1`, `0.4.2`, etc tags that *are* immutable - and these could be released fairly frequently as long as `0.4.1` is always `0.4.1` and it never changes. `0.4` can be anything, of course.

> Every time we merge a change to one of the 50+ plugins (docker, git, etc) or the build runner, your system auto-upgrades.

Honestly, this scares the hell out of me. If the goal is to replace Jenkins, then the implementation is almost certainly *not* to run the bleeding edge of everything. As a sysadmin, I expect that when I ask for a specific tag, I get that specific tag and not just whatever happens to come out of the repo.

**Comment by gtaylor** [comment]
Also, node isn't pushing every update to 0.5:

https://github.com/nodejs/node/tree/master

![image](https://cloud.githubusercontent.com/assets/75556/12693680/c1b26ea4-c6c5-11e5-8d26-5f6e1feaabce.png)

Here's the top of the [Docker hub tags](https://hub.docker.com/r/library/node/tags/):

![image](https://cloud.githubusercontent.com/assets/75556/12693682/d0828f0e-c6c5-11e5-82b9-5cf5784fb113.png)

They're actually tagging these releases: https://github.com/nodejs/node/tags

I think this is the perfect balance, in that you are tagging actual releases:

![image](https://cloud.githubusercontent.com/assets/75556/12693685/fc839c4c-c6c5-11e5-9b48-cb58dc13354f.png)

Users can then choose whether they want to pin against the major, minor, or revision based on their tolerance for risk or breakage. With Drone, your only current option really is 0.4, which is tracking git master (which is definitely going to spook some).

**Comment by bradrydzewski** [comment]
Perhaps I've just become more comfortable with the lack of version numbers from using Go which has no concept of dependency version numbers ...

@gtaylor `node:5` and `node:5.5.0` and `node:latest` are all tagged to the same base layer [1]. The point here was that docker tags are not treated as immutable as https://github.com/drone/drone/issues/1438#issuecomment-177035299 seemed to suggest.

I think we disagree that every push should tag a new image or that tags themselves should be immutable (its ok to disagree). I'm not sure we're going to persuade each-other either way so I don't want to beat a dead horse. I think we can periodically tag images with minor versions as a compromise.

> Yeah, but people that care about things not going down in the middle of the night avoid auto-update like the plague. 

We have been auto-upgrading for months now and this has not been an issue. I'm sure there will be a point where we push some bad code, and when we do, we'll push out a fix, learn from our mistakes and move forward. On the flip side, we've fixed major bugs and added great new features that were immediately usable as a result of auto upgrades. I think it is a net positive, but understand we may disagree here.

> As a sysadmin, I expect that when I ask for a specific tag, I get that specific tag and not just whatever happens to come out of the repo.

I'm sorry to say this is not how Drone works. Large portions of Drone auto upgrade and this is considered a feature of the system, but understand we may disagree here.

I'm not looking to have a heated debate over this topic. I'm fine with more frequent tagging. I'm not interested in changing plugin auto-upgrades at this time.

[1] https://imagelayers.io/?images=node:latest,node:5.5.0,node:5.5
