### ISSUE TITLE
Only build PRs on public repos if drone configuration hasn't changed

### ISSUE THREAD

**Issue by siddharthist** [drone/drone#1442]
This ticket tracks @Cadair's point (2) in #1061, and has the same motivation as #1441.

A great way to secure drone builds from PR attacks on public repos is to disable automated builds except when the drone build configuration hasn't changed. This would make it significantly more difficult to inject malicious code into the Docker image and have it expose Drone's secrets. 

This would allow public repos to have automated testing without maintaining a list of trusted users.

**Comment by bradrydzewski** [comment]
@siddharthist I'm going to close this because the `.drone.sec` file (which didn't exist when #1061 was logged) has a checksum of the yaml encrypted into the file. If the checksum doesn't match no private data is injected into the build environment, thus protecting the pull request (and the build) from those attacks.

You can read more at http://readme.drone.io/usage/secrets/#checksums:0d943d142dc6bcdd2e544b095a49f72b

**Comment by siddharthist** [comment]
@bradrydzewski Thanks for pointing me in the right direction!
