### ISSUE TITLE
Add new repository from Bitbucket without restart

### ISSUE THREAD

**Issue by bndw** [drone/drone#1472]
After the initial setup of Drone with the Bitbucket remote_driver, newly created Bitbucket repositories are not added to the system unless the Drone container is restarted.

Steps to repo:
1. Setup drone with Bitbucket
2. Login to the web interface, note all of your Bitbucket repos
3. Create a new Bitbucket repo

Expected:
I expected to see the new bitbucket repo in the web interface. I also tried to log in/out. Only after restarting the Drone container did it pull in the new repository.

**Comment by bradrydzewski** [comment]
drone has a 15 minute cache in place, as a result a repository may take 15 minutes for a repository to appear.  The restart isn't technically necessary, since the cache will flush automatically after the 15 minute expiration.

there is another open issue for a refresh button in the UI to manually flush the cache. I will find and re-post the issue number

**Comment by bradrydzewski** [comment]
moved to issue #1232
