### ISSUE TITLE
Demo of open-source drone

### ISSUE THREAD

**Issue by techtonik** [drone/drone#1480]
Reticketed from #1479.

Because https://drone.io/ looks out of order and (probably) on different codebase, where to see the working demo of open source drone?

**Comment by bradrydzewski** [comment]
We provide a Docker image that you can download and install. Please stop opening this tickets as it causes un-necessary noise. Feel free to use https://gitter.im/drone/drone for questions, and reserve the issue tracker for bugs or feature requests for this codebase

**Comment by techtonik** [comment]
Okay. I was forced to create tickets, because old ones were closed without ability to comment on them.

**Comment by kisst** [comment]
@bradrydzewski 
The success or failure of an open source  project relay on good tutorials and demos but Dron.io lack of both.

I tired to setup drone for few days without any luck, neither the docker compose files, nor the docker images, nor the cloudformation example does not work, with either gogs or github, but I'm giving up now. There is no way this could be a long living project, if basics like this is not exist, and I do not want to invest days into something just to try it out. It's a pity because it looked like a good alternative for self hosted CI.

I recommend Jordan Sissel's talk on PuppetConf 2013 about the logstash  community

**Comment by gtaylor** [comment]
@kisst This comment isn't especially constructive. If you want to file issues with specific errors or descriptions of the problems you encountered, you'd be positively impacting the situation.

> I recommend Jordan Sissel's talk on PuppetConf 2013 about the logstash community

logstash can be pretty difficult to set up and evaluate beyond a your dev machine. What is being suggested?

**Comment by bradrydzewski** [comment]
> The success or failure of an open source project relay on good tutorials and demos but Dron.io lack of both.

This is open source. The success of the project relies on the community of people working to make this better. If you want to see improvements you can pitch in and help. Donate time. Donate money. Provide constructive feedback. Provide good bug reports. Complaining isn't going to change anything.

> I tired to setup drone for few days without any luck, neither the docker compose files, nor the docker images, nor the cloudformation example does not work

The docker-compose file in the official documentation works out-of-the-box and includes descriptions and screenshots. There are plenty of people every day that read this documentation and successfully install Drone. There are also plenty of people that have difficulties and seek help in our forums. It is unfortunate that you have chosen not to use any of the community forums, which could have saved you time and helped you get Drone running successfully.

__documentation__

http://readme.drone.io/admin/installation-guide/
http://readme.drone.io/admin/setup-github/

__help forums__

https://discourse.drone.io
https://gitter.im/drone/drone

**Comment by kisst** [comment]
Hi @bradrydzewski @gtaylor,

Thanks for the quick respond, actually I'm positively disappointed to get any respond, after pushing away users from the gitter account with the "welcome" message stating clearly, that asking for help is not welcomed there.

First let's be constructive and then will respond to the points you raised, because originally I wanted to help with pointing out the weak point. The fact that we are having this debate under a ticket under a ticket about a demo system, my original suggestion would have been to setup a demo system as originally @techtonik suggested, but as I wrote any functional example would work with me.

> I tired to setup drone for few days without any luck, neither the docker compose files, nor the docker images, nor the cloudformation example does not work, with either gogs or github, but I'm giving up now.

So as I said before I could not make it work with either of this options but  clearly I made something wrong if you say it is working, I just never seen it, nor seen anyone who did managed to try it out, and I would like to think that I tried.

I started on the http://readme.drone.io/tutorials/ page but moved on quickly because there is nothing at all there, but even more, if I would decrypt somehow what magic words I need to murmur, or what type of sacrifices animal I need to offer to the god's to make it work I can't even publish my findings so I moved on to the, the http://readme.drone.io/admin/installation-guide/ page where the docker-compose version is "described" but that does nothing, after figuring out the undocumented dependencies like has connect to a version connect just to boot it up, and etc I got nothing, the page is up, even managed to get the oath2 callbacks and etc but there is nothing visible nothing to change so still have not seen anything to work.

So as even assets was missing, the CSS fail apart I give a chance to the ready whole setup, thinking that maybe it's something around the fact I tired to run localhost without public domains or something like that, as this is primarily a self hosted solution I did expect to work but anyway, next try was with  https://github.com/drone-demos/drone-on-ecs which does offer a ready solution with the whole infrastructure, and I got nothing again, not even a page as the ELB never registered any of the node, only 503.

The next thing was when I discovered that drone already use drone to check the PR's on github which is the minimum, but that was also undocumented, anyway I found http://beta.drone.io on a PR, so I tried to login, and after I created an other dummy github account because of the tons of permission what the page asked for, I got catch in a redirect loop, and github marked that it received too much request from the system and I need to re-authorize and then again re-authorize, and re-authorize I give up on that as well.

So that's how far I got, and still have not seen the software in action.

> Logstash was started in 2010 and has many more years to mature and grow the project. Drone is a young project by comparison. Building a project and creating world class documentation takes a lot of time and effort. Surely as a developer you understand this?

I do understand how much effort is to create documentation, and to be honest I'm not there yet to miss the detailed documentation, all I want is to have a peak look to know what to expect, to give a reason to go after it. The reason why I give Logstash as an example is not because of the quality of they documentation but the mentality how they handle it.
"If a new user has a bad time it's a bug"
https://www.youtube.com/watch?v=fwMnb4-t8vo&t=3m2s till 5:45

`</sass>`
I think as a first step you should remove the message from gitter which send away the users, that for me was a cut off moment. 
Then give at least one functional playground could be something you host ( I can help with that ) or can be something where you should them how to host them self, the docker can be a good direction, but needs work. But it even can be a quick video to show off the different functions check out any of the guides from buddy works, they are amazing.
As you already clam to have a working demo system with docker-compose, let's try to finish that first, get a test repo which can be build, have the hooks, have build steps, and in general show all the available function on the system, AND do not forget about dependencies requirements and presumptions, I alway think of [this picture](http://devhumor.com/content/uploads/images/November2014/X17puIB-animation.gif) when I'm writing documentation, try it maybe it will help.

**Comment by tboerger** [comment]
You had the option that is mentioned on the issue template. Join the Gitter chat and talk about it, the issue tracker is reserved for issues, the forum or the Gitter chat is for discussions and questions. You ignored that, so the issue gets closed and locked.
