### ISSUE TITLE
Frontend build logs don't stream

### ISSUE THREAD

**Issue by jpillora** [drone/drone#1481]
In drone 0.3.x, logs used to stream as the builds ran. I was looking at the browser network tab and request URL just hangs for the whole build and only returns after its completed.

```
GET http://<drone>/api/stream/<namespace>/<repo>/<build>/1
```

I'm guessing this as a bug since it has `stream` in name though maybe this isn't supported anymore?

Edit: I'm using the [latest docker image](https://hub.docker.com/r/drone/drone/tags/) "0.4, 6 MB, 7 days ago"

**Comment by bradrydzewski** [comment]
I'm running the latest build and have no issues streaming. If you are running behind a reverse proxy please see the docs, as 0.4 switched from websockets to sse http://readme.drone.io/setup/proxy_reverse/

Feel free to use https://gitter.im/drone/drone if you need help so we can reserve the issue tracker for verified bugs and feature requests. Thanks!

**Comment by jpillora** [comment]
I'm using caddy and I just dropped in that config and still doesn't work. Maybe this is because I'm running caddy in another docker container and I'm forwarding back to the docker host like:

```
http://ci.company {
    proxy / docker01.company:8000 {
        proxy_header X-Forwarded-Proto {scheme}
        proxy_header X-Forwarded-For {host}
        proxy_header Origin ""
        proxy_header Host "ci.company"
    }
}
```

Will try debugging some more tomorrow and pop over to gitter. Thanks :+1:

**Comment by bradrydzewski** [comment]
Sure, if you find any adjustments are needed to the caddy documentation let me know and we can update accordingly

**Comment by sroze** [comment]
I'm actually experiencing the same issue with but even without an nginx reverse proxy in front of Drone. Any path of investigation?

**Comment by bradrydzewski** [comment]
@sroze I'm running 0.4.0-beta+268 (latest build) and ran a few tests using Chrome 50.0.2661.0 canary. I can confirm that logs are streaming as expected on my machine.

I recommend using chrome developer tools to inspect the event stream (I attached a screenshot of what I see). I would check for javascript errors in your browser console. I would check for server-side logs (docker logs drone) to see if there are any useful errors.

If none of the above debugging helps I would check the gitter.im/drone/drone room to see if anyone else is experiencing this issue. If nobody is experiencing the issue this means it might be specific to your environment and therefore might require advanced debugging on your end (since the core maintainers can't debug what they can't repeat). If that is necessary I can walk you through the process.

<img width="357" alt="screen shot 2016-02-29 at 9 49 06 am" src="https://cloud.githubusercontent.com/assets/817538/13403429/d99de360-dec9-11e5-8d2e-c435ca2453db.png">
