### ISSUE TITLE
go install and drone cache

### ISSUE THREAD

**Issue by let4be** [drone/drone#1483]
`go install` does not rebuild already built packages, but when you build via Drone with caching of the whole `$GOPATH` it's not the case
My project is big and I can't afford time of rebuilding the whole project with all packages and dependencies on each commit as it would take minutes

I suspect `tar` does not preserve timestamps, any ideas?
P.S. why tar archives after all, won't simply mounting a docker volume be a better solution? Copying files is expensive operation

I'm new to drone, I've checked a couple of build systems and so far not so much success in comparison with a standalone server and a couple of shell scripts, it's almost impossible to achieve the same/close build speed as with custom scripted solution(or it's very hard to do and requires a couple of weeks digging into docs/sources...)

**Comment by let4be** [comment]
also see: http://stackoverflow.com/questions/35378904/how-go-install-finds-out-when-to-rebuild

**Comment by bradrydzewski** [comment]
This issue needs more information to help troubleshoot. For starters, what is your yaml file and cache configuration look like? It is possible you have the wrong configuration which is why this isn't working, but without a yaml we cannot verify. I presume your yaml looks like this?

```
cache:
  mount:
    - /drone/pkg
```

> I suspect tar does not preserve timestamps, any ideas?

This is something you could easily test on your own. This is a community of volunteers, so we expect that prior to logging an issue you've done the full amount of troubleshooting. You could test your hypothesis with the following:

```
build:
  image: golang
  commands:
    - ls -la /drone/pkg/linux_amd64/github.com/.../...
```

> P.S. why tar archives after all, won't simply mounting a docker volume be a better solution? Copying files is expensive operation

Docker volumes are not threadsafe for concurrent builds and the current solution is threadsafe for concurrent use. We considered Docker volumes but they are not adequate for our use case.

Please note that you can use volumes, if you really want, instead of Drone's default caching solution:
http://readme.drone.io/usage/build_test/#volumes:fb92aa3346185c57f15afda861d465a3

> I've checked a couple of build systems and so far not so much success in comparison with a standalone server and a couple of shell scripts, it's almost impossible to achieve the same/close build speed as with custom scripted solution(or it's very hard to do and requires a couple of weeks digging into docs/sources...)

This shoudn't be surprising. I would always expect a custom script completely tailored to your codebase to perform better than a generic server-based solution like Drone.

**Comment by bradrydzewski** [comment]
I'm going to close due to inactivity. This issue needs additional research with some items suggested above. If that research is completed and someone can come up with an exact diagnosis for the issue we can re-open and work on a patch
