### ISSUE TITLE
Idea to use Docker Host machine daemon and remove Dind

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#1531]
Today I received an interesting suggestion to create an image during the first phase of the build, and then use this image during subsequent phases. For example:

```yaml
build:
  create_image:
    image: foo
      # .... some yaml syntax to build image foo ....

  use_image:
    image: foo
    commands:
       # ... commands run inside the build image ...
```

The __problem__ with this approach is this would build the image on the host machine and would give a malicious pull request the ability to overwrite a tag. For example:

```yaml
build:
  create_image:
    image: golang
      # .... evil pull request overrides Go image on host to do evil things ....

```

The __solution__ to this approach would be to namespace the build image name. When we parse the Yaml file we could convert image name to a random value and substitute throughout the remainder of the Yaml. This random name could look like this:

```
tmp_3da541559918a808c2402bba5012f6c60b27661c
```

The below diff demonstrates the Yaml before and then after substituting the image name with the random or namespaced value:

```diff
build:
  create_image:
-    image: foo
+    image: tmp_3da541559918a808c2402bba5012f6c60b27661c

  use_image:
-    image: foo
+    image: tmp_3da541559918a808c2402bba5012f6c60b27661c
```

## Publishing?

Some other benefits may be the ability to build an image in one step, run tests in the image in subsequent steps, and then publish the image. This is possible today but requires mounting the host machines docker socket and running the build in trusted mode, which is not considered secure for open source repositories.

The __problem__ when publishing is that above we propose using a random image name:

```
tmp_3da541559918a808c2402bba5012f6c60b27661c
```

We need the ability to publish the image which means it needs to be tagged. This brings us back to the security issue identified above that tagging an image on the host machine could allow a rogue build to replace trusted images with evil images.

The __solution__ is that we can use a custom Docker registry client. This would give us the ability to publish an image to the registry, with tags, without having to tag images in the host machines Docker cache.

There is even a Docker registry client available from the good folks at Heroku:
https://github.com/heroku/docker-registry-client

## Caching

I believe this could also be used to cache Docker layers to reduce build time of Docker images. If we leave the images on the host machine we should be able to re-use them later. We would need to come up with a policy for deleting images and layers from the host machine to avoid disk issues (this could be a separate daemon or cron job).

## Security

We need to verify that we can come up with a unique name / namespace for images. This should be possible by using a sha256 hash of image name combined with repository-specific information.

We need to ensure that a pull request cannot override images or image layers on the host machine. This could allow a rogue pull request to replace a trusted build image with an evil image.

We need to understand how Docker layer caching works to ensure that a rogue repository cannot find a way to create layers that would get picked up and used by other repositories.

**Comment by bradrydzewski** [comment]
note that this is definitely a __help wanted__ issue if anyone is willing to help. I am looking for a proof of concept with the following properties:

* written in Go
* runs in a Docker container
* accesses the host machines Docker cache from a --volume mount
* given an image tag (ie tmp_3da54155) it is able to push the relevant image layers to the Docker registry
* it is then able to tag that top layer in the registry using a custom tag by uploading a manifest that is generated on-the-fly
* the previous step should not impact the host machine in any way

**Comment by frapposelli** [comment]
subscribing and paging @hickeng

**Comment by gtaylor** [comment]
I'm no help on the implementation side of this right now, but I like some of these positives being mentioned. Our build speeds are a bit slower, in that we are a Python shop and the packaging situation isn't great. The caching of image layers would be a nice boost. Ditto for the image creation/publishing changes.

The combination of those perks would make Drone much more suitable for Python and maybe even other interpreted languages.

**Comment by steve-gray** [comment]
I've solved this problem without any kind of craziness in the work I've been doing with docker.

build:
  - step 1: (NodeJS image) Create your app, get it ready. (npm install, etc)
 - step 2: (Docker DIND image) - Run docker-compose file from repo.

My docker compose file has a 'build: .' line in it (and it's actually the same file I use for doing vagrant images locally). So the commands for step 2 look like:

- docker-compose -p my_project up .
- // Run my tests against the stack (Use test-runners in seperate containers), such as:
    - docker run -it -rm --name test_runner  some-test-suite-runner

Basically all you've got to do is get your folder structure into a docker-compose compatible shape before step 2.

What I've had to do though is create a DIND image of my own based on something a bit fresher than the official drone one, because the Alpine base image in use didn't seem to recognise our internal docker repository SSL certificate - but when  we remade the image on CentOS 7 it was fine. That also gave us the window to inject the docker-compose tooling in there.

To recap:

- Run initial build tasks to put repository into correct shape for dockerizing.
- Have a 'Dockerfile' for your app in it's repo
- Have a 'docker-compose.yaml' file for bringing up your image as part of a stack, by specifying it as a 'build: .' and not an image-based service.
- Run supplimental test runners as 'commands' against the docker image.

The only 'inefficiency' is that the docker-build process has to re-run again at the end in order to do the publish, but relatively speaking thats inconsequential.

**Comment by stevenpall** [comment]
@steve-gray I've been thinking about doing basically that except instead of running Docker-in-Docker, just hitting a remote Docker TCP endpoint (this could even be Swarm running someplace). This way, the build cache should be preserved assuming the only thing that's changed is the code. The other thing I like about building the image first and running tests against it is that if a Docker image is going to be your final artifact, you're guaranteed that the image built is the one that has passed tests and vice versa. This also allows you to tag and push the image once tests have passed.

The only thing I need to work out is how to tear down the containers started by compose if tests fail. I think this should be fairly straightforward using something like bash traps, though.

I should note of course that this method isn't the most secure way of going about things, but we're only running Drone internally, and thus don't need to worry about the malicious pull request issue mentioned by @bradrydzewski above.

**Comment by mariosotil** [comment]
@bradrydzewski I implemented something similar to what you're designing. I'm using drone 0.4, and I need to build on-the-fly a docker image using the Dockerfile from some git repo.

So, my version 0.1 receives three parameters:
- the name of the local image
- the URL to the git repo
- the folder where the script can find the Dockerfile

If the image was not built before, it will pull the folder with the Dockerfile from the git repo, build the image, and save it into the local storage. Otherwise, it will just continue.

The .drone.yml file looks like this:

```
build:
    toolchain:
        image: mariosotil/docker-builder
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        commands:
            - /root/build.sh local/golang https://github.com/docker-library/golang.git 1.7
            - docker images | grep local/golang
    compile:
        image: local/golang
        commands:
            - go get
            - go build
            - ...
```

The Dockerfile to build `docker-builder` and the `build.sh` script are [here](https://github.com/mariosotil/docker-library/tree/master/docker-builder).

**ToDo:**

- Read from private git repos
- Run docker-builder using a non-root user
- Check the risk about malicious pull requests 
- Convert it into a drone plugin

Looking forward for your comments, improvements, ideas, etc.

**Comment by bradrydzewski** [comment]
@marcosnils see the following thread that describes pros and cons to various approaches to working with docker, including the above you've mentioned:
https://discuss.drone.io/t/working-with-docker/220

You will note that the problem with this approach is security. Exposing the docker daemon socket is like giving your build root access to your host machine, which is not desirable for many drone installations and especially open source projects using drone that accept pull requests.

The purpose of this issue is to explore a native solution within Drone that has security guarantees and does not expose the host machines docker daemon.
