### ISSUE TITLE
Prevent "toggling" off the last admin user

### ISSUE THREAD

**Issue by kimf** [drone/drone#1561]
I managed to stupidly click the "toggle admin" on myself and I was at that time the only admin user.

Was easily fixed by changing it back in the database, but maybe there should be some kind of safeguard for that feature to prevent removing the last admin.

**Comment by tboerger** [comment]
Maybe it should be even enough to prevent it in the new react based UI.

**Comment by bradrydzewski** [comment]
There are a number of issues with the current approach to defining admins in the database:

* what happens if the last admin is deleted?
* what happens if the only admin leaves the company?
* what happens if you are setting up drone, and someone logs in before you and becomes the admin? (_this is very unlikely but setting the first user as an admin is less than ideal_)

I would prefer to start defining the system administrators using an environment variable (we do this with aircover) to avoid the issues mentioned above. This would be provided to your drone docker container with `-E` or the `--env-file`

```
ADMIN_USER=bradrydzewski,tboerger
```

**Comment by tboerger** [comment]
The aircover approach is totally fine

**Comment by MetalMatze** [comment]
I've overlooked this issue, sorry. @tboerger pointed me in gitter to this.
I've tackled this in #1595 aswell. 
Additionally I'm disabling the **Toggle Admin** & **Delete User** if it is the user itself in the UI.

**Comment by bradrydzewski** [comment]
closing in preparation for 0.5 which moves admin configuration to the  `DRONE_ADMIN` environment variable, preventing such issues.
