### ISSUE TITLE
Get on the Mesosphere DC/OS app store

### ISSUE THREAD

**Issue by nodesocket** [drone/drone#1583]
They already have crappy Jenkins. How hard would this be?

https://dcos.io/

**Comment by gtaylor** [comment]
Probably not difficult, but I suspect this is going to be one of those things that someone will need to contribute, rather than a core roadmap item.

Would you be interested in taking a stab at it?

**Comment by dellintosh** [comment]
FWIW: we are running a Drone.io 0.4 server in our DC/OS Marathon cluster.  Just had to create an application, you can use the JSON here as a starting point:

[drone-0.4.json.txt](https://github.com/drone/drone/files/362786/drone-0.4.json.txt)

That being said, I think it'd be super cool to have 0.5 running and be able to scale the workers... I wasn't able to get that working within the time I had... so had to just stick with 0.4.

**Comment by dellintosh** [comment]
FWIW: we are running a Drone.io 0.4 server in our DC/OS Marathon cluster.  Just had to create an application, you can use the JSON here as a starting point:

That being said, I think it'd be super cool to have 0.5 running and be able to scale the workers... I wasn't able to get that working within the time I had... so had to just stick with 0.4.

[drone-ci-0.4.json.txt](https://github.com/drone/drone/files/362796/drone-ci-0.4.json.txt)

**Comment by dellintosh** [comment]
@nodesocket / @gtaylor / @kamilchm / @xiaods / @gaocegege / @jpzk

It's underway at https://github.com/mesosphere/universe/pull/903 (and I'd love some input from folks here).  I've put down @bradrydzewski as the "Maintainer" (since I'm not in the drone org but just love what you guys are doing here).  Also, if you wanted to add any additional goodies to that PR I'd be super grateful!  Looking forward to getting it added to the Mesosphere!

**Comment by gtaylor** [comment]
@dellintosh Awesome work! And a very good idea.

As mentioned in that PR, you're probably going to want to put yourself as the maintainer, since we don't want to volunteer Brad for that responsibility.

**Comment by dellintosh** [comment]
@gtaylor Good call, I've put down my own personal email for the Maintainer... I went back and forth on that (since I'm not on the core dev team, but I'm technically the one who put this package together).  One thing that I'd ask from you guys is a few screenshots/logos/etc?

Can you take a look at [this section](https://github.com/mesosphere/universe#resourcejson) and let me know if you'd like to see anything Drone-specific added?

**Comment by gtaylor** [comment]
Oh, that's a good question. The various Drone sites are in a state of flux right now with 0.5 looming. I'd imagine there will eventually be some graphics that we could use here, but they unfortunately don't exist just yet.

**Comment by bradrydzewski** [comment]
@dellintosh I do have https://github.com/drone/brand which has some branding assets, including logos in various formats and a few screenshots.

Note that the screenshots include browser chrome and therefore may need to be cropped to meet the style guidelines of the DC/OS website.

**Comment by bradrydzewski** [comment]
closing this since it is being handled by the community (thanks by the way!)
