### ISSUE TITLE
Drone issues with org auth and public repos

### ISSUE THREAD

**Issue by kapilt** [drone/drone#1594]
So i've got a repo at https://github.com/capitalone/cloud-custodian. I do not have access to the organization to authorize webhooks/application integrations at the org level. I **do** have access to setup webhooks on the repository. However drone doesn't seem to support this for reasons that are unclear (and not really logged).

# Hosted Drone with commercial subscription

First attempt using the hosted drone.io service with a commercial subscription, i login, and automatic discovery takes place. However, I don't have organization access to accept the integration, ie. No organization access granted, access requested.

Using the manual add form at the bottom of that repos page, with capitalone/cloud-custodian, i get an error dialog saying i don't have access to the repo. Chrome network inspector shows this on the post to create the repo

```
Status Code:500 Internal Server Error
Not Found
```

# Private drone using latest image

Okay setup https://ci.cloudcustodian.io as a drone server running 0.4.1/0.4.0 (build from 5 days ago). Still no luck, due to lack of organization access.

# Manual add on the cli

```
$ drone repo add capitalone/cloud-custodian
POST https://api.github.com/repos/capitalone/cloud-custodian/hooks: 404 Not Found []
```

Playing around with the github api, and personal apps, i try adding an additional scope, repo:write_hook into REMOTE_CONFIG which then results in silent failure (ie no output, no errors in the log) when using the cli... but does nothing to the actual repo.

# Manual Setup of Repository Hook

Okay trying with manual setup of the repository hook

```
$ docker logs drone
time="2016-04-24T11:22:33Z" level=error msg="failure to find repo capitalone/cloud-custodian from hook. sql: no row
s in result set" 
time="2016-04-24T11:22:33Z" level=error msg="Error #01: sql: no rows in result set\n" ip=192.30.252.34 latency=2.63
9332ms method=POST path="/hook" status=404 time="2016-04-24T11:22:33Z" user-agent="GitHub-Hookshot/cd33156" 
```
Okay drone complains it doesn't know about the repo because it wasn't added.

# Manual setup with db mucking

setup a valid jwt token in the database (small go program to generate), and woot now i have status posting

but now failure to set status

```
$ docker logs drone
time="2016-04-24T14:35:44Z" level=error msg="error setting commit status for capitalone/cloud-custodian/6" 
```

unfortunately the actual error is never logged, which makes this hard to debug without setting up a custom compiled drone with error logging turned.

# Move On ?
 
Travis handles all of this out of the box, https://docs.travis-ci.com/user/github-oauth-scopes/
Note it does read:org

I'd love to use drone, but i'm a bit stymied at the moment

# BoilerPlate Issue

Thank you for taking the time to use Drone and file an issue or feature request. Before filing an issue please ensure the following boxes are checked, if applicable:

- [ X  ] I have searched for existing issues
- [ X ] I have discussed the issue with the community at https://gitter.im/drone/drone
- [ X ] I have provided a sample `.drone.yml` file to help the team reproduce
- [ X ] I have provided details from the build logs
- [ X ] I have provided details from the server logs by running `docker logs drone`
- [ X ] I am not using the issue tracker to ask why my build failed

**Comment by bradrydzewski** [comment]
Hi Kapil, you can customize the plugin scopes to see if adding `read:org` resolves the issue. You can add the scope parameter to your configuration string:

```
REMOTE_CONFIG=https://github.com?client_id=<...>&client_secret=<...>&scope=<...>
```

You can then provide the below value. Note that you need to provide the full string of scopes, not just additional scopes you want to add, because this will fully override the defaults:

```
repo,repo:status,user:email,read:org
```

**Comment by kapilt** [comment]
Didn't help unfortunately, yeah i was playing with the scopes earlier after poking through the source on scopes customization before resorting to the db hacking above. Anyways clean reset the whole thing. Not sure what the issue is, most of the log errors seem to get swallowed.

```
$ cat /etc/drone/dronerc
REMOTE=github
REMOTE_CONFIG=https://github.com?client_id=xxx&client_secret=xxx&scope=repo,repo:status,user:email,read:org
```

```
$ drone repo add capitalone/cloud-custodian
POST https://api.github.com/repos/capitalone/cloud-custodian/hooks: 404 Not Found []
```
with nothing in the logs, this is with read:repo,repo,repo:status all enabled on scopes.

Browsing through the web ui doesn't show any of the public repos under that org.

**Comment by bradrydzewski** [comment]
I just want to clarify a few points? Can you provide yes / no answers to the below three items just to be sure I'm clear on the specific details of this issue?

1. Can you see the repository in your list?
2. If no, this means it isn't being returned from GitHub in your repository list. We use the unfiltered results from the `/user/repos` [endpoint](https://developer.github.com/v3/repos/#list-your-repositories). 
3. If yes, what access to you have to this repository? Pull, push or admin?
4. Have you tried to navigate directly to the repository URL in Drone and activate?

Either way, the lack of admin credentials will definitely prevent you from registering a repository with Drone: https://github.com/drone/drone/blob/master/api/repo.go#L38:L46

You could relax these privileges with the following change to the above block:

```diff
-if !m.Admin {
+if !m.Push {
```

You might also need to comment out these lines that upload an ssh key since you won't have access without admin privileges: https://github.com/drone/drone/blob/master/remote/github/github.go#L304:L308

**Comment by bradrydzewski** [comment]
also note that the 
also this error here:

```
$ drone repo add capitalone/cloud-custodian
POST https://api.github.com/repos/capitalone/cloud-custodian/hooks: 404 Not Found []
```

is coming from here:
https://github.com/drone/drone/blob/master/api/repo.go#L89

Where is where we try to get a list of all your hooks in GitHub to insert or update a new hook. This 404 happens when you don't have adequate privileged to access the repository hooks.

**Comment by bradrydzewski** [comment]
also this error is due to lack of adequate permission to set the `repo:status` scope:

```
$ docker logs drone
time="2016-04-24T14:35:44Z" level=error msg="error setting commit status for capitalone/cloud-custodian/6" 
```

**Comment by kapilt** [comment]
I've got a debug build of drone running, It looks like its returning a 403 on the drone repo add capitalone/cloud-custodian now (which does silent return on the cli with no output)

in docker logs though
```
time="2016-04-24T20:18:28Z" level=info ip=96.241.30.238 latency=417.662µs method=POST path="/api/repos/capitalone/cloud-custodian" status=403 time="2016-04-24T20:18:28Z" user-agent="Go
-http-client/1.1" 
```

what's wierd is if i do a simple python script doing the same it works fine, creating a personal oauth token (and it worked fine for travis which is up and running), i'm wondering if its the request for Admin permission which is causing issues. i'm going to burn some cycles and try to debug via code mods some more, will report later.

**Comment by kapilt** [comment]
oh i should add i went ahead and switched from GetUserRepos to GetAllRepos, it returned a bunch more repos, but none from the capitalone org that are public.

**Comment by bradrydzewski** [comment]
the 403 happens when either 1) you don't provide your token to the cli or 2) you don't have admin access to the repository:
https://github.com/drone/drone/blob/master/api/repo.go#L43

the CLI is still heavily a work-in-progress so you should not expect friendly error messages or anything like that. You can manually navigate to the repository in the user interface to activate from there. You would likely see 403 "Administrative access is required." in the user interface

**Comment by bradrydzewski** [comment]
> oh i should add i went ahead and switched from GetUserRepos to GetAllRepos, it returned a bunch more repos, but none from the capitalone org that are public.

The `GetAllRepos` endpoint was deprecated because about a year ago GitHub changed the behavior of the `/user/repos` endpoint to return all user repositories, including organization repositories.

This is the endpoint we use from GitHub:
https://developer.github.com/v3/repos/#list-your-repositories

This is the endpoint description:

> This includes repositories owned by the authenticated user, repositories where the authenticated user is a collaborator, and repositories that the authenticated user has access to through an organization membership.

If your repository is not included in this list it could be for a number of reasons:

1. you are not a member of the organization
2. you are a private member of the organization and perhaps `read:org` needs to be added as a scope?
3. you did not enable drone to access that organization when you authenticated. See https://cloud.githubusercontent.com/assets/865/5805312/5701e842-9fd3-11e4-8f7b-a2bad994eb0a.gif
4. the organization restricts third party applications and does not whitelist drone. See https://cloud.githubusercontent.com/assets/2988/5803370/e8024542-9fcb-11e4-8dc5-1810c2281e27.png

**Comment by kapilt** [comment]
sorry for the delay, i only have time to debug this on weekends

1. I'm a member of the org
2. I've made my membership public
3. I do not have access to the org to give drone access
4. Likely re restricted org access, but i have the ability access to modify the repo under the org to give drone access manually which i assumed commuted to the api key, but it looks like it only applies to personal tokens, not to app authorization. Having played around with the github api a bit more this appears to be the crux of the problem. I'll have to follow up on this one with the org adminstrators.
5... I played around with scopes and the api a few times, it does indeed appear to be an issue wrt to 4, it looks like the org admins must have already authorized travis. 

So not a drone issue, thanks for the support. 

Re discovery sans 4.

Interestingly even though my org membership is public it doesn't show up when querying the orgs with the token unless the user is made explicit, i assume also related to 4.

Afaics the repo isn't listed when looking at the user's individual repos, the org is listed when looking at my orgs, and my user does have access to 

Re hook write access sans 4.

Fails, it appears i could use a personal auth token but that's a more serious feature change for a limited use case.
