### ISSUE TITLE
Gogs Private Repository with Drone 0.5.0 not working

### ISSUE THREAD

**Issue by joelchen** [drone/drone#1624]
Drone 0.5.0 fails to login over self-hosted Gogs repository. Drone responded, "Unable to login. Registration is closed." with Gogs running on HTTP port 10080 and SSH port 10022, and /etc/dronerc configured as such:
```
DRONE_DEBUG=true
DRONE_GOGS=true
DRONE_GOGS_URL=http://gogs.company.com:10080
DRONE_AGENT_SECRET=secret
I_UNDERSTAND_I_AM_USING_AN_UNSTABLE_VERSION=true
I_AGREE_TO_FIX_BUGS_AND_NOT_FILE_BUGS=true
```

**Comment by joelchen** [comment]
Got it working with instructions in http://readme.drone.io/0.5/manage/proxy_reverse/

**Comment by tboerger** [comment]
@joelchen you understand `I_AGREE_TO_FIX_BUGS_AND_NOT_FILE_BUGS ` not really, right?

**Comment by bradrydzewski** [comment]
@joelchen please read the documentation regarding user configuration:
http://readme.drone.io/0.5/manage/users/

also if you are going to use 0.5 please note that it is unstable and you should be digging through code and attempting to resolve issues yourself.  If you are unwilling to do so we would appreciate you using 0.4 stable instead.

```
I_AGREE_TO_FIX_BUGS_AND_NOT_FILE_BUGS=true
```

**Comment by joelchen** [comment]
Thanks for your reminders, @tboerger and @bradrydzewski. I'm not sure if this is best practice, but I wonder how do contributors and early adopters know about statuses of bugs without issue tracking.

**Comment by donny-dont** [comment]
@joelchen if people just open a bunch of bugs on 0.5 then it just overwhelms the issue tracker. This is why the environment variable is in place. If you want to try out 0.5 that's great it'll help get it in shape that much sooner, but we would like it if you actively chased down the issue rather than saying it didn't work.

Either the problem is user error, where the configuration you are using is wrong, in which case there might be issue with the documentation and that should be addressed by a pull request on the docs. If its something wrong with the code then actually debugging the issue and determining where it fails and providing a patch or a detailed description of your debugging would be the way to go. This particular issue does neither and that's why you got the response you have here.
