### ISSUE TITLE
ability to automate server and agent provisioning

### ISSUE THREAD

**Issue by jdamick** [drone/drone#1645]
(0.5) Right now server generates a token for the agents to use and outputs it into the log file:

```msg="agents can connect with token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9"```

This is painful to automate, if i want to spin up a server and a set of agents.  

Some thoughts:

- Be able to specify an intial / single-use token/secret to the server (in env) for incoming agents
  - Then set (in env) the single use token that the agents then use to provision themselves and exchange for a long-lived token. 

- Provide some kind of cli to generate the token so it could be done prior to deployment instead of dumping to the log file

- something else?

Thank you for taking the time to use Drone and file an issue or feature request. Before filing an issue please ensure the following boxes are checked, if applicable:

- [x] I have searched for existing issues
- [x] I have discussed the issue with the community at https://gitter.im/drone/drone
- [na] I have provided a sample `.drone.yml` file to help the team reproduce
- [na] I have provided details from the build logs
- [na] I have provided details from the server logs by running `docker logs drone`
- [x] I am not using the issue tracker to ask why my build failed

**Comment by brgaulin** [comment]
If it were in the UI of the main controller server, that would make it at least easier to get the key to share with your automation. So long as the key doesn't change I don't think we would really need more than that. 

For example, if building an auto scaling drone cluster, you will most likely just add agents, so you would know the key ahead of time, and could put that in your automation.

But exposing it too easily could be bad if it were a public drone server. Since anyone could ask for the token and add nodes to your cluster... This is a fun one :)

**Comment by bradrydzewski** [comment]
> For example, if building an auto scaling drone cluster, you will most likely just add agents, so you would know the key ahead of time, and could put that in your automation.

I do think this is an important point. I personally think we should treat the installation and management of server and agents as separate tasks for this reason. It is likely you will setup a server once, but scale agents up and down separately on a more frequent basis

**Comment by jdamick** [comment]
yeah i agree about the auto scaling and differentiation of server / agent deployments.  However, if we take the simple example of wanting to spin up a server & agent from a compose file automatically, how would that need to work? 

as for the auto scaled portion, it would be useful to be able to know how many & which agents are registered vs. 'attached' from the server's point of view.

**Comment by bradrydzewski** [comment]
> However, if we take the simple example of wanting to spin up a server & agent from a compose file automatically, how would that need to work?

Or should they be two separate compose files? I've been pushing for separate Kubernetes manifests and treating them as separate entities.

> as for the auto scaled portion, it would be useful to be able to know how many & which agents are 'attached' from the server's point of view.

This capability exists. We have a rest endpoint and command line commands for monitoring agents. You can run `drone agents` to get a list of agents which are constantly pining the server for heartbeat purposes, allowing you to identify agents that go offline

**Comment by andrewmclagan** [comment]
Imagine a situation where users orchestrate drone through docker-compose or similar platform.

Server container and Agent containers are booted together, would be handy to be able to initialise those agents immediately. Therefore have the entire system preconfigured.

**Comment by gtaylor** [comment]
While two compose files are possible, this is definitely a bit more clunky to work with. There are a few projects that do this various ways, but I'll draw from Django as an example:

1. At project creation time, the primary secret token is auto-generated and added to your primary settings file.
2. If you want to change it, you can. But you don't have to.

Something like this for Drone would be my selfish preference:

1. If no environment var for the token is present, check the DB for an existing token. If no token exists, create one and save it to the DB. 
2. If an env var is specified, do not query the DB. Use the value of the evar. Don't save it to the DB. We don't want to over-write any values that might be there in case someone needs to roll back or accidentally specified this value.

This needs to be *very* clearly and I suspect this would require some changes to the auth mechanism, but I'm sure there's a happy medium between ease of setup and security.

**Comment by gtaylor** [comment]
Also, pinging some k8s people on this in case they want to weigh in: @aronchick @viglesiasce

**Comment by aronchick** [comment]
Your best bet (if you're using Kubernetes) is to use ConfigMap or Secrets. These are atomic stores that you can mount it at the point of container creation. You could also use container hooks - http://kubernetes.io/docs/user-guide/container-environment/ (if your containers can't handle not speaking to the master (which they should be able to handle :))

**Comment by ekozan** [comment]
I like the @gtaylor idea

1.  Start server
2.  The server create an init token and save it to an backend ( Secret for K8S for example) 
3.  Start X agents
4.  Each agent can get the token from the backend and ask for uniq token 

So :
- you can rotate init key
- you can revoke uniq key from agent 
- it's really easy to implement autoscaling on kubernetes or other orchestration

**Comment by gtaylor** [comment]
I don't know if I'd want to do anything Kubernetes-specific in Drone, but the big thing I was asking for is to be able to generate the secret on my own and specify it at runtime without needing to check Drone Server's stdout. This would play nicely with Kubernetes and ECR manifests, and I'm assuming the same with Mesos.

**Comment by aronchick** [comment]
That sounds fine - I was only proposing a Kubernetes solution as that's all
I know :)

**Comment by gtaylor** [comment]
Sorry, I guess I didn't really frame that CC very well. My original intent was to see if you had worked on Kubernating anything that was similarly server->agent oriented. We're trying to find the right balance between security/auth and ease of setup between server and agent. The agents all connect to the server and provide a secret.

The flow currently looks like this:

1. Start the server for the first time. A token is auto-generated.
2. Read the server's stdout to get the token.
3. Take that token, start your agents with it set as an env var.

It works without issue, but the problem is that we have to pluck the secret from stdout.

With the goal of providing something that is reasonably secure by default but also easy to setup, I'd love to hear anything you may have ran into in the wild. While the current flow makes the Kubernetes setup a little more cumbersome, it'd impact other container orchestration frameworks that rely on manifests.

Selfishly, I'd love to have a setup process that is 100% deterministic and reproducible from manifests, whether they be Kubernetes, Terraform+CM, Mesos, ECS, or whatever. I don't know whether the right tradeoff is a shared secret or something else, however. Getting into the territory of self-signed SSL certs is probably a little too much as a default.

**Comment by bradrydzewski** [comment]
I've authored pull request #1657 to address this

You can now provide the agent with the `DRONE_TOKEN` or the `DRONE_SECRET`. If you provide the agent with the secret (the same secret you provide to the server) it will automatically generate the token.
