### ISSUE TITLE
Error with Postgresql and Gogs

### ISSUE THREAD

**Issue by krishna-kashyap** [drone/drone#1649]
On trying to use Drone with Gogs and Postgresql, authentication is successful but throws the error pq: syntax error at or near ")" on logging in. This is with both latest and Drone 0.4. No error seen in logs.

Gogs with Sqlite works perfectly fine. So I suspect something to do with the postgres DB driver issue

**Comment by bradrydzewski** [comment]
I believe the issue is related to the SQL query to generate your build feed:
https://github.com/drone/drone/blob/master/store/datastore/users.go#L113

We create an IN statement where the IN statement has a list of your repositories. If this IN statement is empty (meaning no repositories) it returns an error. The simple fix is to not execute the query if your repository list is empty, and just return an empty build feed. I'll take a look at this early next week, but in the mean time am open to pull requests.

**Comment by strk** [comment]
I'm having the same exact error, against Gogs 0.9.27.0512

Any news on the fix @bradrydzewski ?

**Comment by strk** [comment]
This should work:
```
  AND r.repo_full_name = ANY(ARRAY[%s]::text[])
```

I'll open a PR after testing it
