### ISSUE TITLE
nginx with SSL not working for build hooks?

### ISSUE THREAD

**Issue by sandywater** [drone/drone#1655]
Nginx with SSL
```bash
IP_ADDR - - [23/May/2016:16:37:39 -0600] "POST /api/hook?owner= sandy&name=docker-demo&access_token= TOKEN HTTP/1.1" 301 193 "-" "-"
IP_ADDR - - [23/May/2016:16:37:39 -0600] "GET /api/hook?owner= sandy&name=docker-demo&access_token= TOKEN HTTP/1.1" 404 18 "-" "-"
```
Without SSL
```bash
IP_ADDR - - [23/May/2016:16:46:24 -0600] "POST /api/hook?owner=sandy&name=docker-demo&access_token=TOKEN HTTP/1.1" 200 487 "-" "-"
```

Is there any official nginx.conf that I should be using?  Is drone meant to not be secure?

I would very much prefer a way to secure drone with SSL.

Thank you.

**Comment by sandywater** [comment]
Running via Docker on Ubuntu 14.04

**Comment by sandywater** [comment]
drone version 0.4.2

**Comment by bradrydzewski** [comment]
> Is there any official nginx.conf that I should be using?

http://readme.drone.io/setup/proxy_reverse/

**Comment by sandywater** [comment]
that doesn't make any mention of SSL.

**Comment by bradrydzewski** [comment]
Drone works perfectly fine with SSL termination using a reverse proxy. How you configure and setup SSL termination with nginx is up to you, and I'm sure is well documented on the nginx website.  When using SSL termination with Drone you just need to make sure you set `X-Forwarded-` variables so that Drone can determine its own URL, as mentioned in the official docs.
