### ISSUE TITLE
RFC: use plugins.drone.io as Docker index

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#1676]
There are a large number of developers creating plugins, however, there is currently no good way to share, distribute or discover these plugins unless they are added to the official plugins organization. I do not believe that a subset of the Drone community should be the gatekeepers to plugins (I'm mostly talking about me here), deciding which plugins are blessed or deciding which features should be included or excluded. I do not believe this approach is good for the drone ecosystem in the long run.

I would like to propose a number of changes that I hope to help grow the ecosystem, and create a more decentralized plugin model that encourages developers to create (or fork) and publish plugins based on their individual needs, and not based on what bradrydzewski thinks :)

__Plugin Index__

I would like to therefore propose a simple plugin index that can be used to discover plugins at `plugins.drone.io` similar to many of the other community sites:

* https://atom.io/packages
* https://supermarket.chef.io/
* http://godoc.org/
* many more ...

__How it Works__

Developers will be able to submit their projects to this index and choose a top-level name for their plugin. This top level name can then be referenced in the yaml like this:

```
pipeline:
  ...
  notify:
    image: emailer
```

Having a top level name is important because it removes any perceived bias that might exist today between official and unofficial plugins. Unofficial plugins will no longer have to use fully-qualified docker names in their Yaml

This can be achieved using `plugins.drone.io` to lookup the fully qualified image name. I believe this can be done by implementing a subset of the Docker index protocol. When drone server encounters a plugin name it can pull the image using `plugins.drone.io/{plugin}`. The plugin index can then return the actual registry url (ie `registry1.docker.io/....`) which the daemon can use to pull the image.

The benefit to this approach is that `plugins.drone.io` won't actually serve the image, which makes it much easier for us to host and maintain.

__Security and Whitelisting__

The 0.4 version of Drone implements plugin whitelists to prevent the use of malicious plugins. With 0.5 we have taken measures to eliminate the attack vectors associated with un-official plugins, and have therefore removed the plugin whitelist. So this won't be an issue going forward.

__Customization and Firewalls__

Some organizations sit behind a firewall and block outbound traffic to `plugins.drone.io`. These organizations can use the `PLUGIN_NAMESPACE` variable to change the plugin registry / namespace from `plugins.drone.io` to their internal registry, or they can host their own private plugin index.

**Comment by gtaylor** [comment]
I can only speak for myself, but the naming thing is a non-issue for us. We'd probably continue using direct Docker image names (with prefix), since it's a little more explicit as far as what is being pulled and from where. Also avoids the need to hit an additional service before pulling the image.

If we're worried about core plugins getting preferential treatment, the other option might be to get rid of the default namespace entirely (even for Drone core plugins). But this is probably just my anti-magic bias speaking.

I don't feel very strongly about this, as long as we'll be able to continue to still directly refer to plugins in Docker image format as we can now.

**Comment by donny-dont** [comment]
I think this is a great idea. I'm just concerned that its premature considering the state of 0.5.

**Comment by bradrydzewski** [comment]
Another idea I had was to have a yaml file that maps the plugin name to the image url:

```yaml
docker: plugins/docker
git: plugins/git
git_push: bradrydzewski/git-push
slack: bradrydzewski/slack
```

This could be versioned in a repository and developers could submit their plugins via pull request. This would potentially avoid having to hit an external service, since the mapping file location could be configurable (ie configure to fetch from `https://raw.githubusercontent.com/drone-plugins/drone-index/master/index.yml` or from `file:///path/to/index.yml`)

**Comment by gtaylor** [comment]
If we're set on doing this, the manual yaml map is a great way to minimize any further delay for 0.5 while providing a later path for expansion.

**Comment by bradrydzewski** [comment]
I think the question would be refresh policy. Any thoughts?

**Comment by donny-dont** [comment]
What if it needs to authenticate?

**Comment by bradrydzewski** [comment]
I think `plugins.drone.io` or the mapping file would be for globally namespaced plugin aliases (ie `git` -> `plugins/git`). If you were planning to use custom images that require authentication you would use the fully qualified image name and would not use the plugin registry or mapping file

**Comment by bradrydzewski** [comment]
another option is, as @gtaylor mentioned, to eliminate the plugin namespace all together. The yaml would be slightly more verbose:

```diff
pipeline:
  build:
   image: golang
   commands: [ go build, go test ]
  publish:
-   plugin: slack
+   plugin: plugin/docker
    repo: foo
  notify:
-   plugin: slack
+   plugin: plugin/slack
    channel: bar
```

**Comment by donny-dont** [comment]
@bradrydzewski I meant authenticate to get the gist or wherever else the thing is living.

**Comment by bradrydzewski** [comment]
for github / github enterprise you should be able to do `https://<token>:x-auth-basic@github.com/gists/<gist>` as the url

**Comment by vespakoen** [comment]
I think being more verbose is actually a good thing here.
It's less confusing, also, it becomes clear that "plugins" is a user account that you were able to "claim" on dockerhub and not some magic / special thing.

I for one was very confused by this at first.

**Comment by gtaylor** [comment]
I'd be inclined to agree. It is more verbose, but it also less behavior to confuse people or to have to spend much time in the docs. I think this would trip me up for a bit if I wasn't familiar with Docker and actively involved with Drone.

**Comment by subesokun** [comment]
I'd also vote for the more verbose version. Having none namespaced plugins will lead only to the issue that several people want to claim the same plugin name which might end up in the same security mess as happened to npm recently.

Regarding how to host / share this registry, well actually [jspm](http://jspm.io/) came up with a quite clever idea. It hosts a separate registry repository where among others a [registry.json](https://github.com/jspm/registry/blob/master/registry.json) file is put under version control. For Drone a similar file could be created that just maps the namespaced plugin name onto the Docker image.

So everytime you run a jspm install command it will clone the repo into a local folder and then looks up the real package name from there. As via Git only delta updates are happening this saves also bandwidth and time. Furthermore you can easily host this repository in your local network and tell jspm to clone the registry from your local network. Also other users can easily file a PR to add a new registry entry so no complex management UI is required.

As I daily face proxy issues it would be awesome if this registry would be part of the Drone Docker image itself as it's guaranteed that my Drone agents can talk to the Drone master but configuring each agent so that it can talk also to a registry that it located somewhere else is more tricky, especially if it's located in the internet. So ideally the Drone agents would clone/pull the registry from the Drone master and the Drone master can clone/pull it per default from the official Drone registry in the internet. This way it would require zero configuration by the users.

**Comment by bradrydzewski** [comment]
I'm closing this in favor of modifying drone to require fully qualified plugin names, even for official plugins, removing any perceived bias for official plugins.

```diff
pipeline:
  build:
   image: golang
   commands: [ go build, go test ]
  publish:
-   plugin: slack
+   plugin: plugin/docker
    repo: foo
  notify:
-   plugin: slack
+   plugin: plugin/slack
    channel: bar
```
