### ISSUE TITLE
Static go builds broken on Ubuntu Wily and Xenial

### ISSUE THREAD

**Issue by sokoow** [drone/drone#1765]
Ok, I think I got to the bottom of this: https://github.com/drone/drone/issues/1759

This affects all platforms, not only arm64.

We're hitting the following: https://github.com/golang/go/issues/13470 when doing static builds on ubuntu wily and xenial, due to this glibc issue: https://sourceware.org/bugzilla/show_bug.cgi?id=19341

Potential workarounds are to link against musl, like this dude does: https://github.com/tamird/cockroach/commit/a50a6d7fc0b8bdf438bd9a5e6e24acadfa9be7a7

I like his comment on the commit though.

**Comment by sokoow** [comment]
Another way to fix this would be to do static build like this: 

https://github.com/tamird/cockroach/commit/9c93044ce7d3283e78f5941b8b9bcd836f80a7ef

I'll test it in a free moment.

**Comment by bradrydzewski** [comment]
@sokoow it is also possible we do not require `-static` because `go-sqlite3` includes the full C source code that should get embedded directly. We would need thorough testing though before any such PRs are merged, because right now Drone is running fine on amd64 platforms and toggling compiler flags could result in instability on certain platforms

**Comment by sokoow** [comment]
I'll run it for a while on both amd64 and arm64 and see how it goes

**Comment by bradrydzewski** [comment]
edit: I was wrong. We need to statically link because otherwise Go will dynamically link glibc which will cause drone to fail on startup inside the Docker image, which does not have glibc.

I think for now we should only alter the compile argument for arm. I've added some notes to the pull request according with suggestions. This particular bug also seems to be specific to the server. I think the first step is to focus on running the server on amd64 and agents on arm. Once we have the agents and plugins ported, we can look at officially supporting drone server on arm.

Also, let's use [gitter](https://gitter.im/drone/drone) for these types of discussions as opposed to GitHub issues. Thanks!

**Comment by bradrydzewski** [comment]
also note: maybe we shouldn't be using ubuntu as the host build environment. Have you tried building drone using a different environment? Maybe inside an alpine arm image or something?
