### ISSUE TITLE
Stash not display all repositories

### ISSUE THREAD

**Issue by thiago** [drone/drone#1776]
I have a problem with the stash. Apparently it does not display all repositories that have access.

Performing some tests, I realized that the request is limited in 1000 and I have access to 1800 repositories.

My suggestion is to apply a paging client that consumes the api stash, but I can't ensure if this resolve the problem.

I got this problem with version 0.4 and 0.5.

**Comment by appleboy** [comment]
@thiago Closed this issue.

**Comment by mariusgrigoriu** [comment]
Not ready to be closed because you can't query a repo added to drone if it appears as the 1000th or later remote.  #1783

**Comment by thiago** [comment]
@mariusgrigoriu you're right! I did not know why this was happening, thank you.
Sorry by delay.

**Comment by bradrydzewski** [comment]
I merged #1783 which increases the limit to 15,000

I am closing this issue with the __wont fix__ label because ultimately I don't think we are going to fully solve this problem. If someone has 50,000 github repositories Drone simply will not be able to mashup the data efficiently. I view the current 15,000 repository limit as good enough workaround for the vast majority of installations.

Thanks to @thiago and @josmo and @mariusgrigoriu for their work on implementing the workaround.
