### ISSUE TITLE
Drone logs sensitive information on start up

### ISSUE THREAD

**Issue by bobrik** [drone/drone#1779]
On startup drone logs the following:

```
INFO[0000] using agent secret foo
WARN[0000] agents can connect with token bar.baz.yay
```

It also logs tokens from bitbucket and other sensitive information. It's a good practice not to log anything sensitive, so all logs can be centrally collected and presented to everyone.

**Comment by bradrydzewski** [comment]
this information is only being logged temporarily and will be removed before the official 0.5 release (0.5 is still pre-release). I didn't have time to add the token management screen to the user interface yet to retrieve the agent tokens, so printing to the console is a temporary solution so that people can start testing the agent implementation right away.

```
INFO[0000] using agent secret foo
WARN[0000] agents can connect with token bar.baz.yay
```

I've added this as a todo item to the existing issue https://github.com/drone/drone/issues/1386

I don't see where any bitbucket tokens are being logged in 0.5 master. If you can find instances in the code and open an issue we can remove those. thanks!
