### ISSUE TITLE
Tag drone docker image with ${DRONE_COMMIT_SHA}

### ISSUE THREAD

**Issue by vaijab** [drone/drone#1790]
A lot of us are actually using/testing drone in production. It would be great if we were able to pin to specific drone binary when running drone.

At the moment every build is tagged with `0.5.0` and `0.5`. Would it be possible to tag docker image with `${DRONE_COMMIT_SHA}` as well?

**Comment by bradrydzewski** [comment]
this was discussed in https://github.com/drone/drone/issues/1438#issuecomment-177075899

the problem right now is that individuals using 0.5 are using an unstable pre-release and I'm not really keen on tagging pre-releases. Once 0.5.0 is officially released the 0.5.0 tag will be frozen and we'll bump to 0.5.1

the goal will be to have much more frequent tagging to allow for more reliable version pinning. 0.5 pre-release is just a special case due to the duration of the pre-release and the amount of change taking place. 

so my suggestion is that once 0.5.0 and 0.5.1 are released we re-evaluate the tagging to see if that is meeting your needs. If not, we can discuss alternative approaches.

**Comment by vaijab** [comment]
Thanks. That's fair enough. Right now I am building my own docker image and using that, just to have control when and what changes I introduce to drone.
