### ISSUE TITLE
bitbucket hook creation failed

### ISSUE THREAD

**Issue by majest** [drone/drone#1811]
I have installed drone using rancher. Added configuration for bitbucket and mysql. I have an external domain access and managed to authenticate with account (gave all available permissions for the testing purposes). Problem occurs when activating the repository. 

"Unable to activate this repository. You must have administrative access to this repository. Also, please check the third-party application access policy to ensure Drone is approved. Bad request"

I have full admin rights to the repository, I can also create hooks manually.

Logs show 500 error with http://mydomain.com/hook?access_token=someaccesstoken. 
After checking the access token in jwt I get Invalid Signature. Payload and headers are fine. 

Would anyone point me in the right direction please?

**Comment by bradrydzewski** [comment]
> Unable to activate this repository. You must have administrative access to this repository. Also, please check the third-party application access policy to ensure Drone is approved. Bad request

you need to have administrative access to a github repository to enable it from drone. This is because drone needs to add post-commit hooks to GitHub, which can only be done by a repository administrator

> Logs show 500 error with http://mydomain.com/hook?access_token=someaccesstoken. 
After checking the access token in jwt I get Invalid Signature. Payload and headers are fine.

I'm a bit confused here because these seem like two different issues. The `/hook` endpoint is invoked by github when you push to a repository. The only way to invoke the `/hook` endpoint is to activate the repository in drone, and per the above error message, it failed to activate the repository. So how is `/hook` being invoked?

**Comment by bradrydzewski** [comment]
also, we should move the discussion to https://gitter.im/drone/drone ... we prefer to reserve the issue tracker for confirmed bugs (as noted in the issue template) and use our gitter channel for triage and general support. Thanks!!

**Comment by majest** [comment]
Thank you for your comments. They were very helpful. The problem is resolved now. Turns out it was a combination of permission caching and DNS propagation differences.

**Comment by andrewmclagan** [comment]
Could you enlighten us as to what happened with the DNS propagation as we are suffering the same issue after transferring to a new DNS provider
