### ISSUE TITLE
Robot accounts

### ISSUE THREAD

**Issue by vaijab** [drone/drone#1812]
I would like to start a discussion around robot accounts in drone. I might be completely off the right track here, any comments are welcome.
### Current state

Currently every user in drone has to be a real github, gitlab, bitbucket, etc user. This makes it quite costly and painful to build integrations with drone.

To talk to drone API, one must have a valid token to auth to the API. The only way to acquire a token is to login to drone using an existing github/gitlab/etc user.
#### \- Chain multiple drone jobs

I want to be able to trigger a job restart or deploy event from drone itself. For example, I have a pipeline which builds, tests, pushes a docker image and triggers another job which contains deploy scripts and other resources to deploy the docker image. After deployment, the deploy job triggers an end to end test job and so on.
#### \- Restart or send a deploy event to an existing job

I want to be able to restart an existing drone job from slack chat bot or github bot which watches commit messages.
### Robot account scope of access
- Robot accounts should not have git push, pull or any other github/gitlab/etc access.
- Robot accounts access should be limited to certain drone API calls.
- A robot account access should be limited to a single repository.

**Comment by bradrydzewski** [comment]
> Currently every user in drone has to be a real github, gitlab, bitbucket, etc user. This makes it quite costly and painful to build integrations with drone.

What about creating a robot user in github, gitlab, bitbucket, etc? Right now drone delegates user permissions to these systems, so a robot user in github could effectively be a robot user in drone. 

> To talk to drone API, one must have a valid token to auth to the API. The only way to acquire a token is to login to drone using an existing github/gitlab/etc user.

we do have an endpoint that can convert a github token to a drone token. I believe the user must exist in drone, but I guess in theory that endpoint could register a user if they do not yet exist:
https://github.com/drone/drone/blob/master/server/login.go#L123

> I want to be able to trigger a job restart or deploy event from drone itself. For example, I have a pipeline which builds, tests, pushes a docker image and triggers another job which contains deploy scripts and other resources to deploy the docker image. After deployment, the deploy job triggers an end to end test job and so on.

> I want to be able to restart an existing drone job from slack chat bot or github bot which watches commit messages.

I feel like a github robot user could be created and registered with drone to satisfy these use cases.

> Robot accounts should not have git push, pull or any other github/gitlab/etc access.
> Robot accounts access should be limited to certain drone API calls.
> A robot account access should be limited to a single repository.

I would instead propose creating a robot GitHub account, and drone could provide a way to generate jwt tokens that include scope and repository data to limit what the token can do:

```
{
  "scope": [
    "repo",
    "repo:rw",
    "repo:delete",
    "build",
    "build:rw"
  ],
  "repos": [
    "octocat\/hello-world",
    "octocat\/*"
  ]
}
```

The original jwt implementation (back in drone 0.1) was capable of storing this information in the token but was removed because I just wasn't sure if people actually needed it. We could certainly add it back in.

**Comment by vaijab** [comment]
Using github user as a robot account works in small deployments, where people have a few repos or don't necessarily care about security that much.

In larger deployments, where there are hundreds of different repositories and teams, using github users to talk to drone API can be both very time consuming to set up and most importantly very expensive - $9/user per org.

I don't mind having a real github user and then using drone to generate JWTs with different scopes. Would that be an option?

**Comment by bradrydzewski** [comment]
> I don't mind having a real github user and then using drone to generate JWTs with different scopes. Would that be possible?

yes, I think this would be a good compromise.

you can find the token code here:
https://github.com/drone/drone/blob/master/shared/token/token.go

we could do something like this:

```diff
type Token struct {
	Kind string
	Text string
+	Scope []string // []string { "repo:read", "repo:write", "repo:admin" } ???
+	Repos []string // []string { "drone/drone", "drone/docs" }
}
```

Defining a set of scopes will be a bit of a challenge since I'm not sure how granular we want to get, so perhaps we can split this into phases. The first phase could be to add Repos. If the Repos slice is empty we can assume there are no restrictions. Otherwise if the repos slice is not empty we match the current repo to the contents of the slice.

Once we have this working, we can get an RFC together with some fine-grained scopes. We should be able to solicit community input for this to make sure we have all of our bases covered.

**Comment by vaijab** [comment]
Sounds good to me. @bradrydzewski how would you generate multiple token per user? If the code for that is already there, could you link me to that, so I have a starting point to start thinking? Thanks.

**Comment by ogarcia** [comment]
What about have a token by repository as first approach? It'll have same user permissions but only in designed repository and appear in settings page.

**Comment by Adron** [comment]
@ogarcia I'm sure @vaijab or @bradrydzewski can correct me if I'm off base, but I believe you'd want to set permissions per repo on/in Github vs. on the build server. The permissions there dictate who/where/what can do various things per repo. But I may be off base with that answer, could you elaborate some if that doesn't answer your question?

**Comment by Adron** [comment]
Curious if @vaijab @bradrydzewski or anybody on this thread has pushed this feature forward? I've pondered it and just submitted #2129 which would be a feature that would use this feature for further automation of Drone.io in various environments it needs to be deployed into.

**Comment by bradrydzewski** [comment]
I'm closing this issue (which focuses on robot accounts) since we will not be implementing this feature within drone, and recommend using robot accounts in your version control system (i.e. github)

I have created a separate issue for including scopes in personal tokens at https://github.com/drone/drone/issues/2130
