### ISSUE TITLE
Bitbucket - Invalid redirect_uri error

### ISSUE THREAD

**Issue by duncanleo** [drone/drone#1838]
Hi,

I have not been able to get drone set up with Bitbucket Cloud. I have it configured according to [here](http://readme.drone.io/setup/overview/#advanced-configuration:68f80267fa3a50980dbb745a782b8dca) but it redirects me to the following page when I click 'LOGIN':

<img width="1275" alt="screen shot 2016-10-31 at 11 34 58 pm" src="https://cloud.githubusercontent.com/assets/7417870/19881407/ab1a48c0-9fc2-11e6-8d3b-74b64e5b8935.png">

I did encounter a previous issue on this GitHub tracker with the exact same issue (#1355) but the user configured with `/activate` instead of `/authorize`, which is not the issue here.

- [x] I have searched for existing issues
- [ ] I have discussed the issue with the community at https://gitter.im/drone/drone
- [ ] I have provided a sample `.drone.yml` file to help the team reproduce
- [ ] I have provided details from the build logs
- [ ] I have provided details from the server logs by running `docker logs drone`
- [x] I am not using the issue tracker to ask why my build failed

**Comment by bradrydzewski** [comment]
@duncanleo there are two primary root causes for this behavior. The first is when the `redirect_url` is configured incorrectly in Bitbucket. This could include something as simple as adding an extra backslash or using http instead of https or vice versa. So definitely double-check your configured redirect url.

The second common root cause is when someone uses a reverse proxy and does not correctly configure all the `X-Forwarded-For` AND `X-Forwarded-Proto` header variables. When behind a reverse proxy drone requires these headers to determine its own URL and properly construct the `redirect_url` parameter that it sends to Bitbucket.

Let's move this discussion to our support channel since we reserve the issue tracker for confirmed bugs. Thanks! https://gitter.im/drone/drone

**Comment by duncanleo** [comment]
Hey @bradrydzewski, turns out the reverse proxy was the issue, I was not forwarding some of the headers required. It has now proceeded with the Bitbucket login. Thanks for the prompt response!

**Comment by Shuliyey** [comment]
would selfsigned certificate work in this case?
