### ISSUE TITLE
Agent Authentication fails with: `session failed, retry in 15s`

### ISSUE THREAD

**Issue by jackzampolin** [drone/drone#1850]
Image: `drone/drone:0.5`

Running in Kubernetes, when the `agent` is trying to contact the `server` the session fails with the following errors spamming the logs:

### `server`
```
2016-11-11T01:15:47.724223335Z time="2016-11-11T01:15:47Z" level=info ip=10.48.1.99 latency=100.509715ms method=GET path="/ws/broker" status=200 time="2016-11-11T01:15:47Z" user-agent= 
2016-11-11T01:17:03.264946506Z time="2016-11-11T01:17:03Z" level=info ip=10.48.1.99 latency=100.561948ms method=GET path="/ws/broker" status=200 time="2016-11-11T01:17:03Z" user-agent= 
2016-11-11T01:17:18.397750259Z time="2016-11-11T01:17:18Z" level=info ip=10.48.1.99 latency=100.489715ms method=GET path="/ws/broker" status=200 time="2016-11-11T01:17:18Z" user-agent= 
```

### `agent`
```
2016-11-11T00:33:15.948933953Z 1:M 11 Nov 00:33:15.948 # session failed, retry in 15s. EOF
2016-11-11T00:33:31.052656987Z 1:M 11 Nov 00:33:31.052 # session failed, retry in 15s. EOF
2016-11-11T00:33:46.156707940Z 1:M 11 Nov 00:33:46.156 # session failed, retry in 15s. EOF
```

After checking on the gitter board it sounded like it could be an issue with the LB stripping headers. Checking the source it looks like the error on the `agent` side is coming from [here](https://github.com/drone/drone/blob/master/drone/agent/agent.go#L227). The `server` parses the authentication [here](https://github.com/drone/drone/blob/master/shared/token/token.go#L39).

It looks like the `agent` is setting the `[username](https://github.com/drone/mq/blob/master/stomp/option.go#L13)` header to `x-agent` and the `[password](https://github.com/drone/mq/blob/master/stomp/message.go#L18)` header to `$TOKEN`. 

The `server` appears to not be looking for the `token` in the `Authorization` header.

**Comment by bradrydzewski** [comment]
It is not clear to me there is any issue with Drone here. Keep in mind that multiple individuals are running 0.5 without issue, including at beta.drone.io.

The most common problems I've seen are individuals not correctly setting DRONE_SECRET and individuals having a load balancer in front of drone killing the websocket or preventing the http to websocket upgrade.

There are some individuals that are having problems with Kubernetes, and I'm told some of them have instructed the agents to connect directly to the server IP and bypass the load balancer. If Drone works fine with a direct connection, and even with nginx and other reverse proxies, but not with the k8s load balancer, what conclusion am I to draw here?

> After checking on the gitter board it sounded like it could be an issue with the LB stripping headers. 

This would certainly be a problem. I would recommend reading the load balancer documentation to ensure it is configured to enable websocket upgrades, forwarding headers, etc. If not, a GitHub issue would need to be opened with the load balancer.

> After checking on the gitter board it sounded like it could be an issue with the LB stripping headers. 

this would not be the root cause, because http headers are not used when establishing the broker connection.

> The server appears to not be looking for the token in the Authorization header.

The authentication data is not sent in the http headers. They are sent in the stomp message headers, which are packets sent over the websocket connection once established. See http://mq.drone.io/stomp-protocol/#connect

**Comment by bradrydzewski** [comment]
I've added a `DRONE_BROKER_DEBUG=true` parameter that you can pass to the server that exposes the internal broker logging. This should help expose more details with regards to the connection failure.

One could also run the message broker directly on Kubernetes behind the load balancer to test connectivity issues. The only reason I suggest this is because it might be easier to debug the broker in isolation, without drone. See http://mq.drone.io/server-install/

**Comment by xenji** [comment]
Hey there, I do have something on rancher, that seems to point to the same problem. My server log tells a bit of a different story:

```
11/11/2016 4:56:31 PMpasscode:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZXh0IjoieGVuamkiLCJ0eXBlIjoidXNlciJ9.bSlJ_Zb9mdOujb0Kn8vO5EHKeno9IFqtL5f-WrHJyEM
11/11/2016 4:56:31 PM1:M 11 Nov 15:56:31.033 [33m#[0m stomp: server error. stomp: not authorized
11/11/2016 4:56:31 PM1:M 11 Nov 15:56:31.033 - stomp: successfully closed socket connection.
11/11/2016 4:56:46 PM1:M 11 Nov 15:56:46.035 - stomp: handle websocket request.
11/11/2016 4:56:46 PM1:M 11 Nov 15:56:46.035 - stomp: successfully opened socket connection.
11/11/2016 4:56:46 PM1:M 11 Nov 15:56:46.135 [35m.[0m stomp: received message from client.
11/11/2016 4:56:46 PMSTOMP
11/11/2016 4:56:46 PMaccept-version:1.2
11/11/2016 4:56:46 PMlogin:x-token
11/11/2016 4:56:46 PMpasscode:XXXXXXXXX
11/11/2016 4:56:46 PM1:M 11 Nov 15:56:46.135 [33m#[0m stomp: server error. stomp: not authorized
11/11/2016 4:56:46 PM1:M 11 Nov 15:56:46.135 - stomp: successfully closed socket connection.
11/11/2016 4:57:01 PM1:M 11 Nov 15:57:01.136 - stomp: handle websocket request.
11/11/2016 4:57:01 PM1:M 11 Nov 15:57:01.136 - stomp: successfully opened socket connection.
11/11/2016 4:57:01 PM1:M 11 Nov 15:57:01.237 [35m.[0m stomp: received message from client.
11/11/2016 4:57:01 PMSTOMP
```

I've XXX'ed the passcode, but I checked that it is a 100% match with the one provided by the server. The connection is via docker-compose links, so I would say there is no proxy in between.

The client log looks the same as @jackzampolin's.

**Comment by bradrydzewski** [comment]
@xenji the logs indicate you are not authorized. This happens when you are not providing DRONE_SECRET to the server and agent, or if you are providing, there is a mismatch

**Comment by xenji** [comment]
As said, I can prove that the secret is 100% matching. Took the token from the servers HTML (to be sure not to copy any whitespaces) and added it (as documented) to the DRONE_SECRET env when starting the worker. The token in the logs is exactly what the server "told" me to use.

**Comment by bradrydzewski** [comment]
@xenji something doesn't add up. What are you passing a jwt token as the passcode?

`passcode:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZXh0IjoieGVuamkiLCJ0eXBlIjoidXNlciJ9.bSlJ_Zb9mdOujb0Kn8vO5EHKeno9IFqtL5f-WrHJyEM`

**Comment by bradrydzewski** [comment]
To me it looks like you are using the deprecated agent jwt token from the server logs.

**Comment by bradrydzewski** [comment]
> Took the token from the servers HTML (to be sure not to copy any whitespaces) and added it (as documented) to the DRONE_SECRET

Yea, this token is no longer used, and this is no longer documented. Please see the updated install docs.

**Comment by xenji** [comment]
The image is on both sides the drone/drone:0.5. The token is taken from the web interface of the server. While writing there lines, I feel a bit of shame coming up. I took the user token. 

@jackzampolin Sorry for hijacking your Issue -.-
