### ISSUE TITLE
Re-implement drone agents endpoint

### ISSUE THREAD

**Issue by vaijab** [drone/drone#1867]
I believe currently, drone agent ID are derived from an initial request source IP field when an agent first time connects to the server.

This stops working when drone master is behind a load balancer, because all agents will be reporting the same source IP address.

@bradrydzewski asked to start an issue, so that we can come up with a solution how to solve this problem.

Ideas?

**Comment by bradrydzewski** [comment]
> I believe currently, drone agent ID are derived from an initial request source IP field when an agent first time connects to the server.

this was, but is no longer the case with the new message broker. When I implemented the message broker I never backported the ability to store the agent / ip address in the database.

> This stops working when drone master is behind a load balancer, because all agents will be reporting the same source IP address.

not sure this is true given above

**Comment by vaijab** [comment]
@bradrydzewski oh, that explains it. When I run `drone agents` I see a bunch of outdated drone agents and their IPs.

Does drone master need to know agents' ID/IPs for any reason?

**Comment by bradrydzewski** [comment]
> Does drone master need to know agents' ID/IPs for any reason?

It doesn't _need_ to know this information but ...

There is an open issue with the message broker to provide meta-data endpoints that return a list of all sessions. https://github.com/drone/mq/issues/6

This meta-data endpoint could be used to re-implement the `drone agents` command to get a list of connected agents, their architectures, etc.

**Comment by bradrydzewski** [comment]
would it be appropriate to re-name this to `Re-implement drone agents endpoint`?

**Comment by vaijab** [comment]
> would it be appropriate to re-name this to Re-implement drone agents endpoint?

Please do.

**Comment by bradrydzewski** [comment]
I'm going to close this because at this time I do not plan to implement agent tracking within drone. Instead I recommend the following:

* label your drone agent servers (in aws, gcp, etc)
* use your cloud provider api to fetch a list of labeled agent servers

If you want to check health, the agents now implement the `/healthz` endpoint and also implement the docker `healthcheck` directive.

There was a related issue with more discussion:
* https://github.com/drone/drone-ui/issues/107#issuecomment-324790277
* https://github.com/drone/drone-ui/issues/107#issuecomment-324791725
