### ISSUE TITLE
0.5: Logged-out users can view builds

### ISSUE THREAD

**Issue by STRML** [drone/drone#1871]
If you copy-paste an exact url into an incognito window, even with `DRONE_OPEN=false`, the entire history of that build and log output is visible to that anonymous user.

This is running latest 0.5.

**Comment by bradrydzewski** [comment]
DRONE_OPEN=false does not impact the visibility of a repository. If registration is open, anyone can create an account and login. If registration is closed, accounts can only be created by the administrator. You can read more at http://readme.drone.io/0.5/install/authorization/

The repository and build history are always visible if your repository is public. If your repository is private it is not publicly visible [1]. I confirmed this behavior by viewing on of my private test repositories in an incognito window, just to be sure there was no security regression.

![screen shot 2016-11-24 at 10 09 38 pm](https://cloud.githubusercontent.com/assets/817538/20609926/ebcba93a-b292-11e6-8193-7089467580ab.png)

[1] the only notable exception is if the repository was added to drone when it was public, but then was switched to private. there is an open issue to update the public / private status, but it is not implemented yet since it is still sort of an edge case.

**Comment by STRML** [comment]
Thanks for the clarification. It is difficult to verify what the intended behavior is while the 0.5 release is pending and docs are in flux.

**Comment by bradrydzewski** [comment]
@STRML yep, sorry for the confusion ... working to finalize the release and clean up the documentation to make things more clear

**Comment by STRML** [comment]
No worries, thanks for all the great work so far!
