### ISSUE TITLE
Polling remote?

### ISSUE THREAD

**Issue by ooxi** [drone/drone#1882]
What would be the correct way to implement a polling remote? We are using a git repository served by `git-http-backend` and do not currently plan on moving to a supported remote like GitHub or gogs. 

Therefore I'm wondering how to integrate gogs with our repository. Is there any documentation on how to communicate with drone.io remote setup e.g. via `post-receive` hooks?

**Comment by bradrydzewski** [comment]
`git-http-backend` is not something Drone can support. Drone does not have built-in user management, permission management, or logins and instead delegates this to GitHub (or Bitbucket, etc).

**Comment by ooxi** [comment]
But drone does use `.netrc` for communicating with private repositories, which is essentially the same as repositories served by `git-http-backend` with http basic authentication.

Nevertheless I'm not interested in all the account management features, I simply want drone to recognize a changed public repository and build it :)

If a remote is not the right way to implement this, what would be necessary to tell drone *go fetch that repository and build it according to the contained `.drone.yml`*?

**Comment by vaijab** [comment]
@ooxi in that case, you could potentially hack something up with `drone exec`.

**Comment by bradrydzewski** [comment]
@ooxi you can see everything required to implement a drone remote backend here:
https://github.com/drone/drone/blob/master/remote/remote.go

You will see that drone relies on the remote backend to handle authentication, permissions, etc. So that would all need to be somehow simulated to work with a plain old git http server.

Also note that drone only works with post-commit hooks for launching builds. It is not possible to poll a repository.
