### ISSUE TITLE
Enable drone integration on new repositories by default

### ISSUE THREAD

**Issue by mrueg** [drone/drone#1916]
Right now it seems like you need to enable the drone integration on each repository yourself.
It would be nice if there were a global setting to enable them by default.

**Comment by jmccann** [comment]
I like this idea ... because it's something gitlab offers "out of the box" that a lot of people seem to like.  Start a repo and just be ready to do some CI/CD without anymore work.

> Note: Starting from version 8.0, GitLab Continuous Integration (CI) is fully integrated into GitLab itself and is enabled by default on all projects.

https://docs.gitlab.com/ce/ci/quick_start/

**Comment by bradrydzewski** [comment]
> Note: Starting from version 8.0, GitLab Continuous Integration (CI) is fully integrated into GitLab itself and is enabled by default on all projects.

This is probably a bit easier for Gitlab because they own the whole stack. Consider some of the following advantages they have, that Drone does not:

a. knows when a repository is created
b. doesn't have to request permissions
c. doesn't have to create hooks (knows when it is updated)
d. infers whether or not a build should run based on existence of a yaml file

> It would be nice if there were a global setting to enable them by default.

The policy is that these sort of features need to be prototyped external to Drone to flush out features, functionality and technical challenges. It also gives us the ability to gauge demand for integrating a feature in Drone core, or if it should remain an external utility.

I would therefore recommend creating a simple program that polls the Drone server for new (inactive) repositories and then activates them. This could run as a daemon or schedule with cron:

```
client := client.NewClientToken(...)
repos, err := client.RepoList()
...
for _, repo := range repos {
  if repo.ID == 0 {
    client.RepoPost(repo.Owner, repo.Name)
  }
}
```

I am planning to add a Project section in the documentation for external tools and project (such as Drone UI) which could include this sort of tool. This would allow the Drone community to discover the tool, install, and provide feedback.

Let's re-open this issue once an external tool exists and we have some initial feedback to determine next steps.

**Comment by bradrydzewski** [comment]
adding a note that @donny-dont would want this utility to automatically add the .drone.yml, or perhaps automatically send a pull request with a .drone.yml, upon activation.

I'm sure there are all sorts of cool things that can be prototyped here ...

**Comment by rverma-nikiai** [comment]
@bradrydzewski Is this got picked in any release?

**Comment by bradrydzewski** [comment]
nope, there are no plans to build these capabilities directly into Drone. There are, however, community-driven projects solving this externally to Drone. For example if you are using Terraform there is Drone provider https://github.com/artisanofcode/terraform-provider-drone

**Comment by HuxyUK** [comment]
is there a way to register a repository with the drone API? I was thinking of using a GitHub web hook to try and auto-register new repositories. I have 80+ students and manually adding them one at a time is not practical for me.

**Comment by antonin07130** [comment]
> is there a way to register a repository with the drone API? I was thinking of using a GitHub web hook to try and auto-register new repositories. I have 80+ students and manually adding them one at a time is not practical for me.

Seems like there is but I am testing it with no success so far :

```golang
	// get all repos 
	repos, _ := client.RepoList()

	for _, repo := range repos {
		    // RepoEnable activates a repository.
			enabled, _ := client.RepoEnable(repo.Namespace, repo.Name)
                        fmt.Printf("enabled repo : %s/%s\n", enabled.Namespace, enabled.Name)
	}
```

**Comment by rickardrosen** [comment]
The `RepoEnable` requires a sync to have taken place from what I gather.

Add a repo by webhook would be a nice feature, or if the `List` method on `RepositoryService` interface could take a named input it would allow to sync/list specific repo(s).
This requires changing all implementations I guess.
