### ISSUE TITLE
Cyrillic is not displayed

### ISSUE THREAD

**Issue by andruwa13** [drone/drone#1975]
![commits master webakcent mysql-backup gitlab 2017-03-21 17-31-13](https://cloud.githubusercontent.com/assets/5846351/24155405/675a045a-0e5c-11e7-8000-03aff61ea86e.png)
![webakcent mysql-backup drone 2017-03-21 17-30-31](https://cloud.githubusercontent.com/assets/5846351/24155415/6dc5b7da-0e5c-11e7-8fce-72cc83c010e4.png)
drone version 5.0

**Comment by bradrydzewski** [comment]
can you confirm you database is using the correct character set? Drone does not choose a character set for your database, which means this is something you need to configure at the database level.

**Comment by bradrydzewski** [comment]
Also, let's move this discussion to our community support at https://gitter.im/drone/drone. Per the issue template [1] we ask that all issues are triaged using community support so that we can reserve the issue tracker for known bugs.

If we determine there is bug with Drone we can re-open

[1] https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md

**Comment by andruwa13** [comment]
Database = **mariadb** tables=**utf8_general_ci**
On gitter they do not answer me

**Comment by bradrydzewski** [comment]
and did you confirm that, in the database, the values are being persisted correctly?

**Comment by andruwa13** [comment]
how to do it?

**Comment by bradrydzewski** [comment]
mysql (and presumably mariadb) have tools you can download to inspect your database and database records. You can also use command line tools.

Note that I just pushed a commit with cyrillic characters in the commit message and they render properly. This leads me to believe it is a database configuration issue.

![screen shot 2017-03-22 at 1 01 40 am](https://cloud.githubusercontent.com/assets/817538/24159855/41193a7e-0e9b-11e7-824a-a0203822ea0c.png)

**Comment by andruwa13** [comment]
SQLite database **work** 
  
![3_1_3_u nginx-php7-exim drone 2017-03-21 20-49-32](https://cloud.githubusercontent.com/assets/5846351/24165074/2e0127da-0e78-11e7-970a-690275456466.png)
mysql (mariadb) not work :(

**Comment by bradrydzewski** [comment]
If mysql does not work, it is because either your database is not setup correctly, or perhaps you need to modify your connection string for the desired character set https://github.com/go-sql-driver/mysql#dsn-data-source-name.

Perhaps @floatdrop or @Bugagazavr or @vtolstov can provide some insight into correct database and connection string configurations for non-latin character sets?

**Comment by Bugagazavr** [comment]
I use postgres, and has no problems
