### ISSUE TITLE
an API to enable elastic agents

### ISSUE THREAD

**Issue by fommil** [drone/drone#1989]
(I want to write this down now instead of waiting for a full day's TZ lag, so I hope this meets the criteria for creating tickets. If it's ok with you, can we perhaps use this as a place to discuss API requirements. And in my defence, I closed two stale tickets :smile:)

I'm in the process of writing https://github.com/fommil/drone-dynamic-agents as discussed on the gitter channel, to automatically scale the agents with Google Containers or AWS.

The build endpoint http://readme.drone.io/api/build-endpoint/ is sadly lacking some features that I require:

- [x] it is not possible to see a list of all builds across all users / projects (although @jmccann [says otherwise](https://gitter.im/drone/drone?at=58dd74f201d449152eb4be7b))
- [ ] it is not possible to see a list of registered agents (it would be great if an envvar on the agent could be used as a name that appears here)
- [ ] it is not possible to see which agent any given build has been assigned to

and for better control over shutdowns:

- [ ] it is not possible to disconnect / stop an agent (this would be useful to tell an agent not to accept any more work, for a clean shutdown of the machine)
- [ ] (to workaround non-clean shutdowns) it is not possible to see when a job failed because the agent died. It would be good if jobs like this could be automatically rescheduled a finite number of times.

**Comment by jmccann** [comment]
Since I saw my name ... I think the endpoint to get all builds is `/api/builds` as defined in https://github.com/drone/drone/blob/master/router/router.go#L163-L167

Also, `drone build queue` gives that.

**Comment by bradrydzewski** [comment]
Thanks, adding some thoughts

When 0.6 is released it will include an `/api/info/queue` endpoint that provides some information about the work queue:

```
{
    "pending": [ ... ],
    "running":[ ... ],
    "stats": {
        "worker_count": 1,
        "pending_count": 0,
        "running_count": 0,
        "completed_count": 0
    }
}
```

You will be able to see the number of pending builds (`pending_count`) and running builds (`running_count`_, as well as the number of idle workers (worker_count) waiting for builds.

> it is not possible to see which agent any given build has been assigned to

I've added the field for this in the database which is the first step but could definitely use feedback here. What value should we store here? IP address of the agent? Should the agent send its hostname to Drone and we store that? Should you be able to give the agent a name (ie `docker run drone/drone agent --name=....`)?

> it is not possible to see a list of registered agents

For this, I would recommend using the aws or gcp api. If you use a naming convention for your agent instances, you can fetch the list of instances and filter on the ones matching the naming convention. The risk with storing this in Drone is that we can end up with stale / out of sync data. So I think fetching the data from its source is probably the best option.

> it is not possible to see when a job failed because the agent died. It would be good if jobs like this could be automatically rescheduled a finite number of times.

This will be handled automatically when 0.6 is released. The agents implement per-build heartbeats and if the server does not hear from an agent within a designated time period it will re-queue the build. This will definitely need a good amount of real world testing but I think we'll have this one covered :)

> it is not possible to disconnect / stop an agent

If you send a SIGINT to the agent it will stop accepting new builds, will finish remaining builds, and then shutdown. So if you want to shutdown an agent you can ssh into the machine and send the signal using the docker client, or if you would prefer to use rest, you could use the docker remote api.

**Comment by fommil** [comment]
Cool. There are a few constraints though: there are agents that are not managed by aws/google so although I can use their api I cannot see their status as drone agents.

We cannot assume we can independently communicate with agents. Unless it goes via the server we can't do things like KILL signals.

A name sounds good. Although it would be really useful for the agents to reverse lookup their IP too, as meta info.

**Comment by fommil** [comment]
Btw, the info queue sounds like all I need for now! :-) has that been implemented yet v?

**Comment by Spedge** [comment]
> If you send a SIGINT to the agent it will stop accepting new builds, will finish remaining builds, and then shutdown. So if you want to shutdown an agent you can ssh into the machine and send the signal using the docker client, or if you would prefer to use rest, you could use the docker remote api.

@bradrydzewski - Is this true for 0.4 agents as well?

**Comment by bradrydzewski** [comment]
@Spedge sorry, you'll need 0.5 (or preferably 0.6) for this

**Comment by bradrydzewski** [comment]
I am going to close this because I believe all the pieces are in place for auto-scaling

> it is not possible to see a list of all builds across all users / projects

you can use `/api/info/queue` to see queue backlog

> it is not possible to see a list of registered agents

this is out of scope for drone. Instead you should tag / label your agent servers in your hosting service (eg AWS). You can then get a list of servers matching the label using the AWS API.

> it is not possible to see which agent any given build has been assigned to and for better control over shutdowns

agents expose an `/varz` endpoint which can be used to get a list of running builds

> it is not possible to disconnect / stop an agent

you can connect to the server (using the AWS API or SSH) and execute `docker stop -t 3600 agent`

> it is not possible to see when a job failed because the agent died. 

the agent now exposes a `/healthz` endpoint which tells you if the agent is in a bad state

> It would be good if jobs like this could be automatically rescheduled a finite number of times.

the agent has a lease on each job, which it renews every N seconds. If the agent allows the lease to expire the job is re-scheduled.

**Comment by fommil** [comment]
Cool, thanks for this. I am still writing this app, agreed it has turned into an educational aid rather than needing the app.

However I disagree with your assertion that tagging belongs in aws... our drone server is mostly populated by contributor's agents, the gce agents are a base load. Without the ability to list agents and see metadata about agents from the server, there are many places where the business logic is blind to make better decisions.

Which version should I be using?

**Comment by bradrydzewski** [comment]
> You may be interested in my perspectives as a free software maintainer

This is really a phenomenal write up. Congrats on getting ENSIME to where it is today, and I hope enjoy having a bit more free time to pursue new and exciting things :)

> Which version should I be using?

0.8.1 using the upgrade instructions at http://docs.drone.io/release-0.8.0

> However I disagree with your assertion that tagging belongs in aws
> I don't think connecting to agents is feasible in our case, as agents typically will not have public ip addresses.

I do believe that most teams and organizations will be able to use the server tags and the aws/gcp endpoints to retrieve this data, since they do not operate under the same constraints (donated servers, no direct network access).

I understand this does not meet your specific needs, however, tracking agents is not something I plan to implement within drone server. Sorry :(

I believe the industry, and as a result this project, is moving toward a model where you can launch containers on-demand without concerning yourself with servers or infrastructure. See [azure container service](https://azure.microsoft.com/en-us/services/container-service/) and [hyper](https://hyper.sh) and to some extent [kubernetes tasks](https://kubernetes.io/docs/tasks/). I believe these will eventually obsolete our agents.

**Comment by fommil** [comment]
Have you had a look at the gitlab runner CI? It's pretty cool, although the yaml don't allow for some of the simpler setups that drone handles.

**Comment by bradrydzewski** [comment]
nope, but I'm pretty heavily invested in the drone runner. It is badass. It works like a compiler. It has frontends (drone yaml, bitbucket yaml, gitlab yaml) and backends (docker, kubernetes, hyper ...). This makes it quite flexible and supports the vision I have to natively integrate with multiple on-demand container solutions. It also means you can use gitlab yaml files with drone, should you ever decide you want to migrate away from gitlab :)

**Comment by fommil** [comment]
Awesome! I didn't realise it was this omnipotent
