### ISSUE TITLE
Pending build with no error when invalid .drone.yml syntax

### ISSUE THREAD

**Issue by jmccann** [drone/drone#2018]
I tried using Drone 0.6 rc with a  `.drone.yml` for 0.4.  The build sat in "pending" with no visible errors.

I chatted with @bradrydzewski about this in Gitter and he asked me to open an issue.

**Comment by bradrydzewski** [comment]
Yes, an empty or missing pipeline block should fail the linter, which should fail the build. My guess is that the failure status is not correctly being persisted to the database, but I'll have to verify. Thanks for the report :)

**Comment by tonglil** [comment]
I can definitely second this as an issue. Not sure about why, but I am not in a rush about this. The only "bummer" is that there are no controls to cancel this build in the UI.

<img width="1561" alt="screen shot 2017-05-03 at 2 00 09 pm" src="https://cloud.githubusercontent.com/assets/3250776/25674459/e25f59de-3008-11e7-8c7e-f20d75ed1550.png">

**Comment by bradrydzewski** [comment]
fixed with 1 character 😄 

```diff
if lerr != nil {
-	return nil, err
+	return nil, lerr
}
```

**Comment by aPoCoMiLogin** [comment]
Faced almost same issue but with 0.5 version. It was almost same, cause I didn't change my `.drone.yml` file for weeks now, but there was log in drone-server:

```level=error msg="Unable to read logs from broker. Timeout. %!s(<nil>)" ```

Trying to stop that build because every next build was queued was'nt possible via CLI:

```$ drone build stop org/repo 89
-> client error 400: Cannot cancel a non-running build```

Restarting server marked all queued builds as failed.

As a side note: CLI in `drone build` section needs some explanation, cause there is no info about arguments order or which arguments are needed. It just fails with:

```$ drone build logs org/repo
-> strconv.Atoi: parsing "": invalid syntax```
