### ISSUE TITLE
GitLab cannot authenticate user. Error exchanging token. Post http://localhost:10080/oauth/token: dial tcp 127.0.0.1:10080: getsockopt: connection refused

### ISSUE THREAD

**Issue by kenken64** [drone/drone#2027]
cannot authenticate user. Error exchanging token. Post http://localhost:10080/oauth/token: dial tcp 127.0.0.1:10080: getsockopt: connection refused

**Comment by bradrydzewski** [comment]
You cannot use localhost to reach an external service (gitlab) because localhost refers to the network inside the drone container.

Per our github issue template, please consult the mailing list before creating issues. Thanks!

> Bugs or Issues? Please do not open a GitHub issue until you have
discussed and verified on the mailing list: https://gitter.im/drome/drome
