### ISSUE TITLE
`printenv` prints the secrets in plaintext

### ISSUE THREAD

**Issue by ptagr** [drone/drone#2107]
Drone version : `0.7.3`
**Reproduce**: Run `printenv` in a drone step
**Actual**: global secrets are printed with their values in plaintext
**Expected**: global secrets are printed with the values concealed (*)

**Comment by jamrizzi** [comment]
How else do you expect services to read the secrets???

**Comment by donny-dont** [comment]
In 0.5 there was a conceal option for secrets. This was expensive to do and didn't handle multi line secrets.

**Comment by tboerger** [comment]
Please follow the issue template, the tracker should be used for confirmed issues, not just for something you just expect.

If you are using global secrets instead of secrets scoped to specific plugins it's up to you to keep the secrets hidden, in that case you can enable gating and just decline a pull request that tries to print the secrets.

**Comment by tonglil** [comment]
Can I suggest a FR that could help with certain cases of this issue?

Extend secrets with an optional field to specify exactly which plugin(s) can access the secret, otherwise it will not populate that container with that env var.

So for example, if you are publishing an image to Docker, the only place you need that secret is in `plugins/docker` and no where else. So when adding the secret, you add a list of plugins that will _can_ get the secret: `only=plugins/docker only=plugins/gcr:0.5 (if it needs it as well)`.

Then the build steps will not even have these secrets injected into the environment, providing a bit more granularity in controlling the secrets.

At the small scale, this allows pipeline/repo admins to add appropriate secrets knowing that only the appropriate plugins can use them and changes to `.drone.yml` won't explose "these" secrets (it can still explose .netrc for example).

On the org-scale level, global secrets could be injected by Drone operators (who may not be repo owners) for users to use with certain plugins (and versions), and rotate them out if need be all at once, while being able to "not trust" individual `.drone.yml` pipeline changes. For example, this could be a secret for publishing to a shared GCR bucket, or a Slack token for a pre-configured org Slack integration to send build notifications (so team's don't have to create their own Slack integration + more tokens).

Let me know if any part of that doesn't make sense, happy to clarify.

**Comment by tonglil** [comment]
UI could look something like this:
![image](https://user-images.githubusercontent.com/3250776/28835849-d29f8a9e-76b4-11e7-90dc-c1ea8bbcf28b.png)

**Comment by tonglil** [comment]
After looking at the docs' CLI section, I see this is already implemented 😆

**Comment by tonglil** [comment]
I guess if Global Secrets' yml config got updated, this could be considered done?

```yml
- name: docker_username
  value: octocat
  image:
    - plugins/docker
- name: docker_password
  value: correct-horse-batter-staple
  image:
    - plugins/docker
```

**Comment by bradrydzewski** [comment]
@tonglil this is already possible from the command line and the global secrets file :)

Example when configuring a secret from the command line:

```diff
drone secret add \
  -repository octocat/hello-world \
+ -image plugins/docker \
  -name docker_username \
  -value <value>
```

This is also supported in the global secrets file, although not currently documented:

```diff
- name: docker_password
  value: correct-horse-battery-staple
  repos: [ octocat/hello-world, github/* ]
+ images: [ plugins/docker ]
```

**Comment by tonglil** [comment]
Awesome, looks like I am making a PR to the docs this week!

Tony Li

**Comment by bradrydzewski** [comment]
the ability to conceal secrets was re-implemented to work with the new drone-runtime package, and will be re-introduced in 0.9
