### ISSUE TITLE
Ability to use default bridge for pipeline network

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#2132]
We should give the ability to use the default `bridge` network.  With 0.6 we started creating a new bridge network for each build (similar to docker-compose) however this appears to be problematic for some setups that use custom network drivers.

**Comment by bradrydzewski** [comment]
note that this specifically seems to impact the docker plugin and running dind. I have documented a workaround in the following thread:
https://stackoverflow.com/questions/45306699/how-to-use-custom-dns-settings-in-drone-docker-plugin

**Comment by bradrydzewski** [comment]
closing because network aliases cannot be used with the default bridge network

**Comment by anitgandhi** [comment]
In my opinion this would still be nice to have for the situation where you don't really care about using Drone/Docker-compose services, rather just a simple build-test-push pipeline of independent stages. 

Personally my use case is that I'm running drone/server and drone/agent on a Kubernetes cluster (closely following this https://github.com/appleboy/drone-on-kubernetes) and unless I use the `network_mode: host` + trusted repo workaround, every pipeline step will fail since it's not using the functional default Docker daemon bridge network. 

Maybe a bit of a niche use case 🤷‍♂️

**Comment by bradrydzewski** [comment]
have you tried https://github.com/kubernetes/charts/tree/master/incubator/drone ?  You should not need to use `network_most: host`. The helm chart runs a dind container in the same pod as the agent, which prevents the agent from using the host machine docker daemon. For many, it seems to also resolve network issues. For others, they have had to update IP tables

**Comment by anitgandhi** [comment]
Ah that's unfortunate. I'll take a look at the links and try some things. If I get it working consistently without `network_mode: host`, I'll be sure to share back here 😄

**Comment by anitgandhi** [comment]
I was able to use `network_mode: bridge` to explicitly force it to use the Docker engine's bridge (which I had set to use kubelet's `cni0` interface). As before, "Trusted" repo is required.

The dind option would have worked, I just personally felt like that wasn't the right move for my use. 

Thanks @bradrydzewski for the assist!

I think the k8s use-case encompasses more things like not being reliant on the Docker runtime as well so it's clearly a larger scope feature to tackle. I see some stub code in the cncd/pipline repo for it as well 👍
