### ISSUE TITLE
Community ownership of drone-plugins organization

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#2166]
The goal is to transition the [drone plugins](https://github.com/drone-plugins) organization to community ownership. This thread will track progress and todos.

- [ ] document process for submitting a new plugin 
- [ ] document requirements for community owned plugins (technical, license, docs, etc)
- [ ] setup github teams and permissions to drone-plugins organization
- [ ] setup dockerhub permissions to plugins organizations

cc @tboerger

**Comment by tboerger** [comment]
Maybe we want to manage the permissions via https://www.terraform.io/docs/providers/github/index.html? :) Always visible and updatable via pull request. Maybe we can write a micro application that can create the GitHub repo after approval by a maintainer, than you aren't always involved to get it rolling. I think the Docker permissions will be controlled via org secrets or not? Below is a list of the current ownership (I have listed the repos I've got access to and the ones I can't manage because I'm not an admin over there).

## List of plugins controlled by Drone Inc.

* cache
* coverage
* docker
* gcr
* git
* gitter
* s3
* slack
* volume-cache

## List of plugins controlled by community

* anynines
* azure-storage
* azure-web-apps
* bintray
* bitballoon
* cloudcontrol
* codedeploy
* containership
* deis
* devpi
* dockerhub
* downstream
* ecr
* gh-pages
* github-release
* google-cloudstorage
* heroku
* hg
* irc
* marathon
* npm
* nuget
* opsworks
* pushover
* pypi
* rsync
* s3-cache
* s3-sync
* scalingo
* sftp
* slack-blame
* tutum
* webhook

**Comment by bradrydzewski** [comment]
This is a brain dump of thoughts on guidelines for community maintained plugins:

* must be based on the [plugin starter](https://github.com/drone/drone-plugin-starter)
* must be written in Go and use the plugin starter libraries
* must vendor dependencies
* should support amd64, arm, arm64 and windows
* should avoid CGO so we can cross-compile multi-arch on amd64
* should avoid OS dependencies or static linking so we can cross-compile multi-arch on amd64
* should use the [ca-certs-base-image](https://github.com/CenturyLinkLabs/ca-certs-base-image) so we can cross-compile multi-arch on amd64
* published to dockerhub

__Plugins of certain types must use the following libraries__

* cache plugins must use the [drone-cache-lib](https://github.com/drone/drone-cache-lib) and use standard conventions
* notification plugins must use the [drone-notification-lib](https://github.com/drone/drone-notification-lib) (coming soon) and use standard conventions

__Plugins should not__

* require mounting volumes, unless absolutely necessary
* require privileged mode, unless absolutely necessary
* execute untrusted code (i.e. there should never be a `go test` plugin)
* wrap a single command (i.e. we don't need a curl plugin, an npm install plugin, etc)
* contain logic specific to a single business or team's process. Example slack-blame plugin assumes the user email maps directly to the slack username (works for Sony, but not others)

__We should require__

* Plugins should be published to dockerhub and used in production before proposing they are added to the plugin organization
* Plugins should be useful to more than just one person or team. For example don't ask to donate a plugin to the community organization because you want to offload maintenance. I think we should implement voting (via github emotions) and require a minimum of N thumbs up. This indicates demand for the plugin.

**Comment by mrueg** [comment]
> * should use the ca-certs-base-image so we can cross-compile multi-arch on amd64
I wonder if it makes sense to tag it as plugins/drone-base-image and use that. So you are independent from upstream decisions and can change the base image if necessary.

**Comment by bradrydzewski** [comment]
> I wonder if it makes sense to tag it as plugins/drone-base-image and use that. So you are independent from upstream decisions and can change the base image if necessary.

agreed. I have been planning on creating a `drone/scratch` image

**Comment by tboerger** [comment]
That won't work with real scratch images since many plugins need system packages like git, aws-cli etc pp. But based on alpine we can already cover most important architectures. Maybe drone can get a sponsor for vms with the correct architecture? Or launch vms on our own to build it natively?

**Comment by bradrydzewski** [comment]
It is true that we cannot always use the scratch image, but in many cases we can use pure Go alternatives to system packages, for example:

* https://github.com/src-d/go-git
* https://github.com/aws/aws-sdk-go

The benefit of using scratch vs alpine is that we can easily build and publish armhf/ aarch64 / windows images on our amd64 agents. This simplifies our build infrastructure and results in smaller images.

**Comment by donny-dont** [comment]
@bradrydzewski that issue you noted with slack-blame was resolved with https://github.com/drone-plugins/drone-slack-blame/blob/master/main.go#L31-L35

I would probably argue that something like slack-blame is a better base for a notification library since it's a lot more robust than drone-slack but you're the boss.

Also I would argue that windows/arm should be supported on anything in drone-plugins.

**Comment by bradrydzewski** [comment]
@donny-dont yes, sorry, I was searching for an example and that was the first that came to mind. Sorry if it came off as a criticism. Glad to hear it was fixed :)

We should be able to support windows arm as well

**Comment by thomasf** [comment]
After having worked on a https://github.com/thomasf/drone-plugins-go for a while I think I can pretty safely say that the plugin starter kit is a bad idea and not good enough. There should be a simple to use package which does under the hood like formatting argument errors in a drone.yml like way.

**Comment by thomasf** [comment]
I personally feel that the the golang/dep tool is ready enough to be the recommended way to manage vendor/ at this point.. I have began the journey of migration from various other tools the recent months and have not yet come across any problems in doing so.

**Comment by thomasf** [comment]
## must be written in Go...

The "must be written in Go" part should be demoted from a "must" to a "should",
there are so many language specific tools which just aren't feasible maintaining
Go ports of just for drone.

I might be misundestanding this requirement though. If
https://github.com/drone-plugins/drone-npm is considered to be following the
rule even though it is using nodejs it's all good, the requirement text just
need to clarify that it is ok to combine the usage of Go with tools written in
other languages.

**Comment by thomasf** [comment]
## require a test suite

It should always be a requirement that any community driven projects have
quality test suites with good test coverage. Among other things it will be much
easier to accept changes that way.

**Comment by bradrydzewski** [comment]
> I personally feel that the the golang/dep tool is ready enough to be the
recommended way to manage vendor/ at this point

`dep` is great and I am using is for a number of packages and projects with simple dependency graphs. For projects with larger dependency graphs where the vendor file is committed the repository I am waiting for pruning https://github.com/golang/dep/issues/944.

> The "must be written in Go" part should be demoted from a "must" to a "should",
there are so many language specific tools which just aren't feasible maintaining
Go ports of just for drone.

I think the plugin must be written in Go. The example of the NPM plugin is taking this too literally. The npm plugin is written in Go and then uses `os.Exec` to invoke a well-known third party program. The git plugin uses `os.Exec` to invoke a well-known third party program.

There may be exceptions to this rule. We will evaluate such exceptions individually as they are encountered.

> After having worked on a https://github.com/thomasf/drone-plugins-go for a while I think I can pretty safely say that the plugin starter kit is a bad idea and not good enough.

I respectfully disagree. Every developer has their personal preference, and I am quite happy with the current starter kit. I am not looking to make structural changes at this time.

**Comment by thomasf** [comment]
### Go requirement

I fully agree with what you say.


### requiring a good test suite

you didn't reply to this one but as a maintainer I find it totally insane not
requiring a test suite. It's a huge maintainer burden potential not requiring
it.

### About a drone plugins package.

The interface I'm experimenting with isn't the important thing to concentrate
the discussion around. For the sake of a discussion you can just imagine that
exposes exactly the same interface as `urfave/cli` with some additional
features. I'm not particularly fond of the style that the standard library uses
either but I chose to model the package as closely as possible to the stdlib
anyway for reason of familiarly rather than my personal taste.
 
The motivation is about having a high quality, reusable package which can do a
lot of stuff that packages not intended for writing drone plugins never will
provide.

Apparently you found that the ~30LOC of `drone/signal` was worth having as a
reusable package and I can guarantee that there is a lot more valuable
reusable code which can be created for writing plugins.


*Example case of code which should have been reused*

There are various implementations of MapFlag in multiple plugins and none of
them have tests or documentation strings.

All implementations them lacks both documentation and tests from what I can tell.

The implementation in drone-s3-sync even seems to have a bugs it should
probably not ignore parsing errors with a `*`. Even though it's an edge case
it's still a bug and maybe more importantly it can potentially cause different
interface towards the end user depending on which plugin the user is using.

```go
// drone-git: will fail setting the flag if given bad input
func (m *MapFlag) Set(value string) error {
	m.parts = map[string]string{}
	return json.Unmarshal([]byte(value), &m.parts)
}

// drone-s3-sync: will not fail on bad input, will instead blindly replace the value
func (s *StringMapFlag) Set(value string) error {
	s.parts = map[string]string{}
	err := json.Unmarshal([]byte(value), &s.parts)
	if err != nil {
		s.parts["*"] = value
	}
	return nil
}
```

*/*


*usage/flag errors*

When not given any input the `drone-s3-sync` plugin just prints:

`Must set access_key, secret_key, and bucket` which is uninformative, it doesn't 
even tell which option the user failed to set.

It's still nowhere complete but my plugins package would print something
similar to this if parsing fails which is much more understandable from a
plugins user context and the formatting isn't something which the plugin writer
has to be concerned with at all:

```
PLUGIN_FORK=12 DRONE=true go run main.go  
plugin usage:

option:                       env_file
usage:                        source env file

option:                       fork
usage:                        Trigger a new build for a repository
failed to parse value:        fork
current value:                false
error:                        strconv.ParseBool: parsing "12": invalid syntax

option:                       repositories
usage:                        List of repositories to trigger

option:                       server or as env var downstream_server
usage:                        Trigger a drone build on a custom server

option:                       token or as env var downstream_token
usage:                        Drone API token from your user settings

exit status 1

```

The only usage output from most drone plugins are in this form that doesn't
make much sense in a drone end user perspective:

```
NAME:
   s3 sync plugin - s3 sync plugin

USAGE:
   aws [global options] command [command options] [arguments...]
   
VERSION:
   1.1.0+0
   
COMMANDS:
     help, h  Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --access-key value               aws access key [$PLUGIN_ACCESS_KEY, $AWS_ACCESS_KEY_ID]
   --secret-key value               aws secret key [$PLUGIN_SECRET_KEY, $AWS_SECRET_ACCESS_KEY]
   --bucket value                   name of bucket [$PLUGIN_BUCKET]
   --region value                   aws region (default: "us-east-1") [$PLUGIN_REGION]
   --source value                   upload source path (default: ".") [$PLUGIN_SOURCE]
   --target value                   target path (default: "/") [$PLUGIN_TARGET]
   --delete                         delete locally removed files from the target [$PLUGIN_DELETE]
   --access value                   access control settings [$PLUGIN_ACCESS, $PLUGIN_ACL]
   --content-type value             content-type settings for uploads [$PLUGIN_CONTENT_TYPE]
   --content-encoding value         content-encoding settings for uploads [$PLUGIN_CONTENT_ENCODING]
   --cache-control value            cache-control settings for uploads [$PLUGIN_CACHE_CONTROL]
   --metadata value                 additional metadata for uploads [$PLUGIN_METADATA]
   --redirects value                redirects to create [$PLUGIN_REDIRECTS]
   --cloudfront-distribution value  id of cloudfront distribution to invalidate [$PLUGIN_CLOUDFRONT_DISTRIBUTION]
   --dry-run                        dry run disables api calls [$DRY_RUN, $PLUGIN_DRY_RUN]
   --env-file value                 source env file
   --help, -h                       show help
   --version, -v                    print the version
```

**Comment by bradrydzewski** [comment]
> you didn't reply to this one but as a maintainer I find it totally insane not requiring a test suite. It's a huge maintainer burden potential not requiring it.

Are you implying I am insane? I did not intentionally ignore this. There was a lot to reply to, and I simply forgot to reply to this point. Yes, I agree we should have solid testing.

> About a drone plugins package.

This is not something I am interested in sponsoring at this time.

**Comment by thomasf** [comment]
I did not mean to imply that you are insane. I Said that it's insane to not
require a test suite but what I really meant is that not having tests as a
maintainer or contributor of a project can be a large time sink which might not
cause insanity but very much increase the risk of burn out.

I don't understand the significance of you sponsoring a package or not, do you
sponsor `urfave/cli`?

From what understand what you have said earlier you won't be a part of
maintaining the `github.com/drone-plugins` code. This means that the burden of
having to maintain repeated code over a growing list of ~40 plugins onto the
Comminity but you still want to decide that the community can't make their job
easier by requiring use of a template project?

**Comment by bradrydzewski** [comment]
> This means that the burden of having to maintain repeated code over a growing list of ~40 plugins onto the Comminity but you still want to decide that the community can't make their job easier by requiring use of a template project?

I am not aware of any maintainability issues with the current plugins. You have had the opportunity to provide your feedback and it is something we can take into account in the future. At this time we have no plans to change existing plugins or revise the starter template.

**Comment by thomasf** [comment]
Yeah, it seems like we won't resolve this conflict of interest regarding this, at least not at this time . 
 I'll create my own drone plugins org on GitHub/dockerhub instead .
