### ISSUE TITLE
UI 0.8 shows password in plaintext :(

### ISSUE THREAD

**Issue by xinity** [drone/drone#2185]
the registry tab in the 0.8 UI allows to manually add private registry credentials.
but password filled in is in plain text, anyone behind or near you can see on your screen the password .

Any clues how to fix ?

By the Way awesome job on this 0.8 release (even if it's RC stage), really really doing great !

**Comment by bradrydzewski** [comment]
please open UI issue in github.com/drone/drone-ui

also the registry password field is a textarea, because many people are pasting multi-line key files for use with services like gcr. An html textarea does not allow masking of data. So right now this is the intended behavior as I don't know a fix, but I am happy to accept a pull request.
