### ISSUE TITLE
Move support from Gitter to Discourse

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#2191]
https://discourse.drone.io/

We are moving support from Gitter to Discourse. The reasons for this change are largely summarized in [this blog post](https://dave.cheney.net/2017/04/11/why-slack-is-inappropriate-for-open-source-communications). Note that I will be deleting the following rooms:

* https://gitter.im/drone/drone
* https://gitter.im/drone/drone-dev

**Comment by gboddin** [comment]
I was slowly learning golang and wanted to get involved in drone a bit more to contribute.

With the chat going away, I loose the ability to ask stupid questions to the developers about obvious things ( that are not so much for a golang beginner ).

I'm now unsure where I should ask those kind of questions/discuss implementation, share pull requests, (which are not support related), and feel like I won't get the chance to build a correct relation with the devs team.

This is a good move for getting support requests async and keep the history.

This is a bad move to attract any kind of developers or contributors to drone since they'll get lost in the support sea.

Please at least keep a open dev channel at least !

Those were my 2cents :)

**Comment by LFlare** [comment]
I personally **_feel_** this is a bad decision. I don't think the reasons stated in the blogpost have much grounds for removing live chat entirely. As an open-source project, I think having a live chat channel, like on Freenode `#drone-ci` would prove to be an easier way of getting fast responses.

Hell, why is it even needed for us to choose? There's nothing saying we can't use both. Live for easy questions like how to install it and Async for harder ones like compiling from source.

**Comment by bradrydzewski** [comment]
We have a section dedicated to development questions so that they do not get lost in the sea of support requests. https://discourse.drone.io/c/development

> I think having a live chat channel, like on Freenode #drone-ci would prove to be an easier way of getting fast responses.

I fully encourage the community to create an IRC channel

**Comment by LFlare** [comment]
@bradrydzewski I've done so on Freenode, `#drone-ci`, would help if you supported my decision as well ^_^

**Comment by tboerger** [comment]
I have created on Gitter drone-plugins/Lobby, *but* it's dedicated to plugin development, I won't accept any kind of support request! It's really only to discuss development details and I'm pretty sure brad won't join these conversation.

**Comment by bradrydzewski** [comment]
I am happy to promote the IRC channel in our official developer documentation, but I will be unable to participate in live chat support.

Please try to understand what it is like having a chatroom with thousands of people messaging you at all hours of the day and night because people are in every timezone. I am constantly getting messages and alerts on my phone. I am constantly re-answering the same questions over and over. The chatroom is a major source of burnout. It has prevented me from having any level of work life balance and impacted my personal health.

Because this is a matter of personal health, and a personal decision, I ask you to please respect my decision even if you disagree.

**Comment by gtaylor** [comment]
/thread? I don't think any further discussion in here will be constructive.
