### ISSUE TITLE
Gitlab can't find  pipeline built after merge request

### ISSUE THREAD

**Issue by bryanyang0528** [drone/drone#2212]
#1934 changed the fetch branch from `refs/heads/%s` to `refs/merge-requests/%d/head`. But when I  add a new commit in a merge request, the pipeline won't include in the MR because of the name of branch of  `commit` didn't match the name of original branch.

This is a normal pipeline when I pushed a new branch to Gitlab.
<img width="512" alt="screen shot 2017-09-14 at 02 08 10" src="https://user-images.githubusercontent.com/5171607/30393344-6142c986-9885-11e7-8ece-d6a5fb5b2bd3.png">
 
This is the pipeline when I added commit in a MR.
<img width="787" alt="screen shot 2017-09-14 at 02 07 57" src="https://user-images.githubusercontent.com/5171607/30393372-7d6c47d6-9885-11e7-925c-56f21be70dd2.png">

And this pipeline won't show in the MR.
<img width="689" alt="screen shot 2017-09-14 at 02 17 26" src="https://user-images.githubusercontent.com/5171607/30393494-ebef9e92-9885-11e7-8ade-5352db3f83a6.png">

I'm not sure if anyone have the same issue, or there are something wrong of my configuration. 
Thank you for your time.

**Comment by bradrydzewski** [comment]
I am closing this because a) it looks like a GitLab Pipeline issue and does not include any reference to drone and b) because our [issue template](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md) asks you to open a [discourse](https://discourse.drone.io) thread before creating a github issue
