### ISSUE TITLE
Drone pipeline cannot get access to rancher secrets

### ISSUE THREAD

**Issue by justiniantaylor** [drone/drone#2276]
We are using rancher secrets, which injects the secret as a file into a volume in the container at a location "/run/secrets". The problem I am having is that my integration tests in my drone pipeline do not have access to this volume so cannot load the secrets they need for their tests and therefore all fail.

How would I "pass on" or setup this "/run/secrets" volume mounted for the drone container to my drone pipeline? 

I tried using the DRONE_VOLUME="/run/secrets:/run/secrets" server config, which mounts a /run/secrets volume that I can access in the pipeline, but it is empty and does not contain the secrets. I know the secrets work as I have them setup on other containers, its just this setup in drone that does not seem to work, I think due to it running dnd? 

Thanks in advance!

**Comment by bradrydzewski** [comment]
> I tried using the DRONE_VOLUME="/run/secrets:/run/secrets"

This is because it mounts `/run/secrets` on your host machine. I am guessing that rancher secrets behave similar to kubernetes or swarm secrets which do not exist on the host machine, which is why the mount is empty.

> The problem I am having is that my integration tests in my drone pipeline do not have access to this volume so cannot load the secrets they need for their tests and therefore all fail.

Drone does not support providing agents directly to the agent. Everything needs to go through the server. This means the Drone server would need to read secrets from the Rancher secrets file and then pass those down to your running builds.

The Drone Enterprise edition supports loading secrets from external sources [1][2]. There are plans to support loading secrets from file and from the environment to support Kubernetes, in which case Rancher users would also benefit.

[1] http://docs.drone.io/global-secrets/
[2] http://docs.drone.io/vault-secrets/

**Comment by justiniantaylor** [comment]
Thanks @bradrydzewski, I thought as much regarding the mount from host not the container volume, but was hoping there was a way to get that to work where I could "link" or "pass on" the container volume into the workspace.

You see the problem is I need the secrets to be loaded into the spring environment context using spring profiles for the application to use not for drone to access if that makes sense? I would like my application to be tested with the secure properties mechanism built into it rather than mock this in the CI process with drone loading secrets.

Any other possible suggestions on how I could do this?

**Comment by bradrydzewski** [comment]
Sorry, not sure I understand. Maybe post to our support forum to see if others can provide help? https://discourse.drone.io

**Comment by justiniantaylor** [comment]
Ok great thank you very much for taking the time to response. I have logged [discourse post](https://discourse.drone.io/t/drone-pipeline-cannot-access-the-drone-container-volume/1204)

**Comment by justiniantaylor** [comment]
Just fyi, this was answered with a finalised solution in discourse port, but for completeness of this resolution:

```
pipeline:
  build:
    secrets: [ SOME_SECRET ]
    image: golang
    commands:
      - echo -n $SOME_SECRET > /run/secrets/some_secret
      - go test
```
The trick here was to add drone (current version  0.8.2) secrets in the ui and then do the above to write the drone secrets to the rancher secrets location that could be picked up by the application. I know this is not really ideal as the files arent being encrypted at this stage, but at least its using the same mechanism "inside the application" to load these properties and there are no passwords being committed to the code repository.
