### ISSUE TITLE
Gitea pull request handling is inconsistent

### ISSUE THREAD

**Issue by xoxys** [drone/drone#2314]
If a pull request is not closed and a change was commited to the referending branch the commit will be appended to the existing pull request. But the drone status for this commit does not exist in the pr:

Forked repo:
![grafik](https://user-images.githubusercontent.com/3391958/35341867-fbddcca2-0126-11e8-9bdb-a84ff5585095.png)

Pull request:
![grafik](https://user-images.githubusercontent.com/3391958/35341913-167ab2d2-0127-11e8-8791-d4b7af11deb2.png)

Also drone does not run again if a opened pull request was updated with another commit. Is it possible to re-run drone if there was a new commit to a pull request (pull request updated)?

**Comment by tboerger** [comment]
If drone receives a webhook it will start another build.

**Comment by xoxys** [comment]
@tboerger How does this solve my described problem?

**Comment by pylanglois** [comment]
I have the same problem with gitea/drone

It seems that gitea does not have all the webhooks implemented (https://github.com/go-gitea/gitea/issues/2418). Maybe this is a part of the problem.

Gitea does not display the PR state correctly. Only the first commit carries the state from the drone build. It is misleading because drone with build all the pull request, not the specific commit "54acdb3536" in your case. Every PR rebuild will update the state of the first commit in gitea. As a workaround, you can go in drone web interface and manually rebuild the pull request, it will rebuild all commit related to that PR.

The state of the build should be seen in the PR title, not on the "first commit" since each commit as a different state. Probably a gitea issue...

**Comment by xoxys** [comment]
Any chance to get this fixed?

**Comment by bradrydzewski** [comment]
This is not on my current priority list, so I would recommend sending a pull request if you would like to see this resolved in a timely matter.

**Comment by xoxys** [comment]
@tboerger Thanks for pointing this to gitea

**Comment by xoxys** [comment]
@bradrydzewski Thanks for your reply. I'm not a developer so for me its hard to address this issue

**Comment by bradrydzewski** [comment]
fixed in 1.0
