### ISSUE TITLE
download logs as jsonl file

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#2347]
Logs are json-encoded in the database which lends itself well to http://jsonlines.org/ and means we don't have to decode the full log stream in memory and re-write to the response.

**Comment by shivamMg** [comment]
@bradrydzewski Can you please explain what you mean. Is it that when we stream logs at `/stream/logs/:owner/:name/:build/:number`, we're deserialising log data from db, and then serialising it again for the response.

**Comment by tboerger** [comment]
This issue just handles the option to download the logs in jsonl format. The frontend already fetches the logs in json format from the api.

**Comment by bradrydzewski** [comment]
> we're deserialising log data from db, and then serialising it again for the response.

Nope the logs are stored in the database in json format and are written directly to the response. It is a simple io.Copy.

**Comment by shivamMg** [comment]
We can have API endpoint at `/api/repos/:owner/:name/logs/:build/jsonl` that would return all logs for a certain build in JSONL format.
Should the response of the endpoint send an `application/jsonl` content-type? Preferably with a content-disposition header saying `attachment; filename=logs.jsonl` - so it's meant for download as opposed to "being viewed". This way we can provide a download button at UI that links to the endpoint.

**Comment by bradrydzewski** [comment]
It isn't quite that simple. Today we store a traditional json object in the database, which means we would have to decode and then re-encode the logs in memory to convert from json format to jsonl, which is not something we would want to do.

Instead, I created this issue to think about maybe changing how we store the data from a json object to jsonl. The jsonl format would work well with the Go`json.Encoder` and `json.Decoder` that can encode an decode data streams. Changing the data storage format would be breaking, so I didn't have any immediate plans to implement since, but is something I would consider before 1.0

**Comment by shivamMg** [comment]
Migrating existing `logs` table to newer one - one that stores `log_data` in jsonl instead of the json array. I see two approaches for this: 
1) We can start storing logs as jsonl for the newer release. Prior to this release, existing log_data will keep json array as it already does. To separate the two we can add a column, `is_new_format` for instance, that tells us if the saved log is in jsonl or not. We'll have to write application logic to use either newer or older method for decoding. 
2) Convert existing json array inside log_data to jsonl during migration. I'm not sure about this.

After this change we'll need to modify API handlers (`GetProcLogs` and `GetBuildLogs` afaik) that return logs. We won't be able to write them directly to response. They'll need an intermediate step that converts jsonl to valid json array.

**Comment by shivamMg** [comment]
@bradrydzewski If we store logs in jsonl, then our jsonl log API endpoint would be a direct io.Copy. But existing log API endpoints `/api/repos/:owner/:name/logs/*` will need json decoder/encoder to convert jsonl to json. I do see a faster implementation where we don't decode json, just do direct manipulation by appending "," after each line, and surrounding it in "[]". But I'm not sure if this is what we're aiming for.

**Comment by bradrydzewski** [comment]
abandoned
