### ISSUE TITLE
Special characters in commit messages causes issue with CI_COMMIT_MESSAGE environment variable

### ISSUE THREAD

**Issue by DCRichards** [drone/drone#2379]
## Versions
* drone/agent:0.8
* drone/drone:0.8

## Description
The following build error is seen when a '™' character is used in a commit message:

> Could not set the value of environment variable 'CI_COMMIT_MESSAGE': could not convert string to current locale

I suspect that this is also present for other such characters.

**Comment by bradrydzewski** [comment]
I was unable to reproduce the issue in either of my environments. Maybe it is an issue with one of your build containers?

<img width="875" alt="screen shot 2018-03-22 at 8 32 24 am" src="https://user-images.githubusercontent.com/817538/37780273-a5ede71c-2dab-11e8-8280-0ee5c0f3eb3b.png">

**Comment by DCRichards** [comment]
I pushed another commit after that, and got the following:

> Could not set the value of environment variable 'CI_PREV_COMMIT_MESSAGE': could not convert string to current locale.

So it does appear not to be transient and tied to that particular commit. I'm now investigating with another repository.

**Comment by DCRichards** [comment]
I can reproduce this across more than one repository. This is simply a commit pushed called `Test commit™`

<img width="1397" alt="screen shot 2018-03-22 at 15 42 48" src="https://user-images.githubusercontent.com/3857210/37781037-e16aadd4-2de7-11e8-938a-499c8cd05690.png">

**Comment by bradrydzewski** [comment]
do you need to configure your host machine locale? there was a similar issue in one of the gitlab forums and this was the described fix https://gitlab.com/gitlab-org/gitlab-ce/issues/38698#note_43992619

```
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
```

I am going to close the tracker as I was unable to reproduce and because this appears to be a host configuration issue. Note that (per our issue template) we prefer discourse.drone.io for support and triage, and the github issue tracker for verified bugs. If we can verify this as a drone issue, we can always re-open

**Comment by DCRichards** [comment]
Thanks @bradrydzewski I'll give that a try
