### ISSUE TITLE
[FEATURE] Add special API parameter to trigger latest build again

### ISSUE THREAD

**Issue by moritzheiber** [drone/drone#2397]
I'd like to have an API endpoint available which is able to trigger the latest build available to repository. Currently, you can [trigger a build via the API](http://docs.drone.io/api-build-start/) using the following pattern:

```
POST /api/repos/{owner}/{repo}/builds/{build}
```

where `{build}` will have to be the right build _number_. In a scenario where I would want a webhook to trigger a build using the same parameters as the _latest_ build number, akin to a pattern like:

```
POST /api/repos/{owner}/{repo}/builds/:latest
```

or

```
POST /api/repos/{owner}/{repo}/builds/latest
```

This would allow me to trigger builds using a simple webhook pattern via the API without prior knowledge of the system behind it. A usecase would be triggering builds via Docker Hub webhook.

**Comment by frebib** [comment]
drone-downstream achieves this same effect by fetching the list of builds and triggering the latest from that https://github.com/drone-plugins/drone-downstream/blob/master/plugin.go#L95

This endpoint would be useful for us too and would also prevent the big [TOCTOU](https://en.wikipedia.org/wiki/Time_of_check_to_time_of_use) race condition with the fetch-then-execute workflow.

**Comment by bradrydzewski** [comment]
This can be achieved with two separate API calls. The first step is to fetch the latest build using the following endpoint:

```
GET /api/repos/{owner}/{repo}/builds/latest
```

The next step is to restart or promote the build using the build number from the above query:

```
POST /api/repos/{owner}/{repo}/builds/{number}
```

I think at this time I would prefer to keep these separate, discrete steps instead of combining into a single call. The reason is that `latest` is not really something I recommend using because it is subject to data races / timing issues. Imagine you run a deployment on `latest` and end up accidentally deploying a pull request ...

I am definitely interested in the use cases that you are looking to solve, and would be open to brainstorming alternative approaches, but I'm not sure I want to expand the use of the `latest` keyword in the system. Sorry about that.

> This endpoint would be useful for us too and would also prevent the big TOCTOU race condition

I don't think this would prevent the TOCTOU race condition, it would just reduce the window by a few hundred milliseconds. I think the best option for preventing this race condition is to create a new endpoint that lets you fetch a build by sha, so that you can be more explicit about which build to restart.

**Comment by moritzheiber** [comment]
@bradrydzewski Your proposed solution will make it effectively impossible to trigger a build via the API with a single webhook, i.e. integration with any other system is virtually impossible without more complex logic. This is especially relevant if you're thinking about a chain of builds/pipelines that need to be triggered whenever external factors are lining up correctly.

So my question would be: How does your solution solve the use-case I was talking about? :smiley:

**Comment by bradrydzewski** [comment]
If you need to chain builds together we provide a plugin for this:
http://plugins.drone.io/drone-plugins/drone-downstream/

**Comment by moritzheiber** [comment]
That's the happy path of a Drone instance triggering a downstream build in itself. What about other foreign systems triggering builds within Drone? Jenkins? GoCD? They'll all need special logic, maybe even a separate job, instead of "just" using a webhook.

The same goes for systems that allow for webhooks to be triggered upon actions, e.g. as I mentioned, the Docker Hub, Artifactory etc. because it cannot be a simple `GET` or `POST` request but is meant to be two separate requests.

**Comment by bradrydzewski** [comment]
we have a different design proposed per https://github.com/drone/drone/issues/2679, which I think covers the use case that you are trying to solve.
