### ISSUE TITLE
[new metrics] drone_jobs_"state"

### ISSUE THREAD

**Issue by tonglil** [drone/drone#2419]
`drone_jobs_"state"`

Type: gauge(s)? for ongoing states and counter(s) for finished states

Purpose: tracks how many jobs are in what state (pending, running, success, failure, error, cancelled, killed, etc)

Similar/rename:
- `drone_pending_jobs` to `drone_jobs_pending`
- `drone_running_jobs` to `drone_jobs_running`

Labels:
- org or repo (see note)
- branch (see note)

> Do not use labels to store dimensions with high cardinality (many different label values), such as user IDs, email addresses, or other unbounded sets of values.
https://prometheus.io/docs/practices/naming/#labels

**Comment by metalmatze** [comment]
It's probably good to do something similar to what kube-state-metrics does for the Pods in Kuberentes:
`kube_pod_status_phase`

With these labels:
pod=<pod-name> 
namespace=<pod-namespace> 
phase=<Pending|Running|Succeeded|Failed|Unknown>

**Comment by bradrydzewski** [comment]
only minor consideration is that postgres counts are slow and require a full table scan, which could put pressure on the database. But otherwise this should be pretty simple to add.

**Comment by bradrydzewski** [comment]
Drone uses a partial index to efficiently retrieve `pending` and `running` builds to avoid a full table scan. This works because at any given time there are a small number of pending or running builds. In order to provide metrics for all status types we would need a full table scan which is not something I want to enable by default.

Instead, we are providing a way for teams to extract custom metrics from the system by creating a custom metrics provider. We have a boilerplate template that you can use to get you up and running quickly, and you can add new metrics with just a few lines of code

https://github.com/drone/boilr-metrics

**Comment by kminehart** [comment]
aw man. I just added this, too. :( was about to submit a PR.

**Comment by bradrydzewski** [comment]
I would encourage taking a look at https://github.com/drone/boilr-metrics
It should be relatively easy to get started and add your metric.
