### ISSUE TITLE
Wrong $HOME for non-root builds

### ISSUE THREAD

**Issue by vbrandl** [drone/drone#2436]
When running a build using a non-root user, the `$HOME` variable is still set to `/root`. This variable should not be overwritten by drone. In my concret case, I use the [`ekidd/rust-musl-builder`](https://hub.docker.com/r/ekidd/rust-musl-builder/) image to build a Rust project. Using the following `.drone.yml` produces the following output:
```yaml
pipeline:
  build:
    image: ekidd/rust-musl-builder:stable
    commands:
      - id && echo $HOME
```

```
uid=1000(rust) gid=1000(rust) groups=1000(rust),27(sudo)
/root
```

For comparison the output of running the same command directly inside the container:
```
$ docker run -it --rm ekidd/rust-musl-builder sh -c 'id && echo $HOME'
uid=1000(rust) gid=1000(rust) groups=1000(rust),27(sudo)
/home/rust
```

Without knowing the codebase, I think the problematic lines in the code are https://github.com/drone/drone/blob/master/vendor/github.com/cncd/pipeline/pipeline/frontend/yaml/compiler/convert.go#L84 and https://github.com/drone/drone/blob/master/vendor/github.com/cncd/pipeline/pipeline/frontend/yaml/compiler/convert.go#L90. These should not set the home directory to a hardcoded string.

**Comment by bradrydzewski** [comment]
FYI drone does not currently support non-root images when running custom commands due to volume ownership issues. The hard-coded values reflect this limitation. There are plans to resolve this, which are being discussed on our mailing list. https://www.reddit.com/r/droneci/comments/8opfxw/build_using_docker_image_with_user_directive/
