### ISSUE TITLE
remote:gitea - Can't build a public repository when gitea's REQUIRE_SIGNIN_VIEW is true

### ISSUE THREAD

**Issue by JulienTant** [drone/drone#2468]
Hi,

I noticed that when I create a public repository in Gitea and adds it in drone, it doesn't work (`fatal: could not read Username for 'https://address.net: No such device or address`), But if I pass the repository to private in gitea, remove the webhook, delete & readd the repo on drone then it will work.

So I suppose that this is linked to the fact that my gitea instance run with `REQUIRE_SIGNIN_VIEW` which requires users to be logged in to visit http pages. And i guess that more information are stored for private repository (probably some token?) than for public one, tho it works on private repository.

I can totally help on building a quickfix which would be forcing the request of that special token (I didn't watc the code yet), and see for an improvement which would be "force that behavior when some env var is set like `GITEA_IS_HIDDEN: true`"

What do you guys think about that ?

**Comment by bradrydzewski** [comment]
hey there, per the [issue template](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md), we like to have discussions in the mailing list before creating issues since we get a lot of false positives. I'm not able to reproduce any issues with public or private gitea repositories, so I think we need to triage this further before creating an issue in the tracker. Thanks!

Mailing list: https://discourse.drone.io/
