### ISSUE TITLE
Get an 404 error when trying to activate a private repository

### ISSUE THREAD

**Issue by itaymelamed** [drone/drone#2554]
Trying to activate a private repo which belongs to an organization I get an error:
{
    "message": "Not Found"
}

When I'm executing a GET request to that repo I get a 200 ok response and I can see that I have the following permissions:
    "permissions": {
        "read": true,
        "write": true,
        "admin": false
    }

**Comment by bradrydzewski** [comment]
Hi there, for future reference, please use our [mailing list](https://discourse.drone.io) for end-user support questions instead of creating issues. For this particular issue, the problem is that you are not a repository admin, and therefore cannot activate the repository. This is because you need admin access in order to add repository webhooks.
