### ISSUE TITLE
Running Drone agent on Windows Server 2016

### ISSUE THREAD

**Issue by mappu** [drone/drone#2635]
Hi,

Support for Drone Agent on Windows was added in #1330 , however, it is based on an 1803/1809 image.

Windows Server 2016 cannot run a Windows docker container that is based on a newer OS image.

https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility 

There was a Windows binary release in https://github.com/drone/drone/issues/1330#issuecomment-251129732 but it seems to no longer be updated.

Is it possible to publish updated Windows binaries, or (preferably) Docker tags based on Server 2016 as well as the current 1803/1809 tags? So that Drone Agent can run on a Server 2016 PC?

Thanks

**Comment by tboerger** [comment]
It's not that easy to support all these versions because we need matching build agents for all these versions. So far the project doesn't have the required servers for that to build that automatically.

**Comment by bradrydzewski** [comment]
> Is it possible to publish updated Windows binaries

The binary download link is quite old and we are no longer distributing binaries for the project. We only distribute Docker images.

> or (preferably) Docker tags based on Server 2016 as well as the current 1803/1809 tags?

We already provide official Docker images for Windows Server 2019 and 1809. See the `windows-1809-amd64` tag at https://hub.docker.com/r/drone/agent/tags

I am going to close this as resolved since we already provide an official 1809 agent distribution.
