### ISSUE TITLE
Timeout not honored sometimes

### ISSUE THREAD

**Issue by MorrisJobke** [drone/drone#2656]
We have configured a timeout of 1 hour for jobs:

![Bildschirmfoto 2019-04-10 um 13 54 05](https://user-images.githubusercontent.com/245432/55876646-62aa5f00-5b98-11e9-87fd-5fed2f14b700.png)

Sometimes it happens that one step is running longer than the specified timeout and thus causing a never finishing job (especially bad with the autoscaler we are currently testing, because then pending-jobs are counted in as still running processes that never get into the worker scale downs):

![Bildschirmfoto 2019-04-10 um 13 53 46](https://user-images.githubusercontent.com/245432/55876793-c5035f80-5b98-11e9-9382-4141cfd011ed.png)
![Bildschirmfoto 2019-04-10 um 13 53 40](https://user-images.githubusercontent.com/245432/55876792-c5035f80-5b98-11e9-829e-172ab66f7b28.png)

Any further idea what this could have caused and what data is needed here?

Currently I clean them up by a hacky SQL update, but this should not really be needed to accomplish this and also requires that you know the maximum timeout of all the repos:

```sql
UPDATE stages SET stage_status = 'killed' WHERE stage_status IN ('pending', 'running') AND UNIX_TIMESTAMP() - stage_updated > 3600;
```

I also checked all workers and there are no dangling containers or something suspicious.

**Comment by bradrydzewski** [comment]
This is not related to the timeout. The timeout is enforced on the agent when the build is running. The server does not enforce the timeout, meaning if we lose an agent or it becomes unresponsive, the build may not complete. We refer to these as "zombie builds". Drone does not automatically try to resolve zombie builds, leaving this to the system admin to handle manually.

If the root cause of the zombie build is the autoscaler, I recommend sending a pull request to the autoscaler that tries to cleanup any builds that were running on a lost instance.
