### ISSUE TITLE
non-interactive metrics access

### ISSUE THREAD

**Issue by stevecrozz** [drone/drone#2702]
I'm playing with autoscaling drone agents. Everything I need is available from the API at `api/system/stats`. The trouble is, in order to access this information, I need to log into drone to collect my oauth token so that I can paste it into a script and make the request. That's a manual step that I want to avoid. I could use the new `DRONE_PROMETHEUS_ANONYMOUS_ACCESS` which also has the info I need, but I'd rather not expose that publicly.

Here are some ideas I've had:
1. Use `DRONE_USER_CREATE` to specify the token of a new user so that I know it in advance what the token is. I tried this, but it turns out the token actually does not set the `user_oauth_token` field, but the `user_hash` field instead. Is that intentional? Either way it would be nice to be able to do this somehow.
2. Dig a token directly out of the database. I was thinking of doing this, but it seems if I'm going to go that far, I may as well skip that step and dig the stats I need directly out of the database instead. I can do this but it isn't awesome.
3. Add a new HTTP listener to the drone server which serves some bits of the app (maybe parts of the API) on a separate port without requiring authentication so that I can expose it only privately.

**Comment by tboerger** [comment]
The token created for the machine user should be able to access the api.

**Comment by bradrydzewski** [comment]
Machine accounts can access the API.  If you want to use the machine account to access administrator endpoints you will need to grant the machine account admin access. I just confirmed this is working properly when a machine account is created with `--admin`

>  tried this, but it turns out the token actually does not set the user_oauth_token field, but the user_hash field instead. Is that intentional? Either way it would be nice to be able to do this somehow.

Yes, this is by design.  The machine account is not linked to a GitHub account, which is why this field is empty. The purpose of a machine account is to allow accounts that are not explicitly linked to GitHub. If you have a corresponding GitHub account that you want to link to Drone, you would not create a machine user.

**Comment by stevecrozz** [comment]
Ah Thanks so much! This was my misunderstanding of which field is actually for using as a Bearer token in the API requests.
