### ISSUE TITLE
In a pull_request event, DRONE_COMMIT_MESSAGE is using the description instead of the title

### ISSUE THREAD

**Issue by amq** [drone/drone#2729]
I am using GitHub with Drone 1.1 and I have some logic similar to [CI SKIP] bound to the pull request title.

As far as I understand, drone uses the pull request title for `DRONE_COMMIT_MESSAGE` in case of `pull_request` events.

Everything works well when the pull request description is empty, but as soon as I add a description, it gets set to `DRONE_COMMIT_MESSAGE`.

Interestingly, the pull request title is still shown in the drone UI.

`env` doesn't show any variable which would still contain the pull request title.

**Comment by tboerger** [comment]
AFAIK drone is simply using what gets sent by github within the webhook.

**Comment by amq** [comment]
GitHub does send the PR title in the webhook as `title`, while the description is in `body`.

Additionally, drone does use the PR title in its UI in place where there normally is the commit message. It just doesn't use it for the `DRONE_COMMIT_MESSAGE` variable.

**Comment by bradrydzewski** [comment]
This is the expected behavior. There is a DRONE_COMMIT_MESSAGE is meant to display the commit message not the pull request title. If you would like to add a new environment variable to expose the pull request title you can send a pull request to https://github.com/drone/drone/blob/master/operator/runner/env.go#L75
