### ISSUE TITLE
Feature Request -  Implement Catlight.io protocol

### ISSUE THREAD

**Issue by dijitalmunky** [drone/drone#2734]
Heya,  I recently discovered a CI monitor called Catlight that is really cool and allows communication amongst the team.  It implements a new protocol that aims to replace the cc.xml from cruise control.  It would be quite nice if this protocol would be implemented in Drone.  More information is https://blog.catlight.io/post/158337666873/open-protocol-for-integration-with-continuous

**Comment by bradrydzewski** [comment]
hey there, this came up previously. It must have been discussed in our chatroom because I cannot find an existing issue. The tldr is that the protocol may be open, but the client is proprietary and there are no open source reference implementations available. For this reason, it is not something we plan to implement in Drone. Sorry to disappoint !!!
