### ISSUE TITLE
Drone 1.X: Secrets per image

### ISSUE THREAD

**Issue by vasicvuk** [drone/drone#2763]
In drone 0.8 there was possibility to add Secrets scoped to certain images. This would allow only trusted images to use secrets. 

Now in Drone 1.0 when i try add secret for image i am getting following error:
```
flag provided but not defined: -image
```

This allows everyone to create a custom image and read all the secrets from it by putting them in **.drone.yml** file which can be considered as a security issue.

**Comment by bradrydzewski** [comment]
this flag was removed because it did not provide any real security benefits. If you restricted a secret to plugins/docker in 0.8, for example, someone could just get around this restriction with the following patch:

```diff
pipeline:
  docker:
    image: plugins/docker
    secrets: [ docker_password ]
+   commands:
+   - env
-   repo: hello-world
-   tags: latest
```

The most effective way to secure your secrets is to sign the yaml configuration files. See https://docs.drone.io/user-guide/signature/
