### ISSUE TITLE
Github usernames case sensitivity

### ISSUE THREAD

**Issue by Niondir** [drone/drone#2766]
Not sure how github handles usernames, but I seem to get logged in als "Niondir" in drone but in an earlier version it was "niondir". Now my admin permissions were missing, I just found out by looking into the database.

If usernames on github are not case-sensitive, you should sanitize them in the database.

**Comment by bradrydzewski** [comment]
usernames are only case-sensitive in postgres. You can manually alter the username field to use CITEXT in postgres if you want case-insensitive behavior. Drone does not default to this column type because it is an extension.

this is only an issue when manually creating a user.  This could be resolved by making an API request to get the username prior to adding the account to ensure the correct case is saved. There are no plans, however, to sanitize or alter usernames in the database.

**Comment by bradrydzewski** [comment]
fixed by dce18f9afd4c6db6b82c22472f72246dde2ccb68

this will ensure a user is created with a username that matches the case in the remote system and will prevent the issue described in this thread.
