### ISSUE TITLE
GitHub 'closed' webhook is ignored

### ISSUE THREAD

**Issue by amq** [drone/drone#2795]
I'm testing the functionality introduced in https://github.com/drone/drone/issues/2685, but it seems like the `closed` action is ignored. This can be also seen in the database, where there are just `create`, `sync`, `opened`, `synchronized` in the `build_action` column of the `builds` database.

I would have expected all of the actions to be recorded based on: https://github.com/drone/drone/blob/bcdd4bf0245c82c060407b3b24b9b87301d15ac1/service/hook/parser/parse.go#L249

Upd: just noticed that everything apart of open and sync is ignored:
https://github.com/drone/drone/blob/bcdd4bf0245c82c060407b3b24b9b87301d15ac1/service/hook/parser/parse.go#L234-L237

Would it be enough to simply change that to to include close, while adding the corresponding action?

https://github.com/drone/drone/blob/e855881324dcdf912e70f94d6c7abc1d985cdbd3/core/hook.go#L22-L28

However, I do not understand where the `synchronized` action comes from which can be seen in the database.

**Comment by bradrydzewski** [comment]
This is the expected behavior.  There are many actions that Drone ignores (label added, label removed, closed, assigned, unassigned, edited, ready for review, locked, and more). For pull requests Drone only processes the `open` and `sync` events. 

We have an open issue to support additional actions. Please subscribe to https://github.com/drone/drone/issues/1878 for updates.
