### ISSUE TITLE
Templating, shared YAML

### ISSUE THREAD

**Issue by brandonkal** [drone/drone#2860]
Drone should support templating so we can keep things DRY. I'm finding repositories essentially have nearly identical `.drone.yml` files.
Adding support for basic templating such as [GitLab's include directive](https://docs.gitlab.com/ee/ci/yaml/#include) would help keep pipelines more reusable.

At the very least, Drone should support running a script to generate its full `.drone.yml` file before the run.

There is an old 2 year old issue about supporting templating but it was closed without resolution.

**Comment by bradrydzewski** [comment]
see the following
https://discourse.drone.io/t/how-to-reduce-yaml-boilerplate/3704
https://blog.drone.io/create-pipelines-using-starlark/

> At the very least, Drone should support running a script to generate its full .drone.yml file before the run.

you can use `drone jsonnet` and `drone starlark` commands to generate your configuration file from jsonnet or starlark scripts, or you can install the native starlark or native jsonnet plugins.

https://github.com/drone/drone-convert-starlark
https://github.com/drone/drone-jsonnet-config

**Comment by brandonkal** [comment]
Yes, but that means learning and using two other languages. Also the jsonnet post specifically mentions that imports are not supported. I'm not against those options as a half-solution, but part of the reason for drone's broad success is its simple and approachable config format.

**Comment by bradrydzewski** [comment]
Imports have since been added:
https://github.com/drone/drone-jsonnet-config

While I understand where you are coming from, we considered this heavily and decided about a year ago that instead of creating a templating language or creating an import system that we would rather support existing configuration languages that solve these problems.

Lastly, you can always create an extension that introduces `include` or templating systems. community members have already created some interesting extensions that extend the syntax:
https://github.com/bitsbeats/drone-tree-config
https://github.com/microadam/drone-config-changeset-conditional

**Comment by brandonkal** [comment]
Alright, thank you for considering and for the helpful links. Now it's time for me to sell another DSL to my team...

**Comment by bradrydzewski** [comment]
also definitely consider creating a custom extension. The best way to get something added to Drone core is to prototype as an extension and work out design, get real world feedback, and demonstrate demand.

for example, the community has reacted very positively to the changeset extensions; enough so that we may consider adding to core in the future:
https://github.com/microadam/drone-config-changeset-conditional
