### ISSUE TITLE
[Feature Request] Add Autosync / Autoactivate Options

### ISSUE THREAD

**Issue by toni-moreno** [drone/drone#2867]
Hi .

I'm  right now playing with drone , and I've found that could be good for a now kind of automatic validation service, on certain code pushed on any of the versioning systems supported by drone ( I'm currently playing with gitea).

In that case I expect any of the repos created in the gitea server could be synced and also activated automatically ( without human interaction).

So I propose the following 3 environment variables.

* DRONE_AUTOSYNC_ACTIVATE= true
* DRONE_AUTOSYNC_ACTIVATE_PERIOD=10m
* DRONE_AUTOSYNC_ACTIVATE_FILTERS="my_org/.*,my_org2/*"

With these 3 variables I'm asking drone to sync all new created repos each 10min and autoactivate those repos which match the filter ( in my use case all those under the my_org and my_org2 organizations.(Always  looking for .drone.yml ) 

 Could be this feature easy to add ? I could help to test if done!

**Comment by ashwilliams1** [comment]
👋 hey there, Drone exposes an API so that you can automate various tasks. You can use the API to periodically sync repositories using the `POST /api/user` endpoint.  To learn more about the API see https://docs.drone.io/api/overview/

In terms of adding this to Drone core, we have a policy that new features should generally be prototyped as plugins or external utilities. You will see many features (vault secrets, kubernetes secerts, starlark, etc) are all prototyped as third party plugins.  If there is enough community interest in a particular utility or plugin, we then consider adding to Drone core.

So next step would be to build this as a utility, and then gauge overall community demand.

**Comment by toni-moreno** [comment]
Hi @ashwilliams1 , how can I do  for create a new utility for this use case? there is any drone related utility policy? Any example repo to see the code ?

**Comment by bradrydzewski** [comment]
In this case _utility_ just refers to a standalone program that periodically makes API calls to Drone.  You can write this program using whatever tooling or language you feel comfortable with. It could even be a shell script that is scheduled using cron. There is not Drone utility framework, or anything like that.
