### ISSUE TITLE
Docs: single machine setup guide and DRONE_AGENTS_DISABLED missing

### ISSUE THREAD

**Issue by imolein** [drone/drone#2892]
Since the docs were updated for Drone 1.x, the instructions for a single machine setup without a runner/agent is missing. I asked in Gitter around 2 months ago, if the setup is still valid and will be supported in the future, what has been confirmed.
Today, after I updated my Drone installation and all my Builds were stuck at Pending, I read the [FAQ](https://discourse.drone.io/t/builds-are-stuck-in-pending-status/4437) about this problem and wondered about the statement under **Verify Runner Installation**, which, in my opinion, clearly says **"You need a runner"**. After the irritation I found the solutions to my problem in the changelog (`DRONE_AGENTS_DISABLED=true`, which is not documented too btw.), but nevertheless I would be great to have this in the documentation.
I would be happy to make a PR for this, but unfortunately the current docs are not public yet.

**Comment by ashwilliams1** [comment]
> I read the FAQ about this problem and wondered about the statement under Verify Runner Installation, which, in my opinion, clearly says "You need a runner". 

this is a true statement.  the reason the single-machine guide was removed is because single-machine mode was deprecated.  It will continue working but is not something we officially support going forward and it will not receive updates. This is due to the fact that Drone now has multiple agents types (docker, kubenretes, exec, digitalocean, ssh, aws, virtualbox, etc) which means we can no longer practically offer single machine mode.

**Comment by imolein** [comment]
Thank you for the clear statement about this, because as I wrote, a few months ago I was told the opposite.

**Comment by snoby** [comment]
More than an year later ran into this same problem.  That variable `DRONE_AGENTS_DISABLED=true` needs to be added to the docs and the not officially supported should be added to the docs.  Perhaps an updated doc that shows running a runner on the same machine as server as well....
