### ISSUE TITLE
[feature] ytt templating of .drone.yml

### ISSUE THREAD

**Issue by brandonkal** [drone/drone#2898]
From my perspective, [ytt](https://get-ytt.io/) is more approachable than jsonnet and even starlark. It has many of the same benefits of the other two but doesn't require completely switching to a new DSL for basic language features. Being able to have drone render yaml with ytt would be a welcome improvement.

**Comment by ashwilliams1** [comment]
Support for additional markup or scripting languages should be implemented as conversion extensions, similar to what we've done with starlark:
https://github.com/drone/drone-convert-starlark

We have a starter template that you can use to create a conversion extension:
https://github.com/drone/boilr-convert

We also plan on expanding the scope of [plugins.drone.io](https://plugins.drone.io) to help people discover available extensions.  Once available we will publish an announcement at [discourse.drone.io](https://discourse.drone.io).

At this time we do not plan to support any new markup languages in core.  We do periodically receive requests to add support for other markups (toml, json, hcl, etc) but we have decided that we want these to exist as extensions so that we can focus on efforts on yaml.

**Comment by brandonkal** [comment]
@ashwilliams1 Thanks for the heads up. I don't mind writing and maintaining such an extension, but this issue was opened to get YTT support blessed. I value drone for its CI config simplicity and supporting ytt templating would help in that regard. I'd like to be able to use ytt on https://cloud.drone.io/ so writing a conversion extension alone is not enough. Looking through the starlark repo, I am not sure how that would work as this jumps immediately out:
```
DRONE_CONVERT_PLUGIN_ENDPOINT=http://1.2.3.4:3000
```
There is only one such config.

**Comment by ashwilliams1** [comment]
jsonnet is not enabled at Drone Cloud either.  Instead we recommend committing the generated file to your repository, which is what we are doing in many of our repositories today. Example:

https://github.com/drone-plugins/drone-s3/blob/master/.drone.jsonnet
https://github.com/drone-plugins/drone-s3/blob/master/.drone.yml

You can use both jsonnet and ytt command line tools today with Drone Cloud by committing the generated file. In that sense there is a level playing field. Jsonnet does not have any native advantage on Cloud.

**Comment by tboerger** [comment]
FYI: All drone-plugins repositories are slowly step by step migrated to native starlark support.

**Comment by tboerger** [comment]
IMHO writing a convert extension would be the way to go, this doesn't mean that this will be directly available on cloud.drone.io.
