### ISSUE TITLE
Detected accuracy problems on cron jobs with "@every XX" with XX period time

### ISSUE THREAD

**Issue by toni-moreno** [drone/drone#2903]
Hi to all drone followers.

First I would like to be grateful with drone owners and collaborators for this great software.

As previously discused in https://discourse.drone.io/t/triggered-builds-by-cron-have-high-deviation-against-expected-time/6612/4 , we have detected some accuracy problems with builds triggered from cron with expressions `@every XX`  ( continuous period without no important where  it exact begins) 

The 2 main discussion issues was.

## Accumulated delay

 on jobs needed to have a stable cadence (with acceptance of some jitter) it could be a problem as there is lack of data.

**With current drone version**

![image](https://user-images.githubusercontent.com/5883405/72604755-d2b1f680-391b-11ea-8e91-acd28202f44b.png)

En the previous image cron jobs should be triggered each 10min but all cron-jobs has been accumulating time until bypass one period 

**Expected**

![image](https://user-images.githubusercontent.com/5883405/72604826-eeb59800-391b-11ea-867a-c6fe29119dc9.png)

This is the expected behaviour, where there is one execution on each time bucket

##  job alignment

Right now drone changes the triggering time depending on the DRONE_CRON_INTERVAL if drone-server (for maintenance or for incidence) has been stopped more than one "XX period"  on restart all cron jobs will be triggered first at the same time.  This fact could have impact on not much efficient resource consumption distributión and could overload runner system. 

Could be interesting if Drone could maintain the cron deploy initial time by the end user ( this is like delegate resource load distribucion on the end user ) , instead of changing it with this dangerous behaviour

**Comment by ashwilliams1** [comment]
@bradrydzewski patched the code to use the `time.Ticker` as he proposed in the discourse thread. This will prevent an accumulated delay because the ticker will always execute every N minutes, and will account for delay caused by processing time. Based on our testing we believe this largely solves the issue.

**Comment by tboerger** [comment]
@ashwilliams1 than I guess #2904 can also be closed.

**Comment by toni-moreno** [comment]
Hi @ashwilliams1 , @bradrydzewski . 

Thank you for your fast response. In a few days I will revert my fix #2904 on my lab to pass some test about accumulated delay and alignment, and I will give you feedback.

Thank you again.

**Comment by toni-moreno** [comment]
Hi @tboerger let me please maintain #2904 opened until ended the validation test, if ok  I will close it myself.

**Comment by sbengo** [comment]
Hi,

First of all, thanks for not closing #2904 !
I have been doing some test with the last drone version which includes `Ticker` fix and we have seen the same detected behaviours commented on discourse and on this issue:

- On drone-server restarts, it aligns all the builds at the same time and it doesn't respect the time when the cron was added to repository
- On each execution it seems to add a delay based on `DRONE_CRON_INTERVAL`

Just let me know if you need more information or other tests!

#### Relevant configuration:
 `DRONE_CRON_INTERVAL=1m`

#### Repo and cron configuration

We have set 5 different repos and added a `cron` with `@every 5m`
Each cron is added with a delay of `1 min`

### Job/Builds Alignment

As expected, when we enabled the `cron` of each repo, delayed 1m between them, and configured with `@every 5m`, only 1 job is scheduled and executed each minute.
After a Drone stop and start, the cron doesn't respect the original time and it aligns all builds to be executed on the same time

![cron_alignment](https://user-images.githubusercontent.com/13196237/73861094-d6f77280-483c-11ea-9ec3-582474b531f7.png)

### Accumulated Delay

Each job is planned to be executed `every 5m` but you can see on the image that it is always adding a 1 minute of delay (there are 5 spaces between executions, when we expect only 4).
The delay seems to match with defined `DRONE_CRON_INTERVAL` and, as we reported and tried to fix on #2904 , it seems to be caused due to skipping `<=` cases when trying to retrieve ready builds to be scheduled (related code: https://github.com/drone/drone/blob/master/store/cron/cron.go#L186)

On the image:
- The green card are real executions
- The pink cards are expected executions
- The blue cards are real executions with the same time as expected

![image](https://user-images.githubusercontent.com/13196237/73864262-a1a15380-4841-11ea-88a8-b29a47251ce6.png)

Thanks,
Regards!

**Comment by sbengo** [comment]
Hi again,

I have repetead the test commented above using last version of PR #2904 and I want to share with you the results and comparison, as seems that problems described on this issue and on discourse could be solved:

- On drone-server restarts, it doesn't allign all the builds at the same time and it respects the previous value stored
- On each execution it doesn't add an accumulated delay

Please, ask me if you need other tests or more info

### Job/Builds Alignment

As expected, each job is scheduled within 1 minute of delay between them.
On Drone stop and later a start the cron seems to respect and keeps with the same previos/next time stored on DB, so the builds are not aligned on the interval where drone, and cron goroutine starts:

![image](https://user-images.githubusercontent.com/13196237/74042539-07b7e300-49c8-11ea-944b-9367a3211d5c.jpg)

### Accumulated Delay

Each job is planned to be scheduled and run `@every 5m`. As you can see on the following image, no delay is added between executions and it seems to be stable over the time.

Just to clear the image and following with posted above:

- The blue cards are real executions with the same time as expected

![image](https://user-images.githubusercontent.com/13196237/74042668-477eca80-49c8-11ea-989b-68f270b2d7c6.png)

Thanks,
Regards!

**Comment by toni-moreno** [comment]
Hi @ashwilliams1 @bradrydzewski .  

I would like to discuss again about this problem and  the best way to fix it.

You can test my patched drone with this public image `tonimoreno/drone-server_fix_cron4` if you want.

Thank you again.
