### ISSUE TITLE
Any plans for resolving `.local` addresses?

### ISSUE THREAD

**Issue by rcarmo** [drone/drone#3036]
I understand the builder/worker containers are pretty minimal, but I would love to be able to have the agents resolve `.local` addresses. Right now, without Avahi/Bonjour/RendezVous support, it is hard to get Drone to work on my particular LAN without maintaining a DNS server, which is something I'd prefer not to.

(I should add that using `--add-host` or `extra_hosts` to launch the agent container does not seem to work. I can `exec` into the container and ping the `.local` addresses, but `git clone` fails)

**Comment by tboerger** [comment]
Drone is simply using the name resolution of Docker, so what should we do within Drone?

**Comment by rcarmo** [comment]
Well, after a few more tests I think the issue lies with the git container. I have bee trying to use —add-hosts to my drone Docker container, but that seems not to be passed on, so if you could have the git container respect that, it would probably allow me to workaround the problem...

**Comment by tboerger** [comment]
Not sure if there is an environment variables for adding hosts to all build containers, but this sounds like a better thread for discourse.

**Comment by rcarmo** [comment]
I don’t think Discourse is the right way to deal with bugs - it’s impossible to ascertain status and progress on anything discussed there.

**Comment by bradrydzewski** [comment]
This repository is for the Drone server.  The repository for the Docker pipeline runner can be found at [drone-runners/drone-runner-docker](https://github.com/drone-runners/drone-runner-docker) in the event you are interesting a pull request to enhance the pipeline runner to support your use case.  I am going to close this since the request is unrelated to this repository.
