### ISSUE TITLE
Add some reporting (unit tests, code coverage)

### ISSUE THREAD

**Issue by micw** [drone/drone#440]
(feature request) Most build tools support execution of tests and reporting (e.g. maven uses surefire to run unit test and creates reports from it). It would be nice if drone could parse such reports and display them on the history. In addtion, such information could be part of the status mails (like "3/100 tests" failed).

**Comment by shawnzhu** [comment]
one of my problem is how to send out unit test reports when/after test fails since it uses `set +e` in the beginning of actual build script `/usr/local/bin/drone` inside container which means it will exit immediately if any command or pipe fails, and there is no chance to publish any reports out.

So I have to manage this situation in test manager like `grunt` or `protractor` before it exits with non-zero status, then use `publish` plugin to transfer the report files out.

any ideas?

**Comment by bradrydzewski** [comment]
@shawnzhu yes, this will be possible when we move to our new plugin model, which is bundled in the new matrix changes / branch

**Comment by bradrydzewski** [comment]
I'm going to close in favor of https://github.com/drone/drone/issues/239 which has more activity in the comments
