### ISSUE TITLE
Display error messages, prevent silent failures

### ISSUE THREAD

**Issue by ciarand** [drone/drone#542]
Running on: 3d839498a1a694095c89e4798e7f1bb5c643e727

Steps to repro:
1. Go to /account/repos
2. Select a repo that belongs to another group (*one that you aren't an admin for*)
3. Click the "activate now" button

Expected results:
- An error message pops up, telling me what's going on. Something like:

>Oops, looks like you don't have permission to install Drone on this repository. You should talk to the owner of the repo about it.

Actual results:
- Silently fails, logging some 403s in the console

**Comment by rapilabs** [comment]
Yep, parsing private variables was failing due to a lack of space after the colon but no indication was given.  It's been years since I've used YAML so was trying to figure out why my env vars weren't being set.

imho I think env vars are better off with just key value pairs like you get on a lot of other services then issues like this wouldn't really occur.

**Comment by bradrydzewski** [comment]
fixed in 0.4
