### ISSUE TITLE
Easily clone other private repos during a build

### ISSUE THREAD

**Issue by hmarr** [drone/drone#61]
It would be great to be able to inject a pre-defined SSH key into containers.

As part of our build process, we pull down dependencies that are in private GitHub repos. Currently there's no (easy) way of accessing these repos from Drone. This could be resolved by adding the ability to generate an SSH key that's used by containers (copied to `~/.ssh/id_rsa`), which we could then add as the deploy key for our dependencies.

**Comment by bradrydzewski** [comment]
Official support for updating your repository keys via rest:
http://readme.drone.io/api/repos/put/

Along with support for updating keys via the command line utility:
```
drone set-key github.com/foo/bar ~/.ssh/id_rsa
```

**Comment by bradrydzewski** [comment]
we are going to experiment with a new idea here.  We are going to add a `.netrc` file to the build environment with the access token, similar to the comment by @gdborton 

this would not apply to public (open source) repositories for security reasons.

this should work well for GitHub and GitLab. I'm sure we can get something working with Gogs as well. Bitbucket seems like a lost cause, but you never know ...

**Comment by hd-deman** [comment]
take a look https://github.com/blog/1957-git-2-3-has-been-released for new `GIT_SSH_COMMAND`

**Comment by MattyKuzyk** [comment]
I am having issues with Github SSH and Drone.

Originally, I was using a deploy key from Drone on my repo and everything was peachy. However, we soon ran into a problem where we needed to clone a private repo in our npm install. I made a machine user on Github that I added the keys for on my machine and on the machine user, and added that machine user to our orgs on GH. I could clone everything just fine from the machine, all the access rights were correct.

When drone would build, however, it wouldn't pull in this key and use another key (presumably the deploy key) to try and clone this repo we were using in npm.

So I used the REST API to update the public and private keys on Drone to be that of our user, it worked properly and on the web interface it showed my repo as having that public key.

I then tried to use the `drone set-key github.com/foo/bar ~/.ssh/id_rsa` command with our url instead (obviously) to make sure the instance was using the right private key. I got this error:

```
panic: runtime error: assignment to entry in nil map

goroutine 16 [running]:
runtime.panic(0x8d8e60, 0xe11293)
	/usr/local/go/src/pkg/runtime/panic.c:279 +0xf5
net/textproto.MIMEHeader.Set(0x0, 0x96c1d0, 0xe, 0xc20804c0d0, 0x4)
	/usr/local/go/src/pkg/net/textproto/header.go:22 +0xb5
net/http.Header.Set(0x0, 0x96c1d0, 0xe, 0xc20804c0d0, 0x4)
	/usr/local/go/src/pkg/net/http/header.go:31 +0x4f
github.com/drone/drone/client.(*Client).run(0xc20800fa40, 0x948f10, 0x3, 0xc2080d0930, 0x29, 0x7bb640, 0xc208040f40, 0x0, 0x0, 0x0, ...)
	/var/cache/drone/src/github.com/drone/drone/client/client.go:83 +0x594
```
Now I can't even get Drone to clone my repo in the first place since the keys for that are now wrong, and I basically took two steps backward.

@bradrydzewski am I doing something completely wrong? I now have a broken Drone instance with no way to reset the keys. Are there any workarounds here?

**Comment by shawnzhu** [comment]
@MattyKuzyk you can reset key pair of any of your repo via command `drone set-key`. see this [comment](#issuecomment-71779208). it works for me when using latest drone cli.

**Comment by bradrydzewski** [comment]
closing in favor of #1090 which is implemented in 0.4 branch (upcoming release). We use a `.netrc` file to authorize cloning the https url. This means you can `go get` or `npm install` other private repos

**Comment by jgermade** [comment]
Hi @bradrydzewski , could you show an example of use with the .netrc 

In the proyect I'm working in, I have a public repo that uses a private for build. So I'm not sure I can use this approach

also, can not find an example of use for the identity flag

thanks in advance!

**Comment by bradrydzewski** [comment]
@jgermade the netrc file is only injected into private build environments for security reasons. Exposing a netrc file or ssh key for a public repository would make it susceptible to theft by issuing a malicious pull request.

You are more than welcome to use secrets to provide a GitHub token or credentials to your build environment, but secrets won't be injected into your build environment for pull requests for the same security reasons mentioned above.

You can read more about secrets at http://readme.drone.io/usage/secrets/

**Comment by jgermade** [comment]
thanks @bradrydzewski for support!!

finally got it working combining token in secret and sed replace the bower.json dependence
