### ISSUE TITLE
Use regex for branch white-list in yaml

### ISSUE THREAD

**Issue by donny-dont** [drone/drone#713]
Currently the include exclude for branches is an all or nothing scenario.

It would be nice to be able to do something like
```
branches:
  include:
    - master
    - release*
```

**Comment by stevenpall** [comment]
@bradrydzewski Any update on this functionality?

**Comment by bradrydzewski** [comment]
we have a pretty solid implementation in the 0.4 branch. This needs to be documented, including the new negation syntax we added before closing this issue (reminder to me)

**Comment by pgaubatz** [comment]
Hi!

I was wondering what happened to this issue...
It would be great to only trigger a deploy task when the current branch matches a certain regex (e.g., `/^v?[0-9]+\.[0-9]+\.[0-9]+.*$/`).
The documentation (http://readme.drone.io/) doesn't mention it, but is something like this already possible?

Thanks in advance and thanks for drone! I love it! :+1: 

Cheers,
Patrick

**Comment by bradrydzewski** [comment]
I'm marking this as closed since we now have patterm matching and include and exclude sections. See unit tests for more examples:
https://github.com/drone/drone/blob/master/engine/parser/branch_test.go

This is an example of all the different variations:

```
branch: master
branch: [ master, release/*]
branch:
  include: master
branch:
  include: [ master, release/* ]
branch:
  exclude: feature/*
```

If anyone wants something more complex than this I am willing to accept pull requests that maintain backward compatibility and include unit tests :)
