### ISSUE TITLE
Allow global, default values for plugins

### ISSUE THREAD

**Issue by donny-dont** [drone/drone#716]
Currently environment variables can only be injected per repo. Including a way to inject environment variables for all repos would be great for some configurations. As an example if the server has to go through a proxy.

**Comment by engine07** [comment]
Is there any plan to allow setting global environment variables available in all repos?
(without making custom image and drone.d/ option)
as well to setup environment variables per repo from cli or through a kind of settings.

For example, I am using publish docker plugin and where registry is private.
The best place to put registry data is in repository environment variables.
Since many project will use same private registry it make sense to have global env variables
so there is no need to setup same for each repository.

Also in same example, I would need now to login into web interface (unless I am 
now aware of a way to do it from cli) and type those env vars manually.
Being able to set them up from a kind of script would be great,
since that would allow me to automate CI setup .

**Comment by bradrydzewski** [comment]
@engine07 there are a few different ways we are solving this issue. We are starting to allow global settings for each plugin to solve exactly the issue you mentioned. These need to be implemented on a per-plugin basis. You can see an example of this in the NPM plugin:
https://github.com/drone/drone/blob/master/plugin/publish/npm/npm.go#L28

I am still planning to add global environment variables to the configuration file that get injected into every single build, although I think the above option is better for the use case you described.

I would also love the ability to manage private variables via the CLI. The API exposes this capability so it is just a matter of adding the command to the CLI codebase.

**Comment by bradrydzewski** [comment]
Planned implementation is the following ... modify the `runner` package (drone server) to read the `os.Getenv` data and send all plugins that start with `PLUGIN_` down to the build container.

The build container should then use `os.Getenv` to read all environment variables that start with `PLUGIN_`. These environment variables should be sent to each plugin container.

Ideally we could find some way to limit which environment variables are sent to which container. For example, `PLUGIN_HEROKU_TOKEN` would only be sent to the `heroku` plugin. Or `PLUGIN_OCTOCAT_HEROKU_TOKEN` would only be sent to the custom `octocat/heroku` plugin. The only issue here is deciding how we want to handle custom plugins from custom registries (ie custom domain name)

**Comment by bradrydzewski** [comment]
this has been implemented in 0.4 branch. Needs to be documented before we can close (reminder to me)

**Comment by engine07** [comment]
great !

**Comment by bradrydzewski** [comment]
closing now that this is documented http://readme.drone.io/usage/secrets/#global-secrets:0d943d142dc6bcdd2e544b095a49f72b

**Comment by gtaylor** [comment]
Cool, didn't know this was possible!
