### ISSUE TITLE
Build images from private registries

### ISSUE THREAD

**Issue by paislee** [drone/drone#728]
It appears there's no way to use a build image from a registry that requires authentication, the build simply outputs `Authentication is required`  as of drone version 0.3-dev. Perhaps .drone.yml's `image` key can become a block:

```
image:
    registry_host: docker.example.com
    registry_protocol: https
    registry_login: true
    registry_login_uri: /registry/v1/
    username: myuser
    password: mypassword
    email: myuser@example.com
    image_name: my-webapp
```

The above example borrows all keys from [docker publishing](http://drone.readthedocs.org/en/latest/publish.html#docker). It is perhaps worth considering in conjunction with https://github.com/drone/drone/issues/697 or other build image proposals.

**Comment by MitchK** [comment]
Hi! Any updates on the PR?

Some input from me: The approach to store the registry credentials within the ```.drone.yml``` is great when having multiple 3rd party registries.

But I would also add the option to provide credentials within the drone configuration, so the developer does not need to login, even if it is a private registry.

We have two use cases at our company:

 * Giving developers the option to connect to any Docker registry he likes
 * Providing an "official" internal Docker registry in order to provide "standard compliant" build images. Only those images can be used in order to ship software to the customer. 

The second use case is our main use case and we want to make it very easy for developers to build their software with standard compliant images without even knowing what Docker is or even knowing what a Docker Registry is. In the simplest case, our developers just want to consume those images.

And this is actually something where Drone and Docker shines.

So it would be awesome to have the option to store credentials for a specific registry within the drone server configuration, for example. If the user wishes to use another registry with other credentials, he can do this.

**Comment by sunnysingh1985** [comment]
Hi,

Are there any updates on this issue? I am trying to package docker and docker-compose in a custom image so that the base image used by drone to start a build container can be used to create a new and publish a new image. 

Please let me know if there are any plans to get this in soon.

Thanks in advance!

**Comment by bradrydzewski** [comment]
The relevant changes were made to `samalba/dockerclient` to pull private images:
http://godoc.org/github.com/samalba/dockerclient#AuthConfig

The next step is to adjust #902 (yaml specification) to include registry authentication details in the yaml format. It should probably mirror the `AuthConfig` structure defined above.

This change is dependent on the 0.4 release, which replaces our custom docker client with `samalba/dockerclient` as defines the new yaml format. Work on the 0.4 release has just started and is about a month from completion, just to give everyone a timeline estimate.

**Comment by bradrydzewski** [comment]
I wanted to add some notes to describe what it would take to implement this feature.

First, we need to alter the Yaml structure so we can specify a username / password for pulling private images. This would get changed here:

https://github.com/drone/drone-exec/blob/master/yaml/types.go#L18

Before we make the above change, we need to be very careful about how we define these yaml attributes, because they could conflict we attributes being used by our plugins. So we probably need to quickly audit the 20 existing plugins to make sure there isn't an overlap. See http://addons.drone.io

Second, we need also alter the following structure to include the username / password. The username / password from the yaml gets mapped to this object:

https://github.com/drone/drone-exec/blob/master/parser/node.go#L50

Third, we need to alter the build runner code to pass the credentials to the Docker helper functions responsible for pulling images:

https://github.com/drone/drone-exec/blob/master/runner/build.go#L91

And finally, we need to alter the Docker helper functions to accept the credentials and use them (optionally) when pulling the image:

https://github.com/drone/drone-exec/blob/master/docker/util.go#L33

Overall this shouldn't be too terribly difficult to implement. The hardest part, in my mind, is taking the time to audit the existing plugins to make sure there is not overlap in variable names. The rest should be pretty straight forward.

cc @epipho I think you mentioned interest in this feature as well, so wanted to cc you

**Comment by jgreat** [comment]
https://github.com/drone/drone-exec/pull/5

I took a crack at this. I've created 2 new variables `docker_username` and `docker_password`
If we want to name them something else I'm happy to change.

I'll be honest I did not go into every plugin to check for conflicts, but I did check the most likely suspects. drone-docker and drone-dockerhub

```yaml
build:
  image: myrepo/project:0.0.1
  docker_username: jgreat
  docker_password: ***********
```

**Comment by mikejihbe** [comment]
Excited to have this merged too!

**Comment by bradrydzewski** [comment]
initial support merged thanks to @jgreat ... there may still be issues when storing your docker username and password in a `.drone.sec` file for your private image, since secrets aren't injected into pull requests. The `.drone.sec` piece is being worked on, but hopefully this is a good first stepn.

If the above limitation is a blocker and your repository is private, I recommend creating a machine account for your registry (ie account not owned by a person) and hardcoding the password in your .drone.yml until we have a permanent solution for dealing with pull requests

**Comment by epipho** [comment]
@jgreat thanks for picking up the torch on this one. Much appreciated.

**Comment by xinity** [comment]
auth seems to be working for me as the error i get isn't 401, but 404 (not found),

which is strange because:
```
[info] Pulling image gliderlabs/alpine:3.1
[info] Pulling image plugins/drone-git:latest
$ git init
Initialized empty Git repository in /drone/src/github.org/[myrealm]/docker_xinity.git/
$ git remote add origin https://github.org/[myrealm]/docker_xinity.git
$ git fetch --no-tags --depth=50 origin +refs/heads/drone:
From https://github.org/[myrealm]/docker_xinity
 * branch            drone      -> FETCH_HEAD
 * [new branch]      drone      -> origin/drone
$ git reset --hard -q 70fb25029d85aa555fe85bf2a4f3bd3a68ff38fe
[info] Pulling image registry.[mydomain].com/[myrealm]/base:latest
[error] Error pulling registry.[mydomain].com/[myrealm]/base:latest. Error: image [myrealm]/base:latest not found
```
fails!

but:
```
[info] Pulling image gliderlabs/alpine:3.1
[info] Pulling image plugins/drone-git:latest
$ git init
Initialized empty Git repository in /drone/src/github.org/[myrealm]/docker_xinity.git/
$ git remote add origin https://github.org/[myrealm]/docker_xinity.git
$ git fetch --no-tags --depth=50 origin +refs/heads/drone:
From https://github.org/[myrealm]/docker_xinity
 * branch            drone      -> FETCH_HEAD
 * [new branch]      drone      -> origin/drone
$ git reset --hard -q 70fb25029d85aa555fe85bf2a4f3bd3a68ff38fe
[info] Pulling image registry.[mydomain].com/base:latest
```
works !

any clues on why ?

**Comment by xinity** [comment]
should i rebuild drone from master or does the latest docker image build containes the merge?

**Comment by bradrydzewski** [comment]
@xinity drone publishes a new drone image on every successful merge to master. For reference:
https://github.com/drone/drone/blob/master/.drone.yml#L24

**Comment by xinity** [comment]
all right :)

i'll drop all my drone* docker images to make sure i have latest :)

**Comment by xinity** [comment]
just tested with the right yml config

seems to be working even without having to hardcode credentials

**Comment by bradrydzewski** [comment]
there is a patch in the 0.5 release that makes this much easier, but the documentation is poor and I would like to test the feature a bit more. Once documented and thoroughly tested I'll close

**Comment by atombender** [comment]
Will 0.5 support this as a `dronerc` config? It seems completely wrong to me that each repo's `.drone.yml` should have to contain the necessary credentials. For one, it's not the _project_ that pulls images, it's _Drone_.

**Comment by tboerger** [comment]
It is project specific. For 0.5 you will have organization secrets, so you can manage it optionally for the full organization or just for a single project via drone-cli

**Comment by bradrydzewski** [comment]
what @tboerger said. here is the link for reference https://github.com/drone/drone/issues/1619

pull requests accepted if you need the feature expedited

**Comment by DCRichards** [comment]
Hasn't this now been done? http://readme.drone.io/usage/build_test/

**Comment by counterbeing** [comment]
It took me a while to figure out where the documents were regarding using private docker images in drone, so I'll leave the link here:

http://readme.drone.io/0.5/download-private-docker-images-secrets/

And to prevent link rot, here's a snippet that show's how you can use passwords, or environment variables through drone secrets to set credentials:

For passwords directly in your .drone.yml

```
pipeline:
  build:
    image: octocat/hello-image
    auth_config:
    username: octocat
    password: password
    email: octocat@github.com
``` 

And, what I expect most people are looking for, you can set these environment variables through secrets:

```
REGISTRY_USERNAME
REGISTRY_PASSWORD
REGISTRY_EMAIL
```

For dockerhub, I didn't need the `REGISTRY_EMAIL` var set.

**Comment by bradrydzewski** [comment]
closing now that this is solved in 0.5

http://readme.drone.io/0.5/download-private-docker-images/
http://readme.drone.io/0.5/download-private-docker-images-secrets/

**Comment by clintberry** [comment]
It would be nice to set REGISTRY_USERNAME and REGISTERY_PASSWORD globally so I don't have to generate secrets for every repo...

**Comment by clintberry** [comment]
I am an idiot. There are org secrets... `drone org secrets` in case anyone was wondering :-)

**Comment by Jeeppler** [comment]
@clintberry can you explain what you did? I am unable to pull a private image, even with `drone org secrets` enabled. What did you configure to use the `drone org secrets`?
