### ISSUE TITLE
stdout'ing causing high memory, cpu and blocks browser

### ISSUE THREAD

**Issue by nils-werner** [drone/drone#733]
While downloading a ZIP file I accidentally didn't save it to a file but had `curl` print it to stdout. The result is now a big `drone.sqlite` file and a browser that breaks down every time I visit the commit build status.

 - Does drone automatically prune old commit logs?
 - Is there a way to force something like that
 - Can we implement a countermeasure for occasions like these (this is also a security threat as people could just cat `/dev/urandom` into stdout, filling the Drone database with junk)

**Comment by ye** [comment]
@bradrydzewski Conversely, truncating the terminal log output defeated the purpose of logging, as we are missing the critical piece of information of why the build failed.

Additionally, each line of truncation emitted a line of `Truncating build output ...` annoyingly! 
![screen shot 2015-07-08 at 4 22 13 pm](https://cloud.githubusercontent.com/assets/133924/8581250/912d9c88-258d-11e5-9a58-6c6e00c79fdc.png)

I think we should have a raw copy of the terminal output log somewhere stored into SQLite/MySQL/PostgreSQL. And then truncating on the browser output if necessary.

**Comment by bradrydzewski** [comment]
@ye this is how it works in `0.4` (upcoming work-in-progress release). The browser invokes the endpoint with `?truncate=true` which limits the output to 2mb. So invoking the endpoint with `?trucate=false` would stream the full build output. This will allow us to add a "download full logs" button.

The Go code looks something like this:

```Go
	r, err := store.GetBlobReader(path)
	if err != nil {
		c.Fail(404, err)
	} else if truncate == false {
		io.Copy(c.Writer, r)
	} else {
		io.Copy(c.Writer, io.LimitReader(r, 2000000))
	}
```

The logs are stored unbounded in the sqlite database at the moment in that branch, but will probably end up being capped. We need to cap the logs, at some level, because when retrieved from the database the full logs are loaded into memory, even if we limit what is streamed to the browser.

When we first launched Drone (hosted service) someone streamed 1GB of build logs and it kept crashing our server on the database end, which is something I want to avoid in the open source version.

**Comment by vtolstov** [comment]
I think that logs need to be gzipped,so megabytes of data goes to 300K...
What you think?
08 июля 2015 г. 23:40 пользователь "Brad Rydzewski" <
notifications@github.com> написал:

**Comment by ye** [comment]
@bradrydzewski First off, thanks for the insight and the tip, I will look into it. But I think you have a [bug in your code] (https://github.com/drone/drone/blob/master/shared/build/writer.go#L35): `Truncating build output ...` string is getting outputted for each line exceeding the [DefaultLimit](https://github.com/drone/drone/blob/master/shared/build/writer.go#L17). 

Btw, why hardcoding `2000000 ` there in the source? Perhaps a build time configuration is better?

Second of all, I think if w are using MySQL / PostgreSQL as backend options, the storage are essentially limitless IMMO (I.E. Facebook is storing majority of their data on MySQL server farms). Also, evidently, when truncation is enabled, junk data `Truncating build output ...` are stored into the database as well. Just an FYI. 

@vtolstov Either SQLite internally or the Go driver is already gzipping the blob column data type. I was able to reserve engineer the actual log output independent of Drone app by examine the SQLite db file directly.

**Comment by bradrydzewski** [comment]
> But I think you have a bug in your code: Truncating build output ... string is getting outputted for each line exceeding the DefaultLimit.

Your are correct, that is not the intended behavior. I am focused on the 0.4 branch at the moment where this is no longer an issue, but will accept a PR if someone wants to fix in 0.3

> Btw, why hardcoding 2000000 there in the source? Perhaps a build time configuration is better?

Based on prior testing, anything larger than this amount crashes the browser. The problem is almost certainly the to ANSI terminal to HTML algorithm. We could make this configurable, however, it doesn't seem to make much sense if we know it will crash the browser. I'd much rather improve the client side algorithm and remove the limit all together (I bet we could use webworkers, request animation frame and more).

Just to set expectations, this is low on my priority list compared to matrix builds, plugins and just pushing the 0.4 release out in general. So if a motivated individual is willing to pick this up and work on a fast, efficient terminal to html algorithm I would definitely accept a patch, and will be very grateful :)

> I think if w are using MySQL / PostgreSQL as backend options, the storage are essentially limitless IMMO (I.E. Facebook is storing majority of their data on MySQL server farms). Also, evidently, when truncation is enabled, junk data Truncating build output ... are stored into the database as well. Just an FYI.

Agreed the limitation is not the database. When Drone fetches the build output from the database it has to read the entire []byte into memory. Therefore a very large build output has the ability to exhaust system resources and bring down the server. We have actually seen this issue in production which is why we'll put a reasonable cap in place in 0.4 (probably around 20MB)

**Comment by ye** [comment]
Fair enough. I will see what I can do. Btw, what's the release timeline for version 0.4? (Pardon me if you've announced it)

**Comment by PAStheLoD** [comment]
Hello,

We're using 0.4.0 and I just had to wait until the OoM killer stepped in, because otherwise X completely locked up. (I was able to finally switch to a different terminal.)

Thanks

**Comment by bradrydzewski** [comment]
moving issue to https://github.com/drone/drone-ui/issues/39 where it is being actively discussed and worked on.
