### ISSUE TITLE
Rebasing a branch doesn't trigger a branch rebuild

### ISSUE THREAD

**Issue by dangra** [drone/drone#740]
Steps to reproduce:

- branch master to feature-XXX
- commits changes to feature-XXX
- push <-- _this will trigger a branch build as expected_
- create a PR

- make more changes to feature-XXX branch, commit and push
  _this trigger a branch and PR build as expected, so deploy section runs fine for branch build_

- Now add changes to master and rebase feature-XXX on top of it
- push  <-- **UI shows a branch and PR build but both links to PR, and none to the branch**, so deploy section didn't run.

**Comment by andy-g** [comment]
Hi @danga, are you able to test this by submitting the Pull Request from a different github repo? I think it relates to an issue I opened: #819. When pushing the branch & creating the PR on the same repo that drone is linked to, GitHub sends 2 webhooks to drone (one for the branch change and the other for the PR change). Drone appears to responds to the first one it receives (which could be either), and I think this inconsistency may be causing your issues.

If you're able to test submitting a PR from a separate GitHub repo, then I'd assume GitHub will only send PR webhooks (because the branch the PR is based on is no longer in the repository linked to Drone) and I assume this will resolve the issue.

You can also see what webhooks are being sent and which one drone is accepting by going to your repo Settings > Webhooks & Services > Select the drone Webhook url > Go down to "Recent Deliveries"

**Comment by dangra** [comment]
hi @andy-g, the workflow you describe in #819 is the same I use with my team.

The workaround I found was to disable "Pull Request" webhook event so it only build on Push events, this works for me because I need deploy section to run for every feature we work on.

> If you're able to test submitting a PR from a separate GitHub repo, then I'd assume GitHub will only send PR webhooks (because the branch the PR is based on is no longer in the repository linked to Drone) and I assume this will resolve the issue.

I can test it, will let you know.

**Comment by bradrydzewski** [comment]
we previously had a unique constraint in the database that was the root cause of this issue. That constraint has been lifted in latest release
