### ISSUE TITLE
Security issue where user sessions are conflated

### ISSUE THREAD

**Issue by mattbostock** [drone/drone#790]
Hi,

We're running an evaluation Drone based on `master` (as of 0a6227930). During our testing with multiple (~5) users, we noticed an issue whereby one user, having refreshed the page, was suddenly logged in as another user (that had just registered).

This was using the GitHub Enterprise remote plugin.

I've had a look through the codebase and can't find what might have caused it, but it feels like a race condition. I'm going to add some debug logging to our local repo so that we have more information should the issue happen again.

Has anyone noticed this issue before or have a hunch about what may be causing it?

Thanks,
Matt

**Comment by bradrydzewski** [comment]
@mattbostock if you can reproduce or provide detail it would be very helpful. I'm guessing they saw  the other individuals username and avatar in the upper right corner? Can you verify?

Can you check in the database and verify the `user_id` for the above user that had just signed up? Does the `user_created` field match the time of when they signed up? Does anyone have a `user_id` of zero? This is probably a long shot, but if the `user_id` were not correctly set or incremented it would overwrite / replace an existing user in the database.

We are pretty careful not to use any globals or shared state in our codebase. The user session is stored in the browser's `localStorage` with the `user_id` embedded in the token so that we don't need to keep any state on the server.

The only shared state (related to user and user session) is the database which where I'd like to start troubleshooting.

**Comment by mattbostock** [comment]
That's correct, the other user's username/avatar were shown in the top right corner. Unfortunately I don't have much more information that that, other than the issue was first noticed when refreshing the page. The page open was a repository page, i.e. the one that displays immediately after activating a repository.

I believe each user has a distinct user ID but I'll double-check this on Monday.

One thing I did notice is that the [Github plugin uses `securecookie.GetRandomKey()`](https://github.com/drone/drone/blob/5afcc888270fa595920abc76f085e64011e7c9ee/plugin/remote/github/helper.go#L259) to [generate the `state` token](https://github.com/drone/drone/blob/5afcc888270fa595920abc76f085e64011e7c9ee/plugin/remote/github/github.go#L71-L73) used to mitigate CSRF attacks. [`securecookie.GetRandomKey()` returns `nil`](https://github.com/gorilla/securecookie/blob/f0559d009e6943011cd1ba6eb16195cf5e0ed326/securecookie.go#L347) if it encounters an error; I wonder if an error did occur and caused a race condition if two users authenticated against GitHub Oauth around the same time and both [`cookieState` and `state`](https://github.com/drone/drone/blob/5afcc888270fa595920abc76f085e64011e7c9ee/plugin/remote/github/github.go#L79) were storing empty strings. I'll look more closely into that.

**Comment by bradrydzewski** [comment]
I really appreciate you investigating further.

I'm probably a bit too close to the code which means I could overlook something blatantly obvious. I've tried to document the authentication and authorization process so that others can more easily follow the code and double-check for possible issues. All my notes below.

> I wonder if an error did occur and caused a race condition if two users authenticated against GitHub Oauth around the same time

It sounds like one of the users was already authenticated. Upon authentication a token is stored in the browser's localStorage with the embedded user id. If this individual refreshed the page that token would be retrieved from localStorage and re-used, as opposed to going through the authentication flow.

Assuming a user was already authenticated and had a token, we can walk through the code path that was likely executed when invoking the `/api/user` endpoint:

1. `SetUser` middleware function is invoked to get the user from the session and inject into the request `Context`. See https://github.com/drone/drone/blob/master/server/middleware/user.go#L14
    * The `user_id` is parsed from the session token (sent in an http header). The user is retrieved from the database and returned. See https://github.com/drone/drone/blob/master/server/session/session.go#L73
2. `RequireUser` middleware function is invoked to verify the user was properly retrieved and added to the session.
See https://github.com/drone/drone/blob/master/server/middleware/user.go#L29
3. `GetCurrentUser` handler is executed. The user is extracted from the request `Context`, converted to json, and written to the response. See https://github.com/drone/drone/blob/master/server/handler/user.go#L21

Since the `user_id` is embedded in a signed token stored in the browser it has me a bit stumped how it could return the data for the wrong `user_id`. This has me wondering if:

1. two users somehow ended up with the same id, and the newer account overwrote the older account
2. somehow a user was created with an id of zero. The code assumes a minimum id of 1, so an id of zero could definitely lead to some unexpected scenarios
3. we passing the context (User) data from middleware -> middleware -> request in a manner that should be thread safe. Maybe somehow it isn't

Now if the user refreshed the page and it did re-authenticate (instead of re-using a token) we would see the following code path:

1. `GetLogin` handler is invoked and delegates authentication to the GitHub plugin. See https://github.com/drone/drone/blob/master/server/handler/login.go#L24
2. `Authorize` plugin function invoked. See https://github.com/drone/drone/blob/master/plugin/remote/github/github.go#L57
  * We perform the oauth dance and get the `code` back from GitHub which is used to retrieve an access token. See https://github.com/drone/drone/blob/master/plugin/remote/github/github.go#L83
  * We use the access token to make an API call to get the user's Login. See https://github.com/drone/drone/blob/master/plugin/remote/github/github.go#L89
2. `GetLogin` retrieves the Drone user from the database for the matching user Login. See https://github.com/drone/drone/blob/master/server/handler/login.go#L47
  * It inserts a new user into the database if not found. See https://github.com/drone/drone/blob/master/server/handler/login.go#L67 
  * It updates the user to ensure we have the latest GitHub data (email, etc). See https://github.com/drone/drone/blob/master/server/handler/login.go#L88
3. `GetLogin` redirects the user back to the browser with a signed token containing the embedded `user_id`. See https://github.com/drone/drone/blob/master/server/session/session.go#L43 and  https://github.com/drone/drone/blob/master/server/handler/login.go#L110

>  and both cookieState and state were storing empty strings. I'll look more closely into that.

This state does not contain any user-identifiable data. So even if these strings got botched I'm not sure it could lead to confusion of user ids.

**Comment by mattbostock** [comment]
I no longer have the database used when this issue occurs unfortunately.

I'll continue to keep an eye out for this issue.

**Comment by bradrydzewski** [comment]
I added code to require user id > 0 and to be more explicit about inserting vs updating (previously we used a save function which could do either). I'm not sure either of these made a difference, but the code is less sloppy as a result

**Comment by bradrydzewski** [comment]
can re-open if this issue re-appears
