### ISSUE TITLE
What's the use case for the CLI versus the web UI (as admin)?

### ISSUE THREAD

**Issue by mattbostock** [drone/drone#806]
Not an issue but more of a question; what's the purpose of the commandline tool as opposed to using the web UI as an admin?

I'd like to better understand the distinction between the two - it seems that some actions (e.g. disable a repo) would be desirable in the UI, but I feel I'm missing some context.

**Comment by bradrydzewski** [comment]
> Not an issue but more of a question; what's the purpose of the commandline tool as opposed to using the web UI as an admin?

The command line utility is a good place to add functionality because it is stable -- the code is not changing frequently. The user interface, however, is changing very frequently and in very major ways.

Ultimately I'm not opposed to having functionality in the user interface (like disabling a repository, etc) however the more we include in the user interface the more it slows down our ability to iterate. It is a tradeoff. 

I also don't want anyone to get upset if, in the interest of releasing early and often, we push a new user interface concept that omits functionality they previously contributed.

We did contract a designer, so I'm hoping we can stabilize the user interface soon.

> I'd like to better understand the distinction between the two - it seems that some actions (e.g. disable a repo) would be desirable in the UI, but I feel I'm missing some context.

The initial decision regarding what to include was based on usage metrics extracted from our hosted service. We have a pretty good sample size (>10,000 developers). This is the piece of context that, unfortunately, isn't as transparent as I'd like.

**Comment by mattbostock** [comment]
Thanks for clarifying, that's really helpful.
