### ISSUE TITLE
Drone killed build

### ISSUE THREAD

**Issue by bbaugher** [drone/drone#825]
Hi I have been trying out drone by setting it up using vagrant and an ubuntu 14.04 image. I managed to get everything running but it seems my builds keeps getting killed,

    /usr/local/bin/drone: line 82:    48 Killed                  bundle install

This is always right around the 4-5m mark. The part it gets killed at usually takes awhile as its installing native dependencies but I haven't been able to get a successful build in drone. I tried increasing the timeout to some ridiculous setting but that didn't do anything. I also don't see anything in the drone or docker logs that might help. I'm running version 0.3.0-alpha.

**Comment by bradrydzewski** [comment]
@bbaugher this likely means the process (Docker container) is getting killed by the OS for running out of memory (via the OOM killer). The fact that it happens at the same spot in the build makes this even more likely, especially if they are native dependencies and being compiled, which is resource intensive.

If the root cause is OOM it may explain why nothing was in the logs. To Docker and Drone, this will just look like the process exited with an error code. I'm not sure either Docker or Drone have visibility into why a process exited. The best we can do is pick up the error code and signal.

I recommend increasing your memory in virtual box (> 2GB) and giving it another try. Let me know if that helps!

**Comment by bbaugher** [comment]
Ah yes, probably should have thought of that one. I also probably should have just stolen your Vagrantfile and removed the provisioning part to begin with. Thanks for the quick response and awesome project!

**Comment by bradrydzewski** [comment]
cool, if that doesn't fix let me know and I'll re-open
