### ISSUE TITLE
Trigger Builds from Pull Request Comments (and run Privileged)

### ISSUE THREAD

**Issue by dave-tucker** [drone/drone#838]
We have some tests that require the container to be run as privileged. These tests should be run on _every_ PR before it is merged.

The current security model would have these test run on `master` only, which doesn't prevent us merging code that will fail the full test suite.

My proposal is for Drone to listen to the [IssueCommentEvent](https://developer.github.com/v3/activity/events/types/#issuecommentevent) for a given PR and react to comments from users who have Admin permissions in Drone. 

For example:
- `recheck` will re-run the tests
- `recheck trusted` will re-run the tests and enabled Privileged and/or Private ENV Variables

A logical extension to this proposal would be to maintain a whitelist of users for which builds will run trusted by default. I'd suggest that Drone Admins would be sensible starting point and then adding the the ability to add more users either via the UI or even through comments e.g `whitelist`

**Comment by bradrydzewski** [comment]
@dave-tucker I think it is a great idea. We could take the username of the author and then cross reference against our list of user permissions. Pull requests that are not authorized could be given a special status that requires intervention to proceed (ie going into the user interface and manually triggering).

Note that this would only apply to public repositories, since private repositories will always allow a pull request to run in privileged mode.

I'd like to avoid any sort of white list for the time being and see how much we can get done with native GitHub or Bitbucket permissions. These systems both have really solid team and role management that might be adequate for the majority of projects.

It would be great to pilot this with GitHub, and if it works well, expand to all the other systems

**Comment by bradrydzewski** [comment]
closing this in favor of the new gating mechanism which should satisfy this use case
