### ISSUE TITLE
Services do not operate correctly when docker net host option is specified

### ISSUE THREAD

**Issue by dave-tucker** [drone/drone#839]
The addition of `--net` in #617 is awesome, I need it, but I may have found a bug - I don't have bandwidth to test this one out at the moment though...

The implementation of `services` looks to rely on Docker Links 
https://github.com/drone/drone/blob/0a6227930dce3e356667506bc950530a9d847c61/shared/build/build.go#L346

Links and `--net=host` are not supported https://github.com/docker/docker/pull/7066

A possible workaround might be to run service containers in `--net=host` but you might run in to port conflict issues if you are, for example, using postgres as the backend for your Drone install and attempting to run a postgres service.

**Comment by bradrydzewski** [comment]
cool, we can test it out and see. I think we must have accepted a competing pull request (I'll verify), because you can specify the net parameter in your yaml:

```
docker:
  net: host
```

**Comment by dave-tucker** [comment]
@bradrydzewski sorry I might not have been clear in my original message...
I've managed to confirm this one, given the following `drone.yml`
    
    ---
    image: library/golang:1.3
    docker:
      net: host
    services:
      - mysql
    script:
      - env
      - echo "Hello World"
      - ip a
      - sleep 30

**Comment by floatdrop** [comment]
@dave-tucker can you give a hint, why you need a `net: host` for drone? We managed to get up and running Docker 1.5 with IPv6-only setup without using it.

**Comment by dave-tucker** [comment]
@floatdrop we need our `services` and the container where the tests are run to share the same network namespace. `net: host` works, although using docker's `--net=container:<container_name_or_id> would be much safer, but at the time of writing that functionality didn't exist in drone.

**Comment by bradrydzewski** [comment]
@dave-tucker I'm working on a patch that implement `--net=container:{container}`. Hopefully will have something to demo next week.

**Comment by electrofelix** [comment]
Without drone supporting vagrant directly, where VM's are needed (involving building VM images, testing software making use of kernel modules, alternative OS's, etc) use of --net=host seems like it would be required for vagrant inside of a container image to be able to talk to VM's launched via libvirt.

Something like https://hub.docker.com/r/twiest/docker-vagrant-libvirt/

Just evaluating drone here as a replacement, and to be able to limit the use of VM's to just the project being tested rather than needing to also bring up additional services it needs as VM's along side it would be very useful.
