### ISSUE TITLE
oauth with existing gitlab fails since drone 0.3.0-alpha

### ISSUE THREAD

**Issue by epcim** [drone/drone#851]
After the drone login page the url is redirected to to gitlab web to renew "authentication". While the gitlab says 404.

```
Started GET "/oauth/authorize?client_id=&redirect_uri=https%3A%2F%2Fdrone.vums.blueit%2Fapi%2Fauth%2Fgitlab.com&response_type=code&scope=api&state=ESXHFAQCELJYH6LKTTT3MO2VVYXNWXMDENGK7RCFW44Y6ZVM3GRQ%3D%3D%3D%3D" for 127.0.0.1 at 2015-01-26 19:59:20 +0100
Processing by ProjectsController#show as HTML
  Parameters: {"client_id"=>"", "redirect_uri"=>"https://drone.vums.blueit/api/auth/gitlab.com", "response_type"=>"code", "scope"=>"api", "state"=>"ESXHFAQCELJYH6LKTTT3MO2VVYXNWXMDENGK7RCFW44Y6ZVM3GRQ====", "id"=>"oauth/authorize"}
Filter chain halted as :project rendered or redirected
Completed 404 Not Found in 4ms (Views: 0.4ms | ActiveRecord: 0.3ms)

```
no logs in drone.log (what is  a way to enable more verbose or debug logging?)

obviously recent drone update in gitlab oauth do not fit older gitlab (6.8.2 in my case).

**Comment by bradrydzewski** [comment]
@epcim I'm sorry but Drone now requires GitLab 7.7. We've updated the docs to reflect this requirement. There was no logging because technically Drone didn't encounter and error. Drone forwarded to GitLab (as expected) but GitLab halted the OAuth flow since that version doesn't support OAuth.

I do apologize for this inconvenience. We try to limit breaking changes, but in this case we really wanted to eliminate the need to enter your GitLab username / password into Drone.
