### ISSUE TITLE
drone's rpm not compatible with CentOS 6

### ISSUE THREAD

**Issue by lenaten** [drone/drone#873]
CentOS 6 come with glibc 2.12, but drone's rpm generated on machine with glibc 2.14.

If CentOS 7 is a requirement, we need to make it clear.

**Comment by bradrydzewski** [comment]
we've altered our build process for the 0.4 version. First, we are running our build in a Debian container instead of an Ubuntu container, which means we are using glibc 2.1.2. Second, we ship Drone as a Docker image instead of using distro-specific packing (rpm, deb, etc)

drone image, for reference:
http://readme.drone.io/docs/setup/
