### ISSUE TITLE
Build timeout in yaml

### ISSUE THREAD

**Issue by donny-dont** [drone/drone#910]
The build timeout should be able to be set in the yaml. The settings area isn't available to most users so its not common knowledge that there is a build time out.

Additionally if a build fails due to a timeout this should be reflected in the UI so you know whether you should increase the timeout.

**Comment by bradrydzewski** [comment]
proposed solution is to store a timeout value at the repository level (in the database) so that the administrator has the final say in the build timeout. This value will be set very high by default.

the build will take the `Max(yaml.Timeout, repo.Timeout)`

when a build times out we set a default exit code which we should be able to use in the user interface to service exactly what error occurred without any backend code changes. Need to research further.

**Comment by bradrydzewski** [comment]
closing in preparation for 0.5 which has smarter timeout logic, automatically killing the build if no terminal output is received after N minute (default 10). This attempts to solve this exact same issue, but with a different solution. If we decide the solution is inadequate we can re-open and implemented the suggestion yaml-based timeout
