### ISSUE TITLE
IS_PULL_REQUEST environment variable 

### ISSUE THREAD

**Issue by themihai** [drone/drone#922]
Drone should provide an environment variable on pull request so that we can avoid deploying.

Related to #156

**Comment by davidak** [comment]
drone should never deploy builds of pull requests.

**Comment by themihai** [comment]
I mean custom deployment not using an existing drone plugin (i.e. Heroku, S3 etc).

**Comment by davidak** [comment]
the variable is of course useful to do that.

**Comment by floatdrop** [comment]
@themihai isn't [CI_PULL_REQUEST ](https://github.com/drone/drone/blob/a339b54905465cefe1ffed6eb80b2c7ef7a5c6d8/shared/build/build.go#L497) is what you are looking for?

**Comment by bradrydzewski** [comment]
you can use `CI_PULL_REQUEST` as mentioned. In addition, there is a bash plugin that simply executes shell commands during the deployment phase of your build:

```
deploy:
  bash:
    script:
      - echo foo
      - echo bar
    when:
      branch: master
```

I would recommend this approach because deployments won't execute for pull requests, and you have control over which branches the bash step executes for (if you need this).
