### ISSUE TITLE
Encrypted values / variables - and Shared values

### ISSUE THREAD

**Issue by predominant** [drone/drone#929]
Currently (I believe) there is no way to inject information securely into the build.

Use case:
I'm using Drone.io (open source) to run tests against chef cookbooks. With an internal berkshelf server, I need to deploy a key into the container so it can communicate with the internal berkshelf server. If I configure this through the web ui there are 2 problems:
1. The value is plain text / can be read by anyone?
2. I have to set this value on every repository - An organisation level, or user level setting would be more desirable to apply to all builds.

**Comment by bradrydzewski** [comment]
if you go to your repository settings page (in Drone) there is a section for private variables. You may enter private variables in `key: value` format (like yaml). These variables get injected into your build as environment variables so that you don't need to store sensitive data in your yaml file.

there is an open issue for global variables (#716)

feel free to ask these sort of questions in the chat room: gitter.im/drone/drone
