### ISSUE TITLE
Garbage Collection

### ISSUE THREAD

**Issue by nils-werner** [drone/drone#938]
Currently drone doesn't seem to care about docker garbage messing up the system. I wrote three scripts to remove unneeded cruft:

    # clear containers
    sudo docker.io stop $(sudo docker.io ps -qa)
    sudo docker.io rm $(sudo docker.io ps -qa)

    # clear images with drone- prefix (no idea what they're for)
    sudo docker.io rmi $(sudo docker.io images -a | grep "^drone-" | awk '{print $3}')

    # clear images wihout tag
    sudo docker.io rmi $(sudo docker.io images -a | grep "^<none>" | awk '{print $3}')

Not having run the scripts for a few months on a system with approx 5 builds per day it takes a significant amount of time to complete.

It would be nice if there were a way of making drone make more conscience use of resources.

**Comment by bradrydzewski** [comment]
Drone attempts to cleanup and delete every single resource it creates:
https://github.com/drone/drone/blob/master/shared/build/build.go#L271

There are prior versions of Docker that were buggy and failed to remove images and containers. Docker introduced a `force` flag in one of the newer versions to force-remove containers or images to fix this exact issue.

This has been added to the `0.4` release to force delete everything:
https://github.com/bradrydzewski/drone/blob/0.4.0/shared/builder/build.go#L79

**Comment by davidak** [comment]
if you don't need a container after it stopped, you can start it with `--rm`

**Comment by bradrydzewski** [comment]
@davidak this is pretty much what we are doing today, however, we do not invoke the `docker` command line utility. Drone speaks to Docker directly using the [remote API]. Similar to `docker run --rm`, Drone attempts to remove any containers or images that it creates.

You can see this code here:
https://github.com/drone/drone/blob/master/shared/build/build.go#L271

I've been running `test.drone.io` for quite some time and don't have any orphan containers or images. I believe these issues could be specific to Docker versions or even OS. If you search the Docker repository on GitHub you will find a ton of issues related to failures to remove Docker containers.

I think this issue is a bit presumptuous that Drone doesn't attempt to cleanup after itself. It does. It could very well be a Drone issue. It could be a Docker issue. I don't really have enough information to troubleshoot or diagnose.

**Comment by bradrydzewski** [comment]
also, I think there are a bit more constructive ways to log an issue than this:

> Currently drone doesn't seem to care about docker garbage messing up the system

**Comment by nils-werner** [comment]
Ah, it never occurred to me that my version of docker does not implement a certain feature drone is trying to use. I am running the default version on Trusty:

    nils@ci:~$ docker.io version
    Client version: 1.0.1
    Client API version: 1.12
    Go version (client): go1.2.1
    Git commit (client): 990021a

> also, I think we can find more constructive ways to log an issue than this:

Sorry, didn't want to sound mean. I just don't have enough insight into drone to know more precisely what was going on. Since I was using the system default I assumed it was simply a matter of drone not yet implementing garbage collection.

**Comment by thieman** [comment]
I am having this same problem. We run in the neighborhood of 100 builds a day, and after about a week or two we have so many dead images and containers built up that Drone slows to a crawl. We have been running scripts very similar to OP's to try to keep our system clean. No idea whether Drone or Docker is at fault, but Drone is reporting "removing build container" in its log without any further exceptions being logged.

Drone 0.2.1, Ubuntu 12.04, Linux 3.13, if that turns out to be relevant.

**Comment by bradrydzewski** [comment]
0.4 fixes prior issues with build images and containers not being cleaned up. 

Pulling newer images (build images, service images or otherwise) may create untagged images. This is a Docker issue and is out of the scope of Drone. I recommend running a cleanup utility on your build machines:

https://github.com/tutumcloud/cleanup
https://github.com/spotify/docker-gc

**Comment by kkimdev** [comment]
It would be very nice if Docker image cleanup is seamless with Drone IO.  From users point of view, this is just one more manual thing to care about.

I feel like it's not wrong for Drone IO to delete deprecated docker images as Drone IO is pulling those images at the first place.

Or if that's not desired, would it be possible to make a cleaning up Drone IO plugin?  I guess it would required privileged mode at least? http://docs.drone.io/privileged-mode/

**Comment by bradrydzewski** [comment]
> I feel like it's not wrong for Drone IO to delete deprecated docker images as Drone IO is pulling those images at the first place.

This is not necessarily true. The docker cache on the host machine is shared by all users and processes using docker on the host machine. I do not want Drone to be in the business of trying to decide which containers are safe to delete vs which should be left alone.

For this reason I recommend using a well known tool like [yelp/docker-custodian](https://github.com/yelp/docker-custodian) to purge images based on rules that you define and can confirm are safe to remove.

**Comment by bradrydzewski** [comment]
I also meant to post this snippet that you can add to your docker-compose to schedule regular cleanup.

```
services:
  docker-custodian:
    image: yelp/docker-custodian
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    command: [ dcgc, --max-image-age, 30days ]
```

Note the above configuration is a sample and should be tuned for your environment, with [pattern matching](https://github.com/Yelp/docker-custodian#prevent-images-from-being-removed) configured to prevent pruning commonly used images.

**Comment by kkimdev** [comment]
thanks for the tip ! 👍  I think that's convenient enough for me :)

**Comment by bradrydzewski** [comment]
good to hear :)

If you come up with an optimal configuration for pattern matching, please share. This is definitely something we should add to the documentation, with some example patterns.

**Comment by kkimdev** [comment]
Sounds good. 

It looks like https://github.com/yelp/docker-custodian can remove old images with optional exclusion name filter.

For me, I think the ideal rules are:
- Removing all untagged images not in use. (users pull images by digest shouldn't do this but I believe that's really rare)
- Removing all images not in use older than x days (ideally access time, but Docker doesn't support that https://github.com/moby/moby/issues/4237 so maybe just have to use creation time instead).

Seems pretty simple and I'm not too sure why I would need another package to do this, and docker-custodian doesn't seem to support the first rule.  Maybe I'm underestimating the potential edge cases of the task?

But anyways, I think running the following commands regularly or after every build should be good.

```bash
# Images in use, like drone/agent and drone/drone won't be removed by docker image rmi
docker images --format "{{.ID}} {{.Tag}}" | awk '$2 == "<none>" {print $1}' | xargs docker image rmi
# I didn't complete this line
docker images --format "{{.ID}} {{.CreatedAt}}" | [filter by creation date] | xargs docker image rmi
docker system prune
```

**Comment by kkimdev** [comment]
I realized that the creation date on `docker images` command is actually image compilation date, not pull date :/.  So deleting based on creation date doesn't seem like a good idea...

btw, I'm using the following.

```yml
  docker-remove-untagged-image:
    image: docker
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: |
      /bin/sh -c "
      while true; do
        docker images --format \"{{.ID}} {{.Tag}}\" | awk '$$2 == \"<none>\" {print $$1}' | xargs -r docker image rmi || true
        sleep 60
      done
      "
```

**Comment by bradrydzewski** [comment]
We have an official garbage collector that is specifically tailored for use with drone. It implements an lru cache algorithm for image removal, and will avoid removing objects (e.g. volumes) that are being used by an executing pipeline. https://github.com/drone/drone-gc
