### ISSUE TITLE
Drone doesn't work with Gitlab 7.9+

### ISSUE THREAD

**Issue by jumbojett** [drone/drone#942]
As @kowalczykp and others have noted on Gitter, 
Drone does not appear to work with the latest versions of Gitlab. Drone will issue a 400 Bad Request for all incoming webhooks.

Manually verified with tcpflow on ubuntu.
`tcpflow -p -c -i eth0 port 80`

Seems to stem from the gitlab go library.
https://github.com/Bugagazavr/go-gitlab-client/blob/master/hook_payload.go#L93

Indirectly the message reads. *"Invalid hook received, payload format not recognized."*

**Comment by bradrydzewski** [comment]
@jumbojett thanks for reporting and taking the time to troubleshoot. If you have any other insights into the failure that you can provide it would be greatly appreciated.

@Bugagazavr have you tried with newer versions of Gitlab yet? Was wondering if you might know what the issue might be.

Thanks everyone!

**Comment by arrowcircle** [comment]
I think latest gitlab now support oauth. Maybe this is the problem. But in general, it will make gitlab intergration are much more like github

**Comment by bradrydzewski** [comment]
@arrowcircle Drone's gitlab implementation switched to oauth a few weeks back.

As a side note, this has opened up a new set of problems due to GitLab's oauth token refresh policies. When a token is refreshed it immediately expires all outstanding tokens (which is valid per the spec, but not something I've seen in other implementations). This means if two threads attempt to refresh a token at the same time we can hit race conditions, which likely will happen since loading a single page in Drone fires off multiple API requests.

**Comment by jumbojett** [comment]
@bradrydzewski @arrowcircle 
**Update** -  The go-gitlab-client json parser is not liking the keys or values of the JSON object being returned. (i.e. it doesn't match it's STRUCT pattern)

Commenting out line 92,93 fixes the issue, but breaks the verification of the JSON attributes.
https://github.com/Bugagazavr/go-gitlab-client/blob/master/hook_payload.go#L93

**Comment by Bugagazavr** [comment]
So looks like in latest gitlab version hooks has been changed

**Comment by Bugagazavr** [comment]
@bradrydzewski done you can rebuild drone.

**Comment by jumbojett** [comment]
@Bugagazavr :clap: thank you

**Comment by jumbojett** [comment]
@bradrydzewski I'm closing the issue. A rebuild is necessary for others using the built packages.
