### ISSUE TITLE
Drone container linking problem [0.3.0-alpha]

### ISSUE THREAD

**Issue by wdalmut** [drone/drone#945]
Hi,

i am trying to work with drone and I have a problem with services. i have to set of integration tests that runs agains a mongodb database. 

My drone file is this one:  

```
image: wdalmut/php:5.5
services:
  - wdalmut/mongo:2.6
script:
  - echo "date.timezone=Europe/Rome" > /usr/local/etc/php/php.ini
  - echo "memory_limit=512M" >> /usr/local/etc/php/php.ini
  - curl -Ss http://getcomposer.org/installer | php
  - php composer.phar install
  - bin/phpunit -c app
```

The script section works correctly and the container is correctly prepared and executed. Same things for the MongoDB service that is effectively started as described in my `.drone.yml`

The problem is that containers are not linked and my testing scenarios cannot connect to mongodb using "locahost:27017".

I have also inspected both containers and there is no linking between them.

I checked out the docs and i see that the `.drone.yml` is correctly configured. There is anything that i'm missing?

Thanks
Walter

**Comment by bradrydzewski** [comment]
Hey there, you'll want to install `socat` inside your `wdalmut/php:5.5` image. Drone uses `socat` in order to proxy linked containers over localhost (this will change in drone 0.4, but is required for now). You'll also need to ensure port 27017 is exposed in your mongo Dockerfile, similar to the following:
https://github.com/drone/images/blob/master/database/mongodb/mongodb_2.4/Dockerfile

Drone will use the remote API to inspect exposed containers and automatically link to your build container.

Feel free to jump into Gitter if you have any further questions:
https://gitter.im/drone/drone

**Comment by wdalmut** [comment]
@bradrydzewski thanks you so much!!
