### ISSUE TITLE
Bash dependency inside containers

### ISSUE THREAD

**Issue by JeanMertz** [drone/drone#948]
I've noticed some bash scripting going on inside Drone which expects `bash` to be present in a container.

With the "minimal containers" approach, this can become a problem. See for example: https://github.com/blendle/docker-ruby/pull/3

Any thoughts on refactoring the scripts to only use bourne-shell compatible scripts?

**Comment by bradrydzewski** [comment]
Agreed. In fact this was fixed in the matrix demo I gave. We are moving toward a plugin model, and you can see this plugin that is responsible for generating the build script:
https://github.com/drone-plugins/drone-build

It removes the traps which are probably the biggest issue. The only requirement is base64 which is used to properly echo our build commands:
https://github.com/drone-plugins/drone-build/blob/master/main.go#L39

Plugins are swappable, so hypothetically you'll be able to swap this plugin with an alternate implementation for generating a shell script.

Let's track progress for this in #902 since it encapsulates the issue you've described.
