### ISSUE TITLE
Add branch condition on notify webhook

### ISSUE THREAD

**Issue by alexandre-butynski** [drone/drone#976]
We can use conditions like that in the *publish* plugins :

```yml
when:
  branch: master
```

It would be great to be able to use it in the *notify* plugins. My use case (in few words) is to notify a static analysis application to analyse the new version of the code from xml files uploaded to s3 by Drone. I want to do it only for the master branch to avoid inconsistency in temporal graph.

**Comment by bradrydzewski** [comment]
hey there, we've revamped the yaml in the upcoming 0.4 release so that every step (deploy, publish, notify etc) all have the ability to filter on branch. We are moving to a more generic data structure for each step to facilitate this:

```diff
// Step represents a step in the build process, including
// the execution environment and parameters.
type Step struct {
	Image       string
	Pull        bool
	Privileged  bool
	Environment []string
	Entrypoint  []string
	Command     []string
	Volumes     []string
	WorkingDir  string `yaml:"working_dir"`
	NetworkMode string `yaml:"net"`

	// Condition represents a set of conditions that must
	// be met in order to execute this step.
+	Condition *Condition `yaml:"when"`

	// Config represents the unique configuration details
	// for each plugin.
	Config map[string]interface{} `yaml:"config,inline"`
}
```

Let's track this under #902 since it encompasses this functionality  The 0.4 release is in-progress and slated for alpha in about 2 weeks, at which point you'll be able to try it out.

**Comment by alexandre-butynski** [comment]
It seems that all my needs will be satisfied by this new version ! Thanks again for that.
